### ISSUE TITLE
SharePoint Online unable to load external scripts

### ISSUE THREAD

**Issue by 4lexk** [SharePoint/sp-dev-docs#1442]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

External scripts were loaded respecting global dependencies from config.json

#### Observed Behavior

Only scripts without configured dependencies could be loaded. Following message appears in the console:
`Uncaught (in promise) Error: ***Failed to load path dependency "jqueryui" from component "GUID" (TabsWebPart) due to another dependency that failed to load.`

also on the Web Part position:
```
[SPLoaderError.loadComponentError]:
***Failed to load component "f2258bfc-009e-4147-a873-9169b70336f4" (TabsWebPart).
Original error: ***Resource "jquery" not found in loader configuration of manifest for component "f2258bfc-009e-4147-a873-9169b70336f4" (TabsWebPart).

***INNERERROR:
***Resource "jquery" not found in loader configuration of manifest for component "f2258bfc-009e-4147-a873-9169b70336f4" (TabsWebPart).
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-23.004/sp-classic-page-assembly_en-us_04a9641e5a806d80bf5ea84ca30e78a4.js:201:15468)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-23.004/sp-classic-page-assembly_en-us_04a9641e5a806d80bf5ea84ca30e78a4.js:619:36351)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-23.004/sp-classic-page-assembly_en-us_04a9641e5a806d80bf5ea84ca30e78a4.js:619:42054)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-23.004/sp-classic-page-assembly_en-us_04a9641e5a806d80bf5ea84ca30e78a4.js:619:38634)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-23.004/sp-classic-page-assembly_en-us_04a9641e5a806d80bf5ea84ca30e78a4.js:619:11286
    at <anonymous>
```

#### Steps to Reproduce

config.json
```
"externals": {
    "jquery": {
      "path": "https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js",
      "globalName": "jQuery"
    },
    "jqueryui": {
      "path": "https://ajax.aspnetcdn.com/ajax/jquery.ui/1.12.1/jquery-ui.min.js",
      "globalName": "jQuery",
      "globalDependencies": [
        "jquery"
      ]
    },
    "jqueryCookie": {
      "path": "https://HOSTNAME.blob.core.windows.net/spwebparts/common/jquery.cookie.js",
      "globalName": "jQuery",
      "globalDependencies": [
        "jquery"
      ]
    }
```
Import externals via
```
import * as jQuery from 'jquery';
import 'jqueryui';
import 'jqueryCookie';
```

**Comment by 4lexk** [comment]
strange, but seems only to happen with Google Chrome... ?

**Comment by 4lexk** [comment]
appears only if "disable caching" was checked withing chrome develper toos...

**Comment by waqarjavaid25** [comment]
I am also facing this issue, does anybody find any solution.
