### ISSUE TITLE
Get started creating provider hosted SP add-ins guidance doc doesn't work

### ISSUE THREAD

**Issue by ADOrigin** [SharePoint/sp-dev-docs#1469]
I followed the steps in this article but when I run it it fails in Page_Load at the accessToken = TokenHelper.GetAccessToken... line.

NullReferenceException is occurring in TokenHelper.cs at line 298.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceb8bf6d-8d2b-d206-1e13-abe801b09894
* Version Independent ID: 79012988-7caa-a0ba-d7de-91f514550bb3
* Content: [Get started creating provider-hosted SharePoint Add-ins | Microsoft Docs](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-started-creating-provider-hosted-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/get-started-creating-provider-hosted-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-started-creating-provider-hosted-sharepoint-add-ins.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by dac2157** [comment]
Not working for me.  Getting :

Microsoft.SharePoint.Client.ServerUnauthorizedAccessException
  HResult=0x80131500
  Message=Access denied. You do not have permission to perform this action or access this resource.
  Source=Microsoft.SharePoint.Client.Runtime
  StackTrace:
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at SampleAddInWeb.Default.RetrieveWithCSOM(String accessToken) in C:\Users\aclark\source\repos\SampleAddIn\SampleAddInWeb\Pages\Default.aspx.cs:line 71
   at SampleAddInWeb.Default.CSOM_Click(Object sender, EventArgs e) in C:\Users\aclark\source\repos\SampleAddIn\SampleAddInWeb\Pages\Default.aspx.cs:line 46

on line 73.

**Comment by benjito** [comment]
this is broken, where is a decent example of this?

**Comment by psined1** [comment]
Information provided by this page is very misleading. In one place it says: "Two projects are created in the Visual Studio solution: one for the SharePoint Add-in and the other for the ASP.NET web application". But, as it walks you thru the code sample, it makes no reference as to which of the two projects you are making changes to.

**Comment by savannahp** [comment]
I need a good example of this asap, why is this so out of date?
