### ISSUE TITLE
serve does not respect "paths" in tsconfig.json

### ISSUE THREAD

**Issue by patrick-rodgers** [SharePoint/sp-dev-docs#1500]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Add paths to the tsconfig.json at the root of the project. Project builds correctly and `gulp serve` works as expected.

#### Observed Behavior

`gulp serve --nobrowser` and `gulp serve` both fail, seemingly breaking the underlying webpack setup.

```
[SPLoaderError.loadComponentError]:
***Failed to load component "5900ce92-4d58-43cb-9031-87e91bae4d4e" (FastTrackTeamsLeaderboardWebPart).
Original error: ***Failed to load entry point from component "5900ce92-4d58-43cb-9031-87e91bae4d4e" (FastTrackTeamsLeaderboardWebPart).
Original error: Cannot find module "@model/leaderboard"

***INNERERROR:
***Failed to load entry point from component "5900ce92-4d58-43cb-9031-87e91bae4d4e" (FastTrackTeamsLeaderboardWebPart).
Original error: Cannot find module "@model/leaderboard"
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-09.017/sp-webpart-workbench-assembly_en-us_c3f02c4336ecfb133175beae12f253ca.js:283:15646)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-09.017/sp-webpart-workbench-assembly_en-us_c3f02c4336ecfb133175beae12f253ca.js:641:37346)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-09.017/sp-webpart-workbench-assembly_en-us_c3f02c4336ecfb133175beae12f253ca.js:641:43235)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-09.017/sp-webpart-workbench-assembly_en-us_c3f02c4336ecfb133175beae12f253ca.js:641:39678)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-09.017/sp-webpart-workbench-assembly_en-us_c3f02c4336ecfb133175beae12f253ca.js:641:15596
    at <anonymous>
```

#### Steps to Reproduce

Add a "paths" entry as shown below to a local folder in the project and preview on online workbench using `gulp serve --nobrowser`

```
    "paths": {
      "@net/*": [
        "./src/net/*"
      ],
      "@model/*": [
        "./src/model/*"
      ]
    },
```

Thanks for your contribution! Sharing is caring.

**Comment by patrick-rodgers** [comment]
This is resolved by updating the paths to be as below and removing the "@" char. Going to close this issue as I doubt that has anything to do with spfx and everything to do with something buried in node module resolution. Thanks.

```
 "net/*": [
        "./src/net/*"
      ],
      "model/*": [
        "./src/model/*"
      ]
```
