### ISSUE TITLE
gulp deploy-azure-storage does not support an HTTP proxy

### ISSUE THREAD

**Issue by ferdinandosimonetti** [SharePoint/sp-dev-docs#153]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 
#### Category

[X] Question
[ ] Typo
[ ] Mistake
[ ] Additional article idea
#### Expected or Desired Behavior

I'm trying to perform the step 5 of the https://github.com/SharePoint/sp-dev-docs/wiki/HelloWorld,-Deploy-to-CDN; my PC (Windows 7 Professional SP1, joined to domain) is behind a corporate proxy that requires authentication, but I have access to a non-autenticated one too.
After having launched the "gulp deploy-azure-storage" command, there should be some message informing me that my new project has been uploaded to my Azure subscription.
#### Observed Behavior

When launching the above mentioned command, these error messages are occurring 

```
c:\Users\simonett\Documents\prova>gulp deploy-azure-storage                                                         
Build target: DEBUG                                                                                                 
[12:26:06] Using gulpfile c:\Users\simonett\Documents\prova\gulpfile.js                                             
[12:26:06] Starting gulp                                                                                            
[12:26:06] Starting 'deploy-azure-storage'...                                                                       
[12:26:06] Starting subtask 'deploy-azure'...                                                                       
Uploading files '**/*.*' from directory './temp/deploy/' to Azure                                                   
Created container: prova                                                                                            
[Error: Unable to create container: prova]                                                                          
Error: Unable to create container: prova                                                                            
    at c:\Users\simonett\Documents\prova\node_modules\@microsoft\sp-build-core-tasks\lib\deployAzureStorage\uploadCDN\azureStorage\ensureContainer.js:20:28                                                                             
    at c:\Users\simonett\Documents\prova\node_modules\azure-storage\lib\services\blob\blobservice.js:505:7          
    at finalCallback (c:\Users\simonett\Documents\prova\node_modules\azure-storage\lib\services\blob\blobservice.js:5103:7)                                                                                                             
    at c:\Users\simonett\Documents\prova\node_modules\azure-storage\lib\common\filters\retrypolicyfilter.js:176:13  
    at c:\Users\simonett\Documents\prova\node_modules\azure-storage\lib\common\services\storageserviceclient.js:674:17                                                                                                                  
    at c:\Users\simonett\Documents\prova\node_modules\azure-storage\lib\common\services\storageserviceclient.js:842:11                                                                                                                  
    at c:\Users\simonett\Documents\prova\node_modules\azure-storage\lib\common\services\storageserviceclient.js:673:15                                                                                                                  
    at processResponseCallback (c:\Users\simonett\Documents\prova\node_modules\azure-storage\lib\services\blob\blobservice.js:5106:5)                                                                                     
    at Request.processResponseCallback [as _callback] (c:\Users\simonett\Documents\prova\node_modules\azure-storage\lib\common\services\storageserviceclient.js:301:13)                                                                 
    at self.callback (c:\Users\simonett\Documents\prova\node_modules\azure-storage\node_modules\request\request.js:199:22)                                                                                                              
    at emitOne (events.js:77:13)                                                                                    
    at Request.emit (events.js:169:7)                                                                               
    at Request.onRequestError (c:\Users\simonett\Documents\prova\node_modules\azure-storage\node_modules\request\request.js:821:8)                                                                                                      
    at emitOne (events.js:77:13)                                                                                    
    at ClientRequest.emit (events.js:169:7)                                                                         
    at TLSSocket.socketErrorListener (_http_client.js:269:9)                                                        
[12:26:06] Finished subtask 'deploy-azure' after 195 ms                                                             
[12:26:06] Finished 'deploy-azure-storage' after 197 ms                                                             
[12:26:07] ==================[ Finished ]==================                                                         
[12:26:07] Project prova version: 0.0.1                                                                             
[12:26:07] Build tools version: 0.7.1                                                                               
[12:26:07] Node version: v4.5.0                                                                                     
[12:26:07] Total duration: 5.31 s  
```
#### Steps to Reproduce

Use Windows 7 Professional SP1 domain joined.
Put it behind some kind of HTTP proxy.
Follow the tutorials successfully, until reaching step 5 of the "Helloworld, upload to CDN" one.
Execute "gulp deploy-azure-storage" from the root directory of the project.

**Comment by nickpape-msft** [comment]
The deploy-azure-storage task uses [azure-storage](https://www.npmjs.com/package/azure-storage) on the back-end, which has the ability to configure a proxy..

Could you try setting the environment variables mentioned in that package?
```
set NODE_TLS_REJECT_UNAUTHORIZED=0
set HTTP_PROXY=http://127.0.0.1:8888
```

**Comment by patmill** [comment]
Closing this old bug out.  If it still happens, feel free to open a new bug.
