### ISSUE TITLE
Document mode IE10 on classic pages is giving problems with loading modules

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#1617]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When running an SPFx web part on a classic page, it should not behave differently as in running it on the modern pages.

#### Observed Behavior

We noticed that on some tenants, the document mode of the classic pages is still on IE10. When this is the case, the web part returns the following error when loading it in IE11:

```
ERROR:
***Failed to load component "8c1ebe8b-1fd0-41cd-b00c-0131456dad64" (CustomWebPart).
Original error: ***Failed to load entry point from component "8c1ebe8b-1fd0-41cd-b00c-0131456dad64" (CustomWebPart).
Original error: Error loading https://component-id.invalid/8c1ebe8b-1fd0-41cd-b00c-0131456dad64_1.2.0
	https://component-id.invalid/8c1ebe8b-1fd0-41cd-b00c-0131456dad64_1.2.0 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.

CALL STACK:
Error
   at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-classic-page-assembly_en-us_8a2e24d3437451ad709213aed85be0ba.js:201:15958)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-classic-page-assembly_en-us_8a2e24d3437451ad709213aed85be0ba.js:201:15494)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-classic-page-assembly_en-us_8a2e24d3437451ad709213aed85be0ba.js:691:37395)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-classic-page-assembly_en-us_8a2e24d3437451ad709213aed85be0ba.js:691:43286)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-classic-page-assembly_en-us_8a2e24d3437451ad709213aed85be0ba.js:691:39723)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-classic-page-assembly_en-us_8a2e24d3437451ad709213aed85be0ba.js:691:11324)
   at T (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-classic-page-assembly_en-us_8a2e24d3437451ad709213aed85be0ba.js:8:2116)
   at S (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-classic-page-assembly_en-us_8a2e24d3437451ad709213aed85be0ba.js:8:2232)
   at j (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-classic-page-assembly_en-us_8a2e24d3437451ad709213aed85be0ba.js:8:2026)
   at g (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-classic-page-assembly_en-us_8a2e24d3437451ad709213aed85be0ba.js:8:1608)
```

I have tested the web part on a couple of tenant, most of them are running in `IE=edge`, but we also have a couple running in `IE=10` (default Seattle.master is used, no customizations).

Loading the web part on a modern page works fine in IE11.

**Comment by VesaJuvonen** [comment]
This seems to be related to the MC127395 where we informed that we are moving away from the IE10 mode. That admin message also contained instructions to handle ghosted master pages, which seems to be the case in the tenants where you can see the issue - as the rollout has been already completed.

Key information about the guidance is available from the following article, as we apparently are not exposing these messages outside of tenant admin message center - https://www.linkedin.com/pulse/microsoft-making-some-changes-sharepoint-online-pages-yvonne-wright-1/. 

Closing as there's really nothing else we can do here. If you, however, see the issue still after re-ghosting the master pages, please let us know.

**Comment by bgreene2012** [comment]
Same here, still having the issue after setting compatibility to IE10
