### ISSUE TITLE
SPLoaderError.loadComponentError provider-hosted add-in

### ISSUE THREAD

**Issue by josecollazzi** [SharePoint/sp-dev-docs#1920]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
A  provider-hosted SharePoint Add-ins that I have been developing is throwing an error, the add-in shouldn't show any error. I am targeting SharePoint online.

#### Observed Behavior
A provider-hosted SharePoint Add-in that was working before is showing this error now.
````
Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "243166f5-4dc3-4fe2-9df2-a7971b546a0a" (ClientWebPart).
Original error: ***Manifest not found for component id "cc2cc925-b5be-41bb-880a-f0f8030c6aff" and version "1.1.0".

***INNERERROR:
***Manifest not found for component id "cc2cc925-b5be-41bb-880a-f0f8030c6aff" and version "1.1.0".
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-18.011/sp-pages-assembly_en-us_da042c18e645d3c9c8527469fe86d8da.js:320:15770)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-18.011/sp-pages-assembly_en-us_da042c18e645d3c9c8527469fe86d8da.js:1077:22396)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-18.011/sp-pages-assembly_en-us_da042c18e645d3c9c8527469fe86d8da.js:1077:14508)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-18.011/sp-pages-assembly_en-us_da042c18e645d3c9c8527469fe86d8da.js:1077:10707)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-18.011/sp-pages-assembly_en-us_da042c18e645d3c9c8527469fe86d8da.js:1077:64480
````

#### Steps to Reproduce

Install SharePoint add-in:

 https://files-manywho-com.s3.amazonaws.com/bb03e922-8a39-46e8-b492-aacd2ccb5a42/BoomiFlowsApp.app

**Comment by josecollazzi** [comment]
Cool. Thank you.

**Comment by patmill** [comment]
Closing - if you are still seeing this, please reopen.
