### ISSUE TITLE
Yeoman scaffolding taking too long?

### ISSUE THREAD

**Issue by simkessy** [SharePoint/sp-dev-docs#193]
#### Category
[ ] Question
[ ] Typo
[x ] Bug
[ ] Enhancement / Suggestion
[ ] Additional article idea

Maybe it's because I'm running this in Vagrant but I did `yo @microsoft/sharepoing` inside and empty directly and 45 minutes later it's still running. I'm assuming this isn't normal. My internet speed is fairly fast as well.  

Node -v 4.5.0
NPM -v 2.15.9 

I'm looking at my processes and it says NPM is using 200+ of my CPU% and 1.5GB of RAM. 

The host is a DELL XPS 13 i5-5200 with 8GB of ram
The VM has  4GBs assigned to it. 

It really should be enough so I'm not sure what's going on.

**Comment by waldekmastykarz** [comment]
Please upgrade npm to v3 by running in the command line

```
npm i -g npm
```

NPM v3 should improve the process of scaffolding new project slightly. Is there any particular part that's particularly slow or just the overall process?

**Comment by simkessy** [comment]
I updated to NPM 3.10.7 and it ran much faster but gave me these errors at the end

```
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7
npm ERR! path /vagrant/SPFx/test-2/node_modules/escodegen/bin/escodegen.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/SPFx/test-2/node_modules/escodegen/bin/escodegen.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/SPFx/test-2/node_modules/escodegen/bin/escodegen.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/SPFx/test-2/npm-debug.log
```

I also go this when it was generating:

```
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
```

It still said congrats you can run `gulp serve` but then I got this error:

```
vagrant@rails-dev-box:/vagrant/SPFx/test-2 $ gulp serve
module.js:327
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/SPFx/test-2/gulpfile.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by waldekmastykarz** [comment]
Could you delete your existing **node_modules** folder and then re-run `npm i` to restore dependencies?

**Comment by pgonzal** [comment]
I agree with Waldek.  After upgrading from NPM 2 -> NPM 3, you need to delete your node_modules folder and rerun `npm install`.  I am closing this bug.  Please reopen if you are still having trouble.
