### ISSUE TITLE
SPFx 1.5 Plusbeta Webparts do not work on classic pages in IE in some tenants

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#2032]
#### Category
- [X] Bug

#### Expected or Desired Behavior
1.5 plusbeta webparts should work on classic pages as well.

#### Observed Behavior
1.5 plusbeta webparts do not work on classic pages. The error is:
**Failt do load component ....
There was a network problem. This may be a problem with a HTTPS certificate...**
This happens only in some tenants. Probably Tenants without the first release option. And it only happens with IE, not with Chrome for example.

**Comment by patmill** [comment]
Hi Oliver, if there is a "more details" section, can you select it and paste the full error here?

**Comment by OliverZeiser** [comment]
Yes sure, here it is. This is from a Tenant without CDN enabled.
If CDN is enabled it shows a little more info, but I can only provide a very bad screenshot.

ERROR:
***Failed to load component "8fc0c955-948e-4e3a-95cd-61522a3f1edc" (ProjectConsolidationWebPart).
Original error: ***Failed to load entry point from component "8fc0c955-948e-4e3a-95cd-61522a3f1edc" (ProjectConsolidationWebPart).
Original error: Error loading https://component-id.invalid/8fc0c955-948e-4e3a-95cd-61522a3f1edc_0.0.1
	[Parchment] Invalid definition

CALL STACK:
Error
   at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-01.008/sp-classic-page-assembly_en-us_01c72e686d598674e3b85d99926a0e21.js:201:16082)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-01.008/sp-classic-page-assembly_en-us_01c72e686d598674e3b85d99926a0e21.js:201:15618)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-01.008/sp-classic-page-assembly_en-us_01c72e686d598674e3b85d99926a0e21.js:896:22388)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-01.008/sp-classic-page-assembly_en-us_01c72e686d598674e3b85d99926a0e21.js:896:14502)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-01.008/sp-classic-page-assembly_en-us_01c72e686d598674e3b85d99926a0e21.js:896:10695)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-01.008/sp-classic-page-assembly_en-us_01c72e686d598674e3b85d99926a0e21.js:896:64691)
   at S (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-01.008/sp-classic-page-assembly_en-us_01c72e686d598674e3b85d99926a0e21.js:8:2116)
   at T (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-01.008/sp-classic-page-assembly_en-us_01c72e686d598674e3b85d99926a0e21.js:8:2232)
   at j (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-01.008/sp-classic-page-assembly_en-us_01c72e686d598674e3b85d99926a0e21.js:8:2026)
   at g (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-01.008/sp-classic-page-assembly_en-us_01c72e686d598674e3b85d99926a0e21.js:8:1608)

![ie15plusbetaissue](https://user-images.githubusercontent.com/8672900/41397601-3e401cbc-6fa4-11e8-929e-0be6aac12d47.png)

**Comment by OliverZeiser** [comment]
The issue does not seem to be related to SPFx in general, since other webparts are working. I guess it must be something in my code so I am closing the issue
