### ISSUE TITLE
Errors thrown when using command gulp --ship when part is in directory path using square bracket characters.

### ISSUE THREAD

**Issue by KinsonDigital** [SharePoint/sp-dev-docs#2200]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When running the gulp command **gulp --ship**, I should get no CLI errors and web part should be prepared for packaging.

#### Observed Behavior

When running the gulp command **gulp --ship**, I get an error in the CLI that says No localized files are found under the root directory.  This occurs when the project is in a directory path that has the **"["** or **"]"** square bracket characters in the path. 

For example, if the web part lives in a folder with a path that contains the square bracket characters as shown below:
> C:\Temp\[WepPartProjects]\my-web-part

Then this error will occur when using the command **gulp --ship**.  Using the command **gulp package-solution --ship** will also throw errors.

**Specs**
- Windows 10 Pro 64-bit (10.0, Build 17134)

**Package Versions**
```
  "dependencies": {
    "@microsoft/sp-core-library": "1.5.1",
    "@microsoft/sp-webpart-base": "1.5.1",
    "@microsoft/sp-lodash-subset": "1.5.1",
    "@microsoft/sp-office-ui-fabric-core": "1.5.1",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.5.1",
    "@microsoft/sp-module-interfaces": "1.5.1",
    "@microsoft/sp-webpart-workbench": "1.5.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
```

**Error shown in CLI using gulp --ship:**

```
gulp --ship
Build target: SHIP
[09:44:16] Using gulpfile S:\TEMP\[WebPartProjects]\my-web-part\gulpfile.js
[09:44:16] Starting gulp
[09:44:16] Starting 'default'...
[09:44:16] Starting subtask 'configure-sp-build-rig'...
[09:44:16] Finished subtask 'configure-sp-build-rig' after 3.83 ms[09:44:16] Starting subtask 'pre-copy'...
[09:44:16] Finished subtask 'pre-copy' after 4.77 ms
[09:44:16] Starting subtask 'copy-static-assets'...
[09:44:16] Starting subtask 'sass'...
[09:44:16] Finished subtask 'copy-static-assets' after 471 ms
[09:44:16] Finished subtask 'sass' after 464 ms
[09:44:16] Starting subtask 'tslint'...
[09:44:17] Starting subtask 'typescript'...
[09:44:17] [typescript] TypeScript version: 2.4.2
[09:44:17] Finished subtask 'tslint' after 536 ms
[09:44:17] Finished subtask 'typescript' after 71 ms
[09:44:17] Starting subtask 'ts-npm-lint'...
[09:44:17] Finished subtask 'ts-npm-lint' after 1.5 ms
[09:44:17] Starting subtask 'api-extractor'...
[09:44:17] Finished subtask 'api-extractor' after 658 μs
[09:44:17] Starting subtask 'post-copy'...
[09:44:17] Finished subtask 'post-copy' after 584 μs
[09:44:17] Starting subtask 'collectLocalizedResources'...
[09:44:17] Error - 'collectLocalizedResources' sub task errored after 2.64 ms
 Error for resource "MyWebPartWebPartStrings": No localized files found under the root directory ("S:\TEMP\[WebPartProjects]\my-web-part") matching pattern "lib/webparts/myWebPart/loc/{locale}.js"
[09:44:17] 'default' errored after 1.03 s
[09:44:17]
[09:44:17] ==================[ Finished ]==================
Error - 'collectLocalizedResources' sub task errored after 2.64 ms

 Error for resource "MyWebPartWebPartStrings": No localized files found under the root directory ("S:/TEMP/[WebPartProjects]/my-web-part") matching pattern "lib/webparts/myWebPart/loc/{locale}.js"
[09:44:18] Project my-web-part version:0.0.1
[09:44:18] Build tools version:3.7.4
[09:44:18] Node version:v8.11.3
[09:44:18] Total duration:3.57 s
[09:44:18] Task errors:1
The build failed because a task wrote output to stderr.
Exiting with exit code: 1
```

**Error in shown in CLI using gulp package-solution --ship**

```
gulp package-solution --ship
Build target: SHIP
[09:45:15] Using gulpfile S:\TEMP\[WebPartProjects]\my-web-part\gulpfile.js
[09:45:15] Starting gulp
[09:45:15] Starting 'package-solution'...
[09:45:15] Starting subtask 'configure-sp-build-rig'...
[09:45:15] Finished subtask 'configure-sp-build-rig' after 3.48 ms[09:45:15] Starting subtask 'package-solution'...
[09:45:15] Verifying configuration...
[09:45:15] Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\@microsoft\sp-build-core-tasks\lib\packageSolution\packageSolution\createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\@microsoft\sp-build-core-tasks\lib\packageSolution\PackageSolutionTask.js:116:36)
    at DestroyableTransform.prefinish (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at prefinish (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DestroyableTransform.onend (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at S:\TEMP\[WebPartProjects]\my-web-part\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)[09:45:15] Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\@microsoft\sp-build-core-tasks\lib\packageSolution\packageSolution\createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\@microsoft\sp-build-core-tasks\lib\packageSolution\PackageSolutionTask.js:116:36)
    at DestroyableTransform.prefinish (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at prefinish (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DestroyableTransform.onend (S:\TEMP\[WebPartProjects]\my-web-part\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at S:\TEMP\[WebPartProjects]\my-web-part\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)[09:45:15] Error - 'package-solution' sub task errored after 21 ms

 No manifests were found in '*.json'. Ensure a build has completed successfully and that paths.manifestsMatch is correct
[09:45:15] 'package-solution' errored after 28 ms
[09:45:15]
[09:45:16] ==================[ Finished ]==================
Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/packageSolution/createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/PackageSolutionTask.js:116:36)
    at DestroyableTransform.prefinish (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at prefinish (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at S:/TEMP/[WebPartProjects]/my-web-part/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/packageSolution/createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/PackageSolutionTask.js:116:36)
    at DestroyableTransform.prefinish (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at prefinish (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (S:/TEMP/[WebPartProjects]/my-web-part/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at S:/TEMP/[WebPartProjects]/my-web-part/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)Error - 'package-solution' sub task errored after 21 ms
 No manifests were found in '*.json'. Ensure a build has completed successfully and that paths.manifestsMatch is correct
[09:45:16] Project my-web-part version:0.0.1
[09:45:16] Build tools version:3.7.4
[09:45:16] Node version:v8.11.3
[09:45:16] Total duration:2.58 s
[09:45:16] Task errors:3
The build failed because a task wrote output to stderr.
Exiting with exit code: 1
```

#### Steps to Reproduce

Make sure that the yeoman generator v2.0.3 and @microsoft/generator-sharepoint v1.5.1 are installed globally via NPM.

1. Create a folder somewhere on the hard disk to contain web part projects.  Make sure that the folder has the **"["** and **"]"** in the name of the folder.
	- Example: C:\Temp\\[WebPartProjects]

2. Inside of the **C:\Temp\\[WebPartProjects]** folder, create a directory called **my-web-part**.
	- Full path should be **C:\Temp\\[WebPartProjects]\my-web-part**.

3. Using the CLI and the [yeoman generator](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator), create a project using the settings below.  Follow yeoman steps inside the directory that the project will live in.

4. Type the command **yo**.

5. Choose the **@microsoft/sharepoint** generator.

6. When the generator asks for a solution name, choose **MyWebPart**.

7. Choose option **Sharepoint Online only (latest)**.

8. Choose option **Use the current folder**.

9. Use the choice of **N** for the question **Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without running any feature deployment or adding apps in sites?**

10. Choose the option **WebPart** for the question **Which type of client-side component to create? (Use arrow keys)**

11. Type **MyWebPart** for the question **What is your Web part name?**

12. Type anything you want for the question **What is your Web part description?**

13. Choose **No Javascript framework** for the question **Which framework would you like to use? (Use arrow keys)**

14. Once the project has been scaffolded and all the NPM packages are installed, type the command **gulp --ship** to observe the error stated above.

**Comment by VesaJuvonen** [comment]
Technically it's indeed a bug, but we are not right now planning to fix this as there's a clear workaround for avoiding special characters in the folder naming. We do apologize for the inconvenience.

**Comment by KinsonDigital** [comment]
@VesaJuvonen Not a problem.  Glad to hear it will be fixed.  Thanks for the response!!
