### ISSUE TITLE
window.require.config is not a function

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#2520]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

no errors

#### Observed Behavior

```
TypeError: window.require.config is not a function
at Function.e.addConfig (https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-08-31-sts_20180906.004/spoapp-mini-aafbc7c2.js:1:36515)
at https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-08-31-sts_20180906.004/splistdeferred-mini-66af9096.js:1:592064
at o.then (https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-08-31-sts_20180906.004/spofiles-mini-d7e693ce.js:1:25112)
at e._getSuiteNavShell (https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-08-31-sts_20180906.004/splistdeferred-mini-66af9096.js:1:591811)
at e.getO365Shell (https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-08-31-sts_20180906.004/splistdeferred-mini-66af9096.js:1:591345)
at https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-08-31-sts_20180906.004/spofiles-mini-d7e693ce.js:1:2246
at Object.k [as _notify] (https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-08-31-sts_20180906.004/spofiles-mini-d7e693ce.js:1:23350)
at Object.enter (https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-08-31-sts_20180906.004/spofiles-mini-d7e693ce.js:1:21837)
at e.d._run (https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-08-31-sts_20180906.004/spofiles-mini-d7e693ce.js:1:28805)
at e.d._completed (https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-08-31-sts_20180906.004/spofiles-mini-d7e693ce.js:1:28219)
```
#### Steps to Reproduce

I'm loading external library from node_modules in Command Set Customizer.

**Comment by KingKangMSFT** [comment]
Could you provide more information about your issue. Such as how to generate this problem

**Comment by AJIXuMuK** [comment]
I’ve tried both. But I can’t create simple example to reproduce. Maybe it’s just an issue when using specificc libraries. In my case - Monaco Editor. 
I will probably close this one as I can’t give more info right now.
