### ISSUE TITLE
issue while uploading package to SharePoint through VSTS release

### ISSUE THREAD

**Issue by veeramanx** [SharePoint/sp-dev-docs#2727]
I am getting an below mentioned error while running deployment through VSTS release. the same solution was working fine couple of weeks back.

```
 Build target: SHIP
2018-09-27T11:50:19.9745904Z Found config file: tslint.json
2018-09-27T11:50:19.9803375Z Found config file: tslint.json
2018-09-27T11:50:19.9830322Z D:\a\r1\a\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178
2018-09-27T11:50:19.9830647Z             throw new Error(prefix + os.EOL +
2018-09-27T11:50:19.9830851Z             ^
2018-09-27T11:50:19.9830962Z 
2018-09-27T11:50:19.9831203Z Error: JSON validation failed:
2018-09-27T11:50:19.9831726Z 
2018-09-27T11:50:19.9831930Z D:\a\r1\a\config\tslint.json
2018-09-27T11:50:19.9832054Z 
2018-09-27T11:50:19.9832154Z 
2018-09-27T11:50:19.9832270Z 
2018-09-27T11:50:19.9832472Z Error: #/ (Defines configuration options for the...)
2018-09-27T11:50:19.9832614Z 
2018-09-27T11:50:19.9832884Z        Additional properties not allowed: lintConfig,useDefaultConfigAsBase,removeExistingRules,displayAsWarning
2018-09-27T11:50:19.9833227Z     at validateObjectWithCallback (D:\a\r1\a\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178:19)
2018-09-27T11:50:19.9833813Z     at JsonSchema.validateObjectWithCallback (D:\a\r1\a\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:193:13)
2018-09-27T11:50:19.9834329Z     at JsonSchema.validateObject (D:\a\r1\a\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:175:14)
2018-09-27T11:50:19.9835031Z     at TslintCmdTask._readConfigFile (D:\a\r1\a\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:308:28)
2018-09-27T11:50:19.9835459Z     at TslintCmdTask.onRegister (D:\a\r1\a\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:87:32)
2018-09-27T11:50:19.9835820Z     at Object.initialize (D:\a\r1\a\node_modules\@microsoft\gulp-core-build\lib\index.js:299:24)
2018-09-27T11:50:19.9836194Z     at SPWebBuildRig.initialize (D:\a\r1\a\node_modules\@microsoft\sp-build-common\lib\BuildRig.js:61:19)
2018-09-27T11:50:19.9836559Z     at SPWebBuildRig.initialize (D:\a\r1\a\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:22:15)
2018-09-27T11:50:19.9836944Z     at SPWebBuildRig.initialize (D:\a\r1\a\node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js:15:15)
2018-09-27T11:50:19.9837334Z     at Object.exports.initialize (D:\a\r1\a\node_modules\@microsoft\sp-build-web\lib\index.js:23:17)
2018-09-27T11:50:19.9837649Z     at Object.<anonymous> (D:\a\r1\a\gulpfile.js:21:7)
2018-09-27T11:50:19.9837924Z     at Module._compile (module.js:652:30)
2018-09-27T11:50:19.9838187Z     at Object.Module._extensions..js (module.js:663:10)
2018-09-27T11:50:19.9838931Z     at Module.load (module.js:565:32)
2018-09-27T11:50:19.9839134Z     at tryModuleLoad (module.js:505:12)
2018-09-27T11:50:19.9839370Z     at Function.Module._load (module.js:497:3)
2018-09-27T11:50:19.9839764Z     at Module.require (module.js:596:17)
2018-09-27T11:50:19.9840012Z     at require (internal/module.js:11:18)
2018-09-27T11:50:19.9840265Z     at execute (C:\npm\prefix\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:28:18)
2018-09-27T11:50:19.9840639Z     at Liftoff.handleArguments (C:\npm\prefix\node_modules\gulp-cli\index.js:175:63)
2018-09-27T11:50:19.9843089Z     at Liftoff.execute (C:\npm\prefix\node_modules\gulp-cli\node_modules\liftoff\index.js:203:12)
2018-09-27T11:50:19.9843488Z     at module.exports (C:\npm\prefix\node_modules\gulp-cli\node_modules\flagged-respawn\index.js:51:3)
2018-09-27T11:50:19.9843805Z     at Liftoff.<anonymous> (C:\npm\prefix\node_modules\gulp-cli\node_modules\liftoff\index.js:195:5)
2018-09-27T11:50:19.9844133Z     at C:\npm\prefix\node_modules\gulp-cli\node_modules\liftoff\index.js:165:9
2018-09-27T11:50:19.9844446Z     at C:\npm\prefix\node_modules\gulp-cli\node_modules\v8flags\index.js:114:14
2018-09-27T11:50:19.9845315Z     at C:\npm\prefix\node_modules\gulp-cli\node_modules\graceful-fs\graceful-fs.js:43:10
2018-09-27T11:50:19.9845768Z     at FSReqWrap.oncomplete (fs.js:135:15)
2018-09-27T11:50:20.0279757Z ##[error]Gulp failed with error: C:\npm\prefix\gulp.cmd failed with return code: 1
2018-09-27T11:50:20.0316605Z ##[section]Finishing: Upload to SharePoint/CDN DEV
```

Please let me know if any have any idea. 

I am using 1.5.0-plusbeta version. also included dynamicdata

**Comment by KingKangMSFT** [comment]
Could you please provide more information? Such as the tslint.json file

**Comment by veeramanx** [comment]
here is my TSLink file 

{
  "$schema": "https://dev.office.com/json-schemas/core-build/tslint.schema.json", 
  "displayAsWarning": true,
  "removeExistingRules": true,
  "useDefaultConfigAsBase": false, 
  "lintConfig": {
    "rules": {
      "class-name": false,
      "export-name": false,
      "forin": false,
      "label-position": false,
      "member-access": true,
      "no-arg": false,
      "no-console": false,
      "no-construct": false,
      "no-duplicate-variable": true,
      "no-eval": false,
      "no-function-expression": true,
      "no-internal-module": true,
      "no-shadowed-variable": true,
      "no-switch-case-fall-through": true,
      "no-unnecessary-semicolons": true,
      "no-unused-expression": true,
      "no-use-before-declare": true,
      "no-with-statement": true,
      "semicolon": true,
      "trailing-comma": false,
      "typedef": false,
      "typedef-whitespace": false,
      "use-named-parameter": true,
      "variable-name": false,
      "whitespace": false
    }
  }
}

**Comment by jxnx888** [comment]
@veeramanx Hi, could you please provide a reproducible sample code in order me to reproduce your issue? I cannot reproduce and understand how did your occur this issue.

**Comment by Govardhan07** [comment]
@KingKangMSFT, Hello, any update on this "Error: JSON validation failed:" ?
