### ISSUE TITLE
SPWebPartErrorCode.MissingExpectedWebPartMemberError issue on modern page

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#2770]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

SPFX version: 1.6

Kept on getting this error message on modern page while it's fine on classic page.
Webparts randomly showing and throwing errors, but mostly throwing this error with following technical details:

[SPWebPartErrorCode.MissingExpectedWebPartMemberError]:
The class for web part WebPart.GenericCounterWebPart.0a46938e-4509-4839-a8d3-06c8eb3ebc8a,**_internalInitialize is missing an expected member '{1}'**.

***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.029/sp-pages-assembly_en-au_98e2e165fd94848f01fc16a21e14114d.js:745:15996)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.029/sp-pages-assembly_en-au_98e2e165fd94848f01fc16a21e14114d.js:1310:10419)
    at Function.t.createWithLogProperties (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.029/sp-pages-assembly_en-au_98e2e165fd94848f01fc16a21e14114d.js:1310:10992)
    at e._instantiateWebPart (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.029/sp-pages-assembly_en-au_98e2e165fd94848f01fc16a21e14114d.js:1310:79693)
    at e._initializeWebPart (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.029/sp-pages-assembly_en-au_98e2e165fd94848f01fc16a21e14114d.js:1310:81559)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.029/sp-pages-assembly_en-au_98e2e165fd94848f01fc16a21e14114d.js:1310:64472
***LOGPROPERTIES:
{"actualType":"function"}

Any idea what's going on, or am I missing something on the configuration?

Edit: I ran this on workbench/gulp serve and it works fine.. Only happened once its deployed..

**Comment by Seiyasu** [comment]
Please provide your current project configuration. And it should better you can provide an minimized reproduce project, so more guy can further assist you.

**Comment by jonathanhotono** [comment]
Ok, I will upload the project into public git repo for you guys to reproduce.

Thanks

**Comment by jonathanhotono** [comment]
After minimizing the project, I found a rogue external script being loaded that caused this issue. Closing this.
