### ISSUE TITLE
TypeError: Cannot read property 'entries' of undefined

### ISSUE THREAD

**Issue by ag0059985** [SharePoint/sp-dev-docs#28]
when trying to run this command 
yo @microsoft/sharepoint 
getting this below error...
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'entries' of undefined
    at module.exports.yeoman.Base.extend.prompting._updateConfig (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/generators/webpart/main.js:90:11)
    at module.exports.yeoman.Base.extend.prompting.writing (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/generators/webpart/main.js:70:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/yeoman-generator/lib/base.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by mauricionr** [comment]
@ag0059985 windows, linux or mac?

**Comment by ag0059985** [comment]
@mauricionr mac

**Comment by StfBauer** [comment]
Which node and npm version do you use?
```node -v && npm -v```

**Comment by ag0059985** [comment]
@StfBauer npm -v => 3.10.6
and node -v => v4.2.4

**Comment by StfBauer** [comment]
Have you applied one of these fixes to NPM?
https://docs.npmjs.com/getting-started/fixing-npm-permissions
It seems like you don't have permission there to read without sudo command.

**Comment by ag0059985** [comment]
@StfBauer this issue has been fixed now..
just uninstalled npm, gulp and yo..and installed it again..worked fine

thank you so much for all the help 👍
