### ISSUE TITLE
Azure Functions sample does not work

### ISSUE THREAD

**Issue by bogdan1v** [SharePoint/sp-dev-docs#2986]
One change is that the Azure Portal looks different when defining the Function. Copying the code, replacing the storage account and then trying to test the function you get an error. 
I'm pasting what shows up in the console below:
2018-11-21T04:51:41.163 [Error] Function compilation error
Microsoft.CodeAnalysis.Scripting.CompilationErrorException : Script compilation failed.
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.CreateFunctionTarget(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 314
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionLoader`1.GetFunctionTargetAsync[T](Int32 attemptCount) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionLoader.cs : 55
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.GetFunctionTargetAsync(Boolean isInvocation) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 183
2018-11-21T04:51:41.185 [Warning] run.csx(11,62): warning CS0618: 'TraceWriter' is obsolete: 'Will be removed in an upcoming version. Use Microsoft.Extensions.Logging.ILogger instead.'
2018-11-21T04:51:41.193 [Error] run.csx(16,34): error CS1061: 'HttpRequestMessage' does not contain a definition for 'GetQueryNameValuePairs' and no extension method 'GetQueryNameValuePairs' accepting a first argument of type 'HttpRequestMessage' could be found (are you missing a using directive or an assembly reference?)
2018-11-21T04:51:41.212 [Error] run.csx(47,19): error CS1061: 'CloudQueue' does not contain a definition for 'CreateIfNotExists' and no extension method 'CreateIfNotExists' accepting a first argument of type 'CloudQueue' could be found (are you missing a using directive or an assembly reference?)
2018-11-21T04:51:41.231 [Error] run.csx(52,19): error CS1061: 'CloudQueue' does not contain a definition for 'AddMessage' and no extension method 'AddMessage' accepting a first argument of type 'CloudQueue' could be found (are you missing a using directive or an assembly reference?)
2018-11-21T04:51:41.254 [Error] Executed 'Functions.HttpTriggerSPO' (Failed, Id=c2b9151a-cc57-4c97-8589-1443f4c8760a)
Script compilation failed.

After a bunch more fiddling, the Function App has to be down-graded to V1 for the sample code to work. It's probably worthwhile to update the documentation to at least mention that the sample only works with V1, if not to update the instructions to include V2 instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4090b3a1-d10b-f317-2ffd-21cf9a2ad43a
* Version Independent ID: 09febd24-8563-4fdf-5c1b-d680a106b7da
* Content: [Using Azure Functions with SharePoint webhooks](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/sharepoint-webhooks-using-azure-functions)
* Content Source: [docs/apis/webhooks/sharepoint-webhooks-using-azure-functions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/webhooks/sharepoint-webhooks-using-azure-functions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The doc is a bit outdated and could use a refresh... good op for someone to contribute a PR...

**Comment by ehalsey** [comment]
I'm interested in helping with the refresh @andrewconnell.  Wondering if you are asking to refresh https://github.com/SharePoint/sp-dev-samples/tree/master/Samples/WebHooks.List.AzureAD or just this (Azure Function) part?

**Comment by andrewconnell** [comment]
The article is the primary focus. If the article references a project elsewhere, then that project should also be updated.

Thanks for offering to help @ehalsey !

**Comment by ehalsey** [comment]
@andrewconnell The outdated sample is using MVC.  Should the updated sample use MVC again or switch .net core or even node?  Do you have any insight on what folks need the most help with?

**Comment by andrewconnell** [comment]
@ehalsey said:
> Do you have any insight on what folks need the most help with?

No... but IMHO, I'd stay as close to what's already there. IOW, I'd leave it as MVC.

**Comment by ehalsey** [comment]
That makes sense.  Going through this there are a couple of options I think I should mention as a best practice:

- renaming the function HttpTrigger1 -> spwebhookhttpfunc 
- changing to the Plan type to Free F1 app service plan

My question is in general is it best to KISS and go w/ all defaults or OK to point a few of these out?

**Comment by andrewconnell** [comment]
That's my approach... my life is all about technical education teaching, writing and recording demos. The balance you strive for is:

- provide enough information to make it easy for the consumer of the content to be successful
- use default settings as much as possible & stay on a "critical path" to being successful
- minimize screenshots/steps as much as possible because in this constantly changing "cloud" world, content gets outdated quickly... just like this doc

If you do point out change slike that, call it out as a note but not part of the steps. Make it easy for the consumer to see "ah, that's the writer giving us a tip" and for the editor to call out "ah, this isn't part of the main steps so I can leave it and focus on the stuff that needs to be updated."

Make sense?

KISS FTW

**Comment by ehalsey** [comment]
Totally makes sense.  That's why you are one of the best in the biz brother.

**Comment by andrewconnell** [comment]
![](https://media.giphy.com/media/dILZwwhulFUn6/giphy.gif)
