### ISSUE TITLE
Upgrade TypeScript package to latest version

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-docs#3007]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Upgrade Typescript package version to 3.1.6

#### Observed Behavior

I still see older version of TypeScript:

PS C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col\PApps> npm ls typescript
publish-apps@1.0.0 C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col\PApps
+-- @microsoft/sp-build-web@1.7.0
| +-- @microsoft/gulp-core-build-typescript@6.1.10
| | +-- @microsoft/api-extractor@6.0.7
| | | `-- typescript@3.0.3
| | `-- typescript@2.4.2  deduped
| `-- @microsoft/sp-build-common@1.7.0
|   `-- typescript@2.4.2  deduped
+-- @microsoft/sp-tslint-rules@1.7.0
| `-- @microsoft/rush-stack-compiler@0.1.18
|   `-- typescript@2.4.2  deduped
+-- node-sppkg-deploy@1.1.2
| `-- typescript@2.4.2  extraneous
`-- typescript@2.4.2

npm ERR! extraneous: typescript@2.4.2 C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col\PApps\node_modules\node-sppkg-deploy\node_modules\typescript

#### Steps to Reproduce

npm install -g typescript@3.1.6
npm ls typescript

Please let me know how I can get latest version of TypeScript in my project?

Thanks for your contribution! Sharing is caring.

**Comment by darkriderdesign** [comment]
I tried this also, with the same results. It looks like typescript version is hard coded in the Microsoft mode modules folder.

This is kind of a show stopper? In that almost all react based UI frameworks are using 2.8 of newer....  material-design ui is using 3.

To put things into perspective... If I try and find a version of material design ui that uses typescript 2.4 I literally have to go back to pre beta?

**Comment by cebud** [comment]
Install latest typescript locally:

- npm install typescript@3.1.6

Update **gulpfile.js** in SPFx project:

const typescriptBuild = require('@microsoft/gulp-core-build-typescript');

typescriptBuild.tscCmd.mergeConfig({
  overridePackagePath: 'node_modules/typescript'
});

**Comment by salascz** [comment]
Potential typings conflicts might be resolved within “resolutions” attribute in package.json file.

**Comment by xyz92** [comment]
@cebud Thanks! I tried your suggestion. On running gulp build after following your steps, I see additional errors as follows:

Error - [tslint] TypeError: Cannot read property 'clauses' of undefined
    at NoSwitchCaseFallThroughWalker.visitSwitchStatement (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\rules\noSwitchCaseFallThroughRule.js:67:36)
    at cb (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\rules\noSwitchCaseFallThroughRule.js:59:23)
    at visitEachNode (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\typescript\lib\typescript.js:16136:24)
    at NoSwitchCaseFallThroughWalker.walk (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\rules\noSwitchCaseFallThroughRule.js:63:19)
    at Rule.AbstractRule.applyWithWalker (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\language\rule\abstractRule.js:31:16)
    at Rule.apply (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\rules\noSwitchCaseFallThroughRule.js:33:21)
    at Linter.applyRule (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\linter.js:197:29)
    at C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\linter.js:139:85
    at Object.flatMap (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\utils.js:151:29)
[09:29:03] Error - [tslint] TypeError: Cannot read property 'kind' of undefined
    at Object.isIdentifier (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\tsutils\typeguard\node.js:306:17)
    at cb (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\rules\preferConstRule.js:159:27)
    at visitEachNode (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\typescript\lib\typescript.js:16276:24)
    at cb (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\rules\preferConstRule.js:172:27)
    at visitEachNode (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\typescript\lib\typescript.js:16215:21)
    at cb (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\tslint\lib\rules\preferConstRule.js:172:27)
    at visitEachNode (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\Users\xyz\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\gulp-core-build-typescript\node_modules\typescript\lib\typescript.js:16136:24)

**Comment by xyz92** [comment]
@cebud Thank you! I still see 2.4.2 version in microsoft modules:

publish-apps@1.0.0 C:\Users\lipalath\Desktop\spfx-upgrade\EUS-Col-ColPub-PublishApps\PublishApps
+-- @microsoft/sp-build-web@1.7.0
| +-- @microsoft/gulp-core-build-typescript@6.1.10
| | +-- @microsoft/api-extractor@6.0.7
| | | `-- typescript@3.0.3
| | `-- typescript@2.4.2
| `-- @microsoft/sp-build-common@1.7.0
|   `-- typescript@2.4.2
+-- @microsoft/sp-tslint-rules@1.7.0
| `-- @microsoft/rush-stack-compiler@0.1.18
|   `-- typescript@2.4.2
`-- node-sppkg-deploy@1.1.2
  `-- typescript@2.4.2  extraneous

Also, I see [tsc] errors - TS2564: Property 'isReviewer' has no initializer and is not definitely assigned in the constructor. Are these introduced as a part of typescript version upgrade?

**Comment by cebud** [comment]
@xyz92 

During the compilation of which file this error occurred?  It is in your custom code? _[tsc] errors - TS2564: Property 'isReviewer' has no initializer and is not definitely assigned in the constructor._

The problem is most likely due to the strictPropertyInitialization  flag firstly introduced in TypeScript 2.7 (and beyond), which could cause these kind of errors.

**Comment by xyz92** [comment]
@cebud It is in my custom code. I was able to fix that. I get a tslint error though Error - [tslint] no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead. I tried setting the rule  "no-unused-variable": false in tslint.json. That didn't work though.

**Comment by cebud** [comment]
@xyz92 Where do you have tslint.json? in config folder? or on the same level as is tsconfig.json, package.json,...

**Comment by xyz92** [comment]
@cebud Figured out the issue. I had 2 tslint.json files in my project - one on the same level of  tsconfig.json, package.json (where I made the updates), one within src folder. I had to update that as well. Thank you so much! Appreciate your help!

**Comment by darkriderdesign** [comment]
@Cebud.... this totally works, thank you.

**Comment by FlorianGrimm** [comment]
Ola

I'm using on a project "@microsoft/sp-build-web": "1.5.1".
I accidentally installed Node.JS version:v10.14.0 on my maschine. 

As I reallized that - and it worked - I also updated the typescript version to 3.2.1. 

As I hacked @microsoft\gulp-core-build-typescript via
```
cd node_modules\@microsoft\gulp-core-build-typescript
yarn add typescript tslint-microsoft-contrib
```

I was also able to run gulp serve, gulp bundle, gulp package-solution.

I don't have installed any Typescript version globally.

**Comment by xyz92** [comment]
@cebud, after updating gulp files, I ran gulp build and I still see my older version of TypeScript being listed:

[17:57:55] Starting subtask 'typescript'...
[17:57:55] [typescript] TypeScript version: 2.4.2
typeof-compare is deprecated. Starting from TypeScript 2.2 the compiler includes this check which makes this rule redundant.

**Comment by cebud** [comment]
@xyz92 What's the SPFx version in your project? The previous steps are valid only for version 1.6 and newer.

**Comment by xyz92** [comment]
SPFx version is 1.7.0, NodeJS: 8.11.4, npm: 6.4.1

**Comment by mrukas** [comment]
I also had to upgrade typescript in order to get Ant Design working.
The solution above wasn't working for me.
My workaround was the following:

- npm install typescript --save-dev
- Edit gulpfile so it looks lile this:
```
'use strict';

const typeScriptConfig = require('@microsoft/gulp-core-build-typescript/lib/TypeScriptConfiguration');

typeScriptConfig.TypeScriptConfiguration.setTypescriptCompiler(require('typescript'));

const gulp = require('gulp');
const build = require('@microsoft/sp-build-web');
build.addSuppression(`Warning - [sass] The local CSS class 'ms-Grid' is not camelCase and will not be type-safe.`);

build.initialize(gulp);
```

**Comment by xyz92** [comment]
@cebud Hi, when I try to run gulp build, it takes ~8 minutes to complete step "Finished subtask 'tsc'". Before typescript update, it usually gets completed in seconds. Could you please let me know if you have idea to resolve this?

**Comment by patmill** [comment]
What does the output of gulp serve --verbose look like?

**Comment by xyz92** [comment]
@patmill Here is the output for gulp serve --verbose:

 gulp serve --verbose
Build target: DEBUG
Found config file: copy-assets.json
Found config file: write-manifests.json
Found config file: serve.json
Found config file: deploy-azure-storage.json
Found config file: package-solution.json
[12:54:23] Using gulpfile ~\_\EUS\PA\gulpfile.js
[12:54:23] Starting gulp
[12:54:23] Starting 'serve'...
[12:54:23] Starting subtask 'configure-sp-build-rig'...
[12:54:23] [configure-sp-build-rig] Found config file: config.json
[12:54:23] Finished subtask 'configure-sp-build-rig' after 19 ms
[12:54:23] Starting subtask 'spfx-serve'...
[12:54:23] Starting server...
Starting api server on port 5432.
Registring api: /workbench
Registring api: */*
[12:54:24] Finished subtask 'spfx-serve' after 1.39 s
[12:54:25] Starting subtask 'pre-copy'...
[12:54:25] Finished subtask 'pre-copy' after 50 ms
[12:54:25] Starting subtask 'copy-static-assets'...
[12:54:25] Starting subtask 'sass'...
[12:54:25] Server started https://localhost:4321
[12:54:25] LiveReload started on port 35729
[12:54:25] Running server
[12:54:25] Opening https://localhost:5432/workbench using the default OS app
[12:54:26] Finished subtask 'sass' after 1.46 s
[12:54:26] Starting subtask 'tslint'...
[12:54:26] [tslint] tslint version: 5.11.0
[12:54:27] Starting subtask 'tsc'...
[12:54:27] [tsc] typescript version: 3.1.6
  Request: [::1] '/workbench'
  Request: '/temp/workbench.html'
[12:54:28] Finished subtask 'copy-static-assets' after 3.2 s
  Request: '/temp/manifests.js'
  Request: '/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js'
  Request: '/node_modules/@microsoft/decorators/dist/decorators.js'
  Request: '/node_modules/@microsoft/sp-component-base/dist/sp-component-base_en-us.js'
  Request: '/node_modules/@microsoft/sp-extension-base/dist/sp-extension-base_en-us.js'
  Request: '/node_modules/@microsoft/sp-application-base/dist/sp-application-base_en-us.js'
  Request: '/temp/workbench-packages/react/umd/react.development.js'
  Request: '/temp/workbench-packages/react-dom/umd/react-dom.development.js'
  Request: '/node_modules/@microsoft/office-ui-fabric-react-bundle/dist/office-ui-fabric-react-bundle.js'
  Request: '/node_modules/@microsoft/sp-webpart-base/dist/sp-webpart-base_en-us.js'
  Request: '/node_modules/@microsoft/sp-webpart-workbench/dist/sp-webpart-workbench_en-us.js'
  Request: '/node_modules/@microsoft/sp-webpart-workbench/dist/4.4_4c6ac99cf0a3a4aaf266.js'
  Request: '/node_modules/@microsoft/sp-webpart-workbench/dist/3.3_82dcff9c7c8ac15d1d73.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/assets/server-icon.png'
[12:54:59] Finished subtask 'tslint' after 32 s
[13:03:05] Finished subtask 'tsc' after 8.63 min
[13:03:05] Starting subtask 'api-extractor'...
[13:03:05] Finished subtask 'api-extractor' after 2.21 ms
[13:03:05] Starting subtask 'post-copy'...
[13:03:05] Finished subtask 'post-copy' after 2.13 ms
[13:03:05] Starting subtask 'collectLocalizedResources'...
[13:03:05] [collectLocalizedResources] 1 localized resources defined.
[13:03:05] [collectLocalizedResources] Found file "lib/webparts/publishApps/loc/en-us.js", identified as locale "en-us"
[13:03:05] [collectLocalizedResources] Found file "lib/webparts/publishApps/loc/es-es.js", identified as locale "es-es"
[13:03:05] [collectLocalizedResources] Found file "lib/webparts/publishApps/loc/hi-in.js", identified as locale "hi-in"
[13:03:05] Finished subtask 'collectLocalizedResources' after 24 ms
[13:03:05] Starting subtask 'configure-webpack'...
[13:03:08] [configure-webpack] 1 entries specified.
[13:03:08] [configure-webpack] 20 externals specified.
[13:03:08] [configure-webpack] 1 localized resources specified.
[13:03:08] Finished subtask 'configure-webpack' after 3.14 s
[13:03:08] Starting subtask 'webpack'...
[13:03:17] Finished subtask 'webpack' after 8.88 s
[13:03:17] Starting subtask 'configure-webpack-external-bundling'...
[13:03:17] [configure-webpack-external-bundling] No localized resources specified, nothing to do.
[13:03:17] Finished subtask 'configure-webpack-external-bundling' after 2.84 ms
[13:03:17] Starting subtask 'copy-assets'...
[13:03:18] Finished subtask 'copy-assets' after 352 ms
[13:03:18] Starting subtask 'write-manifests'...

**Comment by patmill** [comment]
OK, that's seriously weird.  If you do the usual "what is my machine doing" things (look at perf monitor, network usage, disk usage, cpu usage, etc.) can you tell what subsystem is getting hammered?  I'd expect my machine to sound like a jet engine if it was spending 8 minutes on CPU.

**Comment by xyz92** [comment]
It's the CPU I think: 

![image](https://user-images.githubusercontent.com/6519992/55753853-322fbd00-5a00-11e9-83b3-1f3478095111.png)

**Comment by xyz92** [comment]
I upgraded typescript to latest version 3.4.2 and now is taking only seconds :) Thank you!

**Comment by agzertuche** [comment]
I was reading this [post](https://www.eliostruyf.com/define-the-typescript-version-you-want-to-use-in-sharepoint-framework/) but it is a pretty different approach as the solution mentioned on this thread.

@xyz92 Could you be so kind and explain how did you be able to do it?
