### ISSUE TITLE
This does not work with latest Node LTS version

### ISSUE THREAD

**Issue by jasonjoh** [SharePoint/sp-dev-docs#3100]
While your link goes to the v8.x distro, the text basically says to install "NodeJS LTS version". The LTS version as of this post is 10.14.2.

With any version over 8, gulp commands generate the error:

```
Error: Your dev environment is running NodeJS version v10.14.2 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches &gt;=8.9.4 &lt;9.0.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-nodejs)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
Both 8 and 10 are LTS versions (https://github.com/nodejs/Release#release-schedule) getting active development at the moment.  I've clarified the wording to note that only 8 is supported at this point.

**Comment by jlsfernandez** [comment]
Any news about this issue? any progress? Thanks a lot

**Comment by coolvijaymca** [comment]
Any idea how to make it work on NodeJS v10. I am also getting the same error.

C:\SharePoint\samples\ListViewControl\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:24
            throw new Error(`Your dev environment is running NodeJS version ${process.version} which does`
            ^

Error: Your dev environment is running NodeJS version v10.12.0 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0 || >=10.13.0 <11.0.0
    at SPWebBuildRig.initialize (C:\SharePoint\samples\ListViewControl\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:24:19)
    at SPWebBuildRig.initialize (C:\SharePoint\samples\ListViewControl\node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js:14:15)
    at Object.exports.initialize (C:\SharePoint\samples\ListViewControl\node_modules\@microsoft\sp-build-web\lib\index.js:22:17)
    at Object.<anonymous> (C:\SharePoint\samples\ListViewControl\gulpfile.js:7:7)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
