### ISSUE TITLE
SharePoint online SPFx Modern Page layout SingleWebPartAppPage Error

### ISSUE THREAD

**Issue by beyasu** [SharePoint/sp-dev-docs#3566]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When link in single part app page is clicked to redirect to another single part app page, content in redirected page should render properly. 

#### Observed Behavior
Navigation among single part app pages breaks with error shown below from Chrome browser console log. Basically I created two page added the Out of the Links web part to both with some links on them and then changes the pages layout to SingleWebPartAppPage.
I can see even the out of the box web part breaks when we navigate. Navigation bar shows proper page address after link clicked but page is rendered empty. If I refresh the page the page works fine. 

Here is error log from chrome console. 

DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Hn (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:429988)
    at br (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:446784)
    at gr (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:444110)
    at yr (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:443455)
    at dr (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:442484)
    at ir (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:441543)
    at Cr (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:450139)
    at Er (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:450206)
    at Or.window.spModuleLoader.Or.render (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:920:24100)
    at Ir (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:451836)
Ln @ sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912
sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Hn (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:429988)
    at br (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:446784)
    at gr (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:444110)
    at yr (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:443455)
    at dr (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:442484)
    at ir (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:441543)
    at Cr (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:450139)
    at Er (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:450206)
    at Or.window.spModuleLoader.Or.render (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:920:24100)
    at Ir (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.004/sp-pages-assembly_en-us_6c1a087a0a66ab5efb0620a4886d0060.js:912:451836)

**Comment by ng-marcus** [comment]
We see this too.   I reported it under this bug:

https://github.com/SharePoint/sp-dev-docs/issues/3168

It should have been fixed in SPFX1.8.    My first build with SPFX 1.8 still has the same issue, but I'm double checking my build at the moment.

**Comment by beyasu** [comment]
> We see this too. I reported it under this bug:
> 
> #3168
> 
> It should have been fixed in SPFX1.8. My first build with SPFX 1.8 still has the same issue, but I'm double checking my build at the moment.

Thank you for your kind response. I will also update to SPFX 1.8 and build our solution. Hopefully it will address the issue unless I will use the bug you created for future communication related to this issue.
