### ISSUE TITLE
Unable to Open sharepoint video inside mobile app via deeplink 

### ISSUE THREAD

**Issue by edcastrohit** [SharePoint/sp-dev-docs#3702]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Can anyone help me to deep link in share point mobile app from our app? 

basically, i having a share point video link like below 
https://ankitagency.sharepoint.com/:v:/g/EfBqocbTKF5LoE6Qd-2ZLagBOvOHIwqXT9Rgmee6A2lhsQ?e=1udYI6

and to open this link in the SharePoint app we startSharepoint activity with below URI.

**ms-sharepoint:ofe|u|https://ankitagency.sharepoint.com/:v:/g/EfBqocbTKF5LoE6Qd-2ZLagBOvOHIwqXT9Rgmee6A2lhsQ?e=1udYI6**

the app is open successfully but crashing after open with below error.
 so can anyone help or suggest a way like how I can deep link or open a document from our native Android mobile app. 
Might be I am doing something wrong in above URI scheme. but this all working in case of Word, Excel and PPT link with a native other individual share point app.

`Process: com.microsoft.sharepoint, PID: 30834
   java.lang.RuntimeException: Unable to resume activity {com.microsoft.sharepoint/com.microsoft.sharepoint.MainActivity}: java.lang.UnsupportedOperationException: This isn’t a hierarchical URI.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3830)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3870)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3090)
       at android.app.ActivityThread.-wrap11(Unknown Source:0)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1739)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7036)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
    Caused by: java.lang.UnsupportedOperationException: This isn’t a hierarchical URI.
       at android.net.Uri.getQueryParameter(Uri.java:1679)
       at com.microsoft.odsp.urlrequest.ODSPUrlRequest.a(SourceFile:25)
       at com.microsoft.sharepoint.MainActivity.a(SourceFile:544)
       at com.microsoft.sharepoint.MainActivity.onMAMPostResume(SourceFile:239)
       at com.microsoft.intune.mam.client.app.offline.OfflineActivityBehavior.onPostResume(SourceFile:270)
       at com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivityBase.onPostResume(SourceFile:177)
       at android.app.Activity.performResume(Activity.java:7468)`

**Comment by vanth0me** [comment]
This still crashes the app. Is there really no way too deeplink?
