### ISSUE TITLE
Error - Cannot find module 'orchestrator'

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#385]
#### Category
- [x] Bug

I created a new project with the RC0 build. When I start ```gulp serve``` I get the following error:

<img width="577" alt="screen shot 2017-01-25 at 00 42 23" src="https://cloud.githubusercontent.com/assets/5503835/22271927/7ff2673c-e297-11e6-84f9-3b9df1f067b3.png">

Project was fresh and haven't customised anything yet. NodeJS is running on osX Sierra. The verbose error message contain the following information:

```
[00:46:40] Error - Unknown 
 Cannot find module 'orchestrator' 
 Error: Cannot find module 'orchestrator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/Code/demos/spfx-handlebars/node_modules/@microsoft/sp-build-web/node_modules/@microsoft/gulp-core-build/lib/GulpProxy.js:7:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by michel-weber** [comment]
What template  did you use (yo @microsoft/sharepoint)?

**Comment by StfBauer** [comment]
Plain HTML Template haven't tried any other yet.

**Comment by michel-weber** [comment]
I see you are using npm version 2.15.5.
SharePoint Framework requires version 3.x.

See this document. They also recommend using hombrew on a Mac.
https://dev.office.com/sharepoint/docs/spfx/set-up-your-development-environment

**Comment by manishgarg1** [comment]
@StfBauer, also can you show how you are including the 'orchestrator' module in your code? And also make sure it is present in the node_modules folder. If not, try running 'npm i orchestrator --save' and then recompile. If this works, that implies that you need to add 'orchestrator' as a dependency in the package.json file.

**Comment by StfBauer** [comment]
Yep that was it @michel-weber. Played around with lastest Node versions via [n](https://www.npmjs.com/package/n) also reinstalled node.

Somehow missed the npm upgrade.
