### ISSUE TITLE
Could not connect to the conversion service.

### ISSUE THREAD

**Issue by sean-ator** [SharePoint/sp-dev-docs#3864]
I have tried to use this code in every context possible and I always get the following:
Begin conversion
Error: Microsoft.Office.Server.PowerPoint.Conversion.ConversionException: Could not connect to the conversion service. --- ConversionError: ServiceUnavailable ---&gt; System.ServiceModel.FaultException: The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the &lt;serviceDebug&gt; configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.

Server stack trace:
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeEndService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at Microsoft.Office.Web.Common.AsyncResult`1.WaitForCompletion()
   at Microsoft.Office.Server.PowerPoint.Conversion.RequestUtility.OnResponseReceived(IAsyncResult result)
   --- End of inner exception stack trace ---
   at Microsoft.Office.Web.Common.AsyncResult`1.WaitForCompletion()
   at Microsoft.Office.Server.PowerPoint.Conversion.Request.EndConvert(IAsyncResult result)
   at Convert.Program.Main(String[] args) in C:\Users\svc_spacct\source\repos\Convert\Convert\Program.cs:line 55
Complete

The service is running and the service application exists. But I can find no way to get the connection to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53091bf8-72cc-ab43-7488-3249393b1c61
* Version Independent ID: fe422e0a-cdbe-fa01-03e2-2c410ebfda37
* Content: [PowerPoint Automation Services in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/powerpoint-automation-services-in-sharepoint#feedback)
* Content Source: [docs/general-development/powerpoint-automation-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/powerpoint-automation-services-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by sean-ator** [comment]
I'm sorry the version above is SharePoint 2019 running Windows Server Standard 2019.

**Comment by ankitsaxena86** [comment]
Hi - is there any update on this I am facing the same issue on SharePoint 2019

**Comment by BuGzY404** [comment]
Hi, please try this workaround :-

1) Open C:\Program Files\CommonFiles\MicrosoftShared\WebServerExtensions\16\WebServices\PowerPointConversion\web.config

2) Add the following on line 3 (after <configuration>and before <system.serviceModel>) :-

<appSettings><add key="ConfigAdapterAssemblyQualifiedTypeName" value="Microsoft.Office.ConversionServices.Local.Environment.ConfigAdapter,Microsoft.Office.Word.Server,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c"/>
</appSettings>
