### ISSUE TITLE
Highlighted content webpart fails when searching for ContentClass equals STS_List_DocumentLibrary

### ISSUE THREAD

**Issue by hamedy** [SharePoint/sp-dev-docs#4052]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
To see a list of document libraries on the site. 

#### Observed Behavior

TECHNICAL DETAILS

ERROR:

Cannot read property 'indexOf' of null

CALL STACK:

TypeError: Cannot read property 'indexOf' of null

at e._parseURI (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:995:77963)

at new e (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:995:73483)

at e.getThumbnailUrl (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:1070:38581)

at Function.e.getContentPreviewInfo (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-contentrollup-webpart-bundle_en-us_25bc4a90a223ba290d5ee90ceaffbf61.js:191:88332)

at t.transposeRow (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-contentrollup-webpart-bundle_en-us_25bc4a90a223ba290d5ee90ceaffbf61.js:191:103456)

at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:2678:62993

at e.transposeRow (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:2678:77770)

at e.transpose (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:2678:78031)

at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:2678:62949

#### Steps to Reproduce

add the webpart to a modern page, filter on ContentClass equals to  STS_List_DocumentLibrary

Thanks, 
Hamed

**Comment by qianghuang94** [comment]
Hey @hamedy , thanks for reporting, we are addressing this bug.
