### ISSUE TITLE
Cannot create a node-based HTTPS server on localhost:4321

### ISSUE THREAD

**Issue by apoorvpatne10** [SharePoint/sp-dev-docs#4094]
#### Category
- [x] Question
- [ ] Bug
- [ ] Typo
- [ ] Additional article idea

#### Expected or Desired Behavior

* OS : Ubuntu 18.04. 
* node version - 8.10.0
* npm version - 6.9.0

Prior to this step I've followed every step from the [official docs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part). I can't get the sharepoint web part to run on localhost. When I execute `gulp serve` this is supposed to happen:

![image](https://user-images.githubusercontent.com/31184004/58928803-a7560f00-8771-11e9-87d6-c17a0930cddb.png)

#### Observed Behavior

But instead I get this traceback:

```
apoorv@apoorv:~/Desktop/GAM/helloworld-webpart$ sudo gulp serve
Build target: DEBUG
[09:05:13] Using gulpfile ~/Desktop/GAM/helloworld-webpart/gulpfile.js
[09:05:13] Starting gulp
[09:05:13] Starting 'serve'...
[09:05:13] Starting subtask 'configure-sp-build-rig'...
[09:05:13] Finished subtask 'configure-sp-build-rig' after 3.87 ms
[09:05:13] Starting subtask 'spfx-serve'...
[09:05:13] Starting server...
Starting api server on port 5432.
Registring api: /workbench
Registring api: */*
[09:05:13] Finished subtask 'spfx-serve' after 119 ms
[09:05:13] Starting subtask 'pre-copy'...
[09:05:13] Finished subtask 'pre-copy' after 14 ms
[09:05:13] Starting subtask 'copy-static-assets'...
[09:05:13] Starting subtask 'sass'...
{ Error: listen EADDRINUSE :::5432
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at SpfxServeTask.executeTask (/home/apoorv/Desktop/GAM/helloworld-webpart/node_modules/@microsoft/gulp-core-build-serve/lib/ServeTask.js:70:65)
    at SpfxServeTask.executeTask (/home/apoorv/Desktop/GAM/helloworld-webpart/node_modules/@microsoft/sp-build-core-tasks/lib/spfxServe/SpfxServeTask.js:38:22)
    at Promise (/home/apoorv/Desktop/GAM/helloworld-webpart/node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:171:31)
    at new Promise (<anonymous>)
    at SpfxServeTask.execute (/home/apoorv/Desktop/GAM/helloworld-webpart/node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:163:16)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 5432 }
[09:05:13] Error - Unknown 
 listen EADDRINUSE :::5432
[09:05:13] Server started https://localhost:4321
[09:05:13] LiveReload started on port 35729
[09:05:13] Running server
[09:05:13] Opening https://localhost:5432/workbench using the default OS app
[09:05:13] Finished subtask 'copy-static-assets' after 43 ms
[09:05:13] Finished subtask 'sass' after 180 ms
[09:05:13] Starting subtask 'tslint'...
[09:05:14] [tslint] tslint version: 5.12.1
[09:05:14] Starting subtask 'tsc'...
[09:05:14] [tsc] typescript version: 2.9.2
(node:24438) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/apoorv/Desktop/GAM/helloworld-webpart/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:24438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24438) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[09:05:14] ==================[ Finished ]==================
Error - Unknown 
 listen EADDRINUSE :::5432
[09:05:15] Project helloworld-webpart version:0.0.1
[09:05:15] Build tools version:3.9.26
[09:05:15] Node version:v8.10.0
[09:05:15] Total duration:3.06 s
[09:05:15] Task errors:2
[09:05:15] Error - 'undefined' errored after  
 "orchestration aborted"
[09:05:16] Finished subtask 'tsc' after 2.27 s
[09:05:17] Finished subtask 'tslint' after 3.16 s
[09:05:17] Starting subtask 'post-copy'...
[09:05:17] Finished subtask 'post-copy' after 103 μs
[09:05:17] Starting subtask 'collectLocalizedResources'...
[09:05:17] Finished subtask 'collectLocalizedResources' after 2.45 ms
[09:05:17] Starting subtask 'configure-webpack'...
[09:05:17] Finished subtask 'configure-webpack' after 230 ms
[09:05:17] Starting subtask 'webpack'...
[09:05:18] Finished subtask 'webpack' after 1.21 s
[09:05:18] Starting subtask 'configure-webpack-external-bundling'...
[09:05:18] Finished subtask 'configure-webpack-external-bundling' after 442 μs
[09:05:18] Starting subtask 'copy-assets'...
[09:05:18] Finished subtask 'copy-assets' after 15 ms
[09:05:18] Starting subtask 'write-manifests'...
[09:05:18] Finished subtask 'write-manifests' after 300 ms
[09:05:18] Starting subtask 'reload'...
[09:05:18] Finished subtask 'reload' after 722 μs
```

Where am I going wrong?

**Comment by patmill** [comment]
Sounds like something else is already using that port.  Any chance you have another instance of gulp serve running?

**Comment by apoorvpatne10** [comment]
I restarted my terminal and executed `gulp serve` again. This is what I got:

```
apoorv@apoorv:~/Desktop/GAM/helloworld-webpart$ gulp serve
Build target: DEBUG
[09:38:04] Using gulpfile ~/Desktop/GAM/helloworld-webpart/gulpfile.js
[09:38:04] Starting gulp
[09:38:04] Starting 'serve'...
[09:38:04] Starting subtask 'configure-sp-build-rig'...
[09:38:04] Finished subtask 'configure-sp-build-rig' after 4.6 ms
[09:38:04] Starting subtask 'spfx-serve'...
[09:38:04] Starting server...
Starting api server on port 5432.
Registring api: /workbench
Registring api: */*
[09:38:04] Finished subtask 'spfx-serve' after 148 ms
[09:38:04] 'serve' errored after 164 ms
[09:38:04] 
{ Error: listen EADDRINUSE :::5432
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at SpfxServeTask.executeTask (/home/apoorv/Desktop/GAM/helloworld-webpart/node_modules/@microsoft/gulp-core-build-serve/lib/ServeTask.js:70:65)
    at SpfxServeTask.executeTask (/home/apoorv/Desktop/GAM/helloworld-webpart/node_modules/@microsoft/sp-build-core-tasks/lib/spfxServe/SpfxServeTask.js:38:22)
    at Promise (/home/apoorv/Desktop/GAM/helloworld-webpart/node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:171:31)
    at new Promise (<anonymous>)
    at SpfxServeTask.execute (/home/apoorv/Desktop/GAM/helloworld-webpart/node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:163:16)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 5432 }
[09:38:04] Error - Unknown 
 listen EADDRINUSE :::5432
[09:38:04] Server started https://localhost:4321
[09:38:04] LiveReload started on port 35729
[09:38:04] Running server
[09:38:04] Opening https://localhost:5432/workbench using the default OS app
[09:38:04] ==================[ Finished ]==================
Error - Unknown 
 listen EADDRINUSE :::5432
[09:38:05] Project helloworld-webpart version:0.0.1
[09:38:05] Build tools version:3.9.26
[09:38:05] Node version:v8.10.0
[09:38:05] Total duration:2.75 s
[09:38:05] Task errors:2
[09:38:05] Error - 'undefined' errored after  
 "orchestration aborted"
```

On chrome, this is what I'm getting:

![Screenshot from 2019-06-05 09-38-14](https://user-images.githubusercontent.com/31184004/58929734-fe5de300-8775-11e9-8842-de523c052553.png)

**Comment by apoorvpatne10** [comment]
I don't know whether this is a perfect solution but, changing the port number in config/serve.json did the work for me since 5432 was already in use for some reason. 

Then:
```
...
"https": true,
  "initialPage": "https://localhost:5432/workbench",
  "api": {
    "port": 5432,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }
...
```

Now :

```
...
"https": true,
  "initialPage": "https://localhost:5432/workbench",
  "api": {
    "port": 8000,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }
...
```

**Comment by andrewconnell** [comment]
As @patmill commented, this line in the results you posted is stating the problem:

```
Error: listen EADDRINUSE :::5432
```

There's something on your machine that has port 5432 option so the web server can't open it. Restarting the terminal won't have an effect... you either need to find the process that's opening that port & shut it off OR as you did in your reply, change the default port the local web server is spinning up via `gulp serve` by modifying the **config/serve.json** file.

I _think_ 5432 is also used by postgresql... maybe that's the culprit?

**Comment by apoorvpatne10** [comment]
Thanks for clarifying, but `lsof -i tcp:5432` didn't show any port being used. How can I know where is this port being used?

**Comment by andrewconnell** [comment]
Not familiar with Linux... sorry. But it's clearly the problem that the port is already reserved by another process.
