### ISSUE TITLE
react-application-tenant-global-navbar

### ISSUE THREAD

**Issue by jurivero** [SharePoint/sp-dev-docs#4224]
Good morning,

I am trying to test the following extension "react-application-tenant-global-navbar"
node -v 10.15.3
npm v 6.9.0
gulp v CLI 2.2.0 Local  3.9.2
if I run gulp test or gulp serve --nobrowser I get the same errors, I need some help to test this
please see the errors below:

C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  deasync.cc
  win_delay_load_hook.cc
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (
compiling source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
  c:\users\xxx\.node-gyp\10.15.3\include\node\v8.h(3243): note: see declaration of 'v8::Object' (compiling source file ..\src\deasync.cc)
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\node_modules\nan\nan.h(834): warning C4996: 'node::MakeCallback': was declared deprecated (compiling
 source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
  c:\users\xxx\.node-gyp\10.15.3\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\deasync.cc)
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\node_modules\nan\nan.h(849): warning C4996: 'node::MakeCallback': was declared deprecated (compiling
 source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
  c:\users\xxx\.node-gyp\10.15.3\include\node\node.h(169): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\deasync.cc)
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\node_modules\nan\nan.h(864): warning C4996: 'node::MakeCallback': was declared deprecated (compiling
 source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
  c:\users\xxx\.node-gyp\10.15.3\include\node\node.h(162): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\deasync.cc)
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\node_modules\nan\nan.h(1473): warning C4996: 'node::MakeCallback': was declared deprecated (compilin
g source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
  c:\users\xxx\.node-gyp\10.15.3\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\deasync.cc)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):les\fsevents):                                                           events@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.10 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by andrewconnell** [comment]
This is one of the community samples from the repo https://github.com/SharePoint/sp-dev-fx-extensions... it's best to post your issue there instead of this repo. 

BTW, that specific sample is VERY old... SPFx v1.2.0.
