### ISSUE TITLE
What API permissions are required for executing this SharePoint API?

### ISSUE THREAD

**Issue by cperson** [SharePoint/sp-dev-docs#4500]
Can you provide details around which RBAC permissions are needed to use an Azure Application to trigger a bulk update via Powershell? 

I'm attempting to trigger 'QueueImportProfileProperties' using a SPO 'Get-PnPContext' object after authenticating to SPO using 'Connect-PnPOnline' with the 'AppId' and 'AppSecret' of an Azure Application. I get 'Access denied. You do not have permission to perform this action or access this resource.' 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0dffd-d314-6e01-be9a-f72d852227e3
* Version Independent ID: e48220e4-412d-aee0-ce37-86400efb6cc3
* Content: [Bulk update custom user profile properties for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online#what-permissions-are-required-for-executing-this-api)
* Content Source: [docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by cperson** [comment]
The following article helped me to understand that I need to be using 'ClientId' and 'CertificatePath' instead to pull this off: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread

I still, however, get a 401 unauthorized in the Powershell console when attempting to queue the import job. See the stack trace below: 

ERROR: Exception calling "ExecuteQuery" with "0" argument(s): "The remote server returned an error: (401) Unauthorized." , System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at CallSite.Target(Closure , CallSite , Object )

**Comment by cperson** [comment]
@andrewconnell any insight on this? 

I'm currently attempting to use an Azure Application to execute the Add-PnPFile cmdlet and I get the error: 
`Add-PnPFile : Access denied. You do not have permission to perform this action or access this resource.`
