### ISSUE TITLE
I have ERROR

### ISSUE THREAD

**Issue by abotchorishvili** [SharePoint/sp-dev-docs#4558]
ERROR:
Cannot read property 'bind' of undefined

CALL STACK:
TypeError: Cannot read property 'bind' of undefined
    at JQueryWebPart../sp-webpart-base.js.__WEBPACK_AMD_DEFINE_RESULT__../lib/core/BaseClientSideWebPart.js.BaseClientSideWebPart._internalInitialize (https://localhost:4321/node_modules/@microsoft/sp-webpart-base/dist/sp-webpart-base_en-us.js:1666:35)
    at ClientSideWebPartManager../sp-webpart-base.js.__WEBPACK_AMD_DEFINE_RESULT__../lib/core/ClientSideWebPartManager.js.ClientSideWebPartManager._initializeWebPart (https://localhost:4321/node_modules/@microsoft/sp-webpart-base/dist/sp-webpart-base_en-us.js:3684:17)
    at https://localhost:4321/node_modules/@microsoft/sp-webpart-base/dist/sp-webpart-base_en-us.js:2943:31
I have this error, when i am trying to add jquery accordion to web part. Can anyone help me ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5a35c2-9914-fc67-1550-15d4f63c918c
* Version Independent ID: 8418c398-1a93-622d-4df8-84c866fef67f
* Content: [Add jQueryUI Accordion to your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part#feedback)
* Content Source: [docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thank you for the issue. Can you provide some more information us?

1. What version of SPFx/Node/NPM are you using?
2. When does the error happen? 
3. Does the error happen  when you do gulp serve, or does it happen when you try to add the web part to a page?

I have just ran through the tutorial and I am not receiving this error.

![image](https://user-images.githubusercontent.com/7944457/63943764-8aa63c00-ca2d-11e9-9621-2ca3d5b01d3c.png)
