### ISSUE TITLE
 Command failed: wmic os get Caption

### ISSUE THREAD

**Issue by AmerQwaider** [SharePoint/sp-dev-docs#4618]
I have an issue when run this command for spfx   yo @microsoft/sharepoint

i try to use spfx to create  web part and upload it to sharepoint online (modern site)
 
I use Win 8.1

### #spfx
#npm
#nodejs
#SPFX

λ yo @microsoft/sharepoint
C:\Users\Mohammad\AppData\Roaming\npm\node_modules\yo\node_modules\windows-release\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.

    at makeError (C:\Users\Mohammad\AppData\Roaming\npm\node_modules\yo\node_modules\windows-release\node_modules\execa\index.js:174:9)
    at Function.module.exports.sync (C:\Users\Mohammad\AppData\Roaming\npm\node_modules\yo\node_modules\windows-release\node_modules\execa\index.js:338:15)
    at windowsRelease (C:\Users\Mohammad\AppData\Roaming\npm\node_modules\yo\node_modules\windows-release\index.js:34:24)
    at osName (C:\Users\Mohammad\AppData\Roaming\npm\node_modules\yo\node_modules\os-name\index.js:39:18)
    at new Insight (C:\Users\Mohammad\AppData\Roaming\npm\node_modules\yo\node_modules\insight\lib\index.js:37:13)
    at Object.<anonymous> (C:\Users\Mohammad\AppData\Roaming\npm\node_modules\yo\lib\cli.js:54:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

![image](https://user-images.githubusercontent.com/55237841/64788875-0f3fa100-d57c-11e9-9fdf-423d704ab2ea.png)

![image](https://user-images.githubusercontent.com/55237841/64788985-3b5b2200-d57c-11e9-81f4-6e932dd003b7.png)

**Comment by andrewconnell** [comment]
What version of SPFx?

**Comment by AmerQwaider** [comment]
@microsoft/generator-sharepoint@1.4.1 

> What version of SPFx?

**Comment by andrewconnell** [comment]
That's a very old version of the generator. Please update to the latest version (v1.9.1) and try again.

**Comment by AmerQwaider** [comment]
ok can you share the right way to create spfx from scratch 
from installation to first example 

!!!

**Comment by andrewconnell** [comment]
See the docs: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part
