### ISSUE TITLE
Apply-PnPProvisioningTemplate - Random (500) Internal Server Error while running the script

### ISSUE THREAD

**Issue by limcysam** [SharePoint/sp-dev-docs#4952]
**Category**
[X] Bug

**Environment**
[X] SharePoint 2019

**Expected or Desired Behavior**
Template is applied without errors (or at least with detailed errors)

**Observed Behavior**
We are getting the 'The remote server returned an error: (500) Internal Server Error' intermittently while running the script  Apply-PnPProvisioningTemplate. The script works at times and other times it doesn't. See the trace log below:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PowerShell_ISE.exe Error: 0 : 2019-11-27 08:54:39.5022	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: System.Net.WebException: The remote server 
returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent).
	0ms	
PowerShell_ISE.exe Error: 0 : 2019-11-27 08:54:39.5282	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: System.Net.WebException: The remote server 
returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent).
	0ms	
Apply-PnPProvisioningTemplate : The remote server returned an error: (500) Internal Server Error.
At line:9 char:1
Apply-PnPProvisioningTemplate -Path ' ...
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**Steps to Reproduce**
Run the following script:
Apply-PnPProvisioningTemplate -Path "C:\temp\template.xml" -Verbose

**Comment by VesaJuvonen** [comment]
Duplicate for #4924, so closing this one. Issue is at the underlying oob API surface and it's being worked on.
