### ISSUE TITLE
JsonSchema.js:178 Error on gulp trust-dev-cert

### ISSUE THREAD

**Issue by theromych** [SharePoint/sp-dev-docs#5042]
node -v v11.0.0 ,   npm -v 6.4.1 ,   gulp -v  CLI version: 2.2.0   Local version: 3.9.1 
Getting following error:
C:\Temp\SharePoint\APPs\MyApp1\config\package-solution.json

Error: #/solution
       Additional properties not allowed: isDomainIsolated
    at validateObjectWithCallback (C:\Temp\SharePoint\APPs\MyApp1\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178:19)
    at JsonSchema.validateObjectWithCallback (C:\Temp\SharePoint\APPs\MyApp1\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:193:13)
    at JsonSchema.validateObject (C:\Temp\SharePoint\APPs\MyApp1\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:175:14)
    at PackageSolutionTask._readConfigFile (C:\Temp\SharePoint\APPs\MyApp1\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:308:28)
    at PackageSolutionTask.onRegister (C:\Temp\SharePoint\APPs\MyApp1\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:87:32)
    at Object.initialize (C:\Temp\SharePoint\APPs\MyApp1\node_modules\@microsoft\sp-build-common\node_modules\@microsoft\gulp-core-build\lib\index.js:299:24)
    at SPWebBuildRig.initialize (C:\Temp\SharePoint\APPs\MyApp1\node_modules\@microsoft\sp-build-common\lib\BuildRig.js:61:19)
    at SPWebBuildRig.initialize (C:\Temp\SharePoint\APPs\MyApp1\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:22:15)
    at SPWebBuildRig.initialize (C:\Temp\SharePoint\APPs\MyApp1\node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js:15:15)
    at Object.exports.initialize (C:\Temp\SharePoint\APPs\MyApp1\node_modules\@microsoft\sp-build-web\lib\index.js:23:17)
    at Object.&lt;anonymous&gt; (C:\Temp\SharePoint\APPs\MyApp1\gulpfile.js:7:7)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#feedback)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by PrasadKasireddy** [comment]
you are using Node.js  v11.0.0 which is not supported with SharePoint Framework.

you can uninstall node.js v11.00 and install mode.js v10.x

Refer the below URl, it will guide how to setup 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

Note: 
The current supported LTS version of NodeJS for the SharePoint Framework is both Node.js v8.x and Node.js v10.x (recommended). Node.js v12.x is not currently supported. Notice that 9.x or 11.x versions are currently also not supported with SharePoint Framework development.

**Comment by Jerry0527** [comment]
Node. js v11 is not supported to build SPFX solution, currrently please use Node.js v10.x instead, this is the recommended version, if you are working with SharePoint Online, this is the result in my local which is using Node.js v10.17.0:

![Snipaste_2019-12-23_17-48-29](https://user-images.githubusercontent.com/28797671/71350596-87225c00-25ac-11ea-83b1-86889d94d62f.png)

**Comment by alessandraamosso** [comment]
Following the instructions and using gulp 3.9.1, I've gotten this message: "This tool requires a version of NodeJS that matches >=8.9.4 and <9.0.0 || >=10.13.0 and <11.0.0 ".
I have installed NodeJS 10.13.0 and everything worked perfectly :)
