### ISSUE TITLE
Excluding Angular JS and Making Externals

### ISSUE THREAD

**Issue by webtechy** [SharePoint/sp-dev-docs#516]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I would like to be able to exclude Angular 2 JS files from being bundled. This should reduce the webpack time.

#### Observed Behavior
I get 404 errors and:

```
[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.GapFormWebPart.7955d5ed-ccc8-454a-a04b-e618bffe5a2f,Error: ***Failed to load component "425fd8f0-46ec-4704-8280-e2f12cefbb35" (GapFormWebPart). Original error: ***Failed to load path dependency "@angular/core" from component "425fd8f0-46ec-4704-8280-e2f12cefbb35" (GapFormWebPart). script resources due to: {1}. CALLSTACK:: Error at SPWebPartError.SPError [as constructor] (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader_en-us.js:13577:26) at new SPWebPartError (https://localhost:4321/node_modules/@microsoft/sp-webpart-base/dist/sp-webpart-base_en-us.js:988:30) at Function.SPWebPartError.create (https://localhost:4321/node_modules/@microsoft/sp-webpart-base/dist/sp-webpart-base_en-us.js:1012:18) at https://localhost:4321/node_modules/@microsoft/sp-webpart-base/dist/sp-webpart-base_en-us.js:1884:65
```

#### Steps to Reproduce
Set config/config.json as follows:

```
  "externals": {
    "@microsoft/sp-client-base": "node_modules/@microsoft/sp-client-base/dist/sp-client-base.js",
    "@microsoft/sp-client-preview": "node_modules/@microsoft/sp-client-preview/dist/sp-client-preview.js",
    "@microsoft/sp-lodash-subset": "node_modules/@microsoft/sp-lodash-subset/dist/sp-lodash-subset.js",
    "office-ui-fabric-react": "node_modules/office-ui-fabric-react/dist/office-ui-fabric-react.js",
    "react": "node_modules/react/dist/react.min.js",
    "react-dom": "node_modules/react-dom/dist/react-dom.min.js",
    "react-dom/server": "node_modules/react-dom/dist/react-dom-server.min.js",
    "jquery":"node_modules/jquery/dist/jquery.min.js",
    "@angular/core": "node_modules/@angular/core/bundles/core.umd.min.js",
    "@angular/common": "node_modules/@angular/common/bundles/common.umd.min.js",
    "@angular/compiler": "node_modules/@angular/compiler/bundles/compiler.umd.min.js",
    "@angular/platform-browser": "node_modules/@angular/platform-browser/bundles/platform-browser.umd.min.js",
    "@angular/platform-browser-dynamic": "node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.min.js",
    "@angular/http": "node_modules/@angular/http/bundles/http.umd.min.js",
    "@angular/router": "node_modules/@angular/router/bundles/router.umd.min.js",
    "@angular/forms": "node_modules/@angular/forms/bundles/forms.umd.min.js",
  }
```

Any help much appreciated.

**Comment by iclanton** [comment]
Can you share a sample repro project?

**Comment by iclanton** [comment]
Are you still having this problem? Otherwise I'll close this issue. You're free to reopen it if it comes back up.
