### ISSUE TITLE
tslint error no-switch-case-fall-through

### ISSUE THREAD

**Issue by a1exymoroz** [SharePoint/sp-dev-docs#5249]
## Category

- [x] Bug

## Describe the bug
```
[17:07:47] Error - [tslint] The 'no-switch-case-fall-through' rule threw an error in 'D:/job/sharePoint/locations/src/webparts/locationsManagement/components/breadcrumb/Breadcrumb.tsx':
TypeError: Cannot read property 'clauses' of undefined
    at NoSwitchCaseFallThroughWalker.visitSwitchStatement (D:\job\sharePoint\locations\node_modules\@microsoft\rush-stack-compiler-3.3\node_modules\tslint\lib\rules\noSwitchCaseFallThroughRule.js:67:36)
    at cb (D:\job\sharePoint\locations\node_modules\@microsoft\rush-stack-compiler-3.3\node_modules\tslint\lib\rules\noSwitchCaseFallThroughRule.js:59:23)
    at visitNodes (D:\job\sharePoint\locations\node_modules\@microsoft\rush-stack-compiler-3.3\node_modules\typescript\lib\typescript.js:16224:30)
    at Object.forEachChild (D:\job\sharePoint\locations\node_modules\@microsoft\rush-stack-compiler-3.3\node_modules\typescript\lib\typescript.js:16450:24)
    at cb (D:\job\sharePoint\locations\node_modules\@microsoft\rush-stack-compiler-3.3\node_modules\tslint\lib\rules\noSwitchCaseFallThroughRule.js:61:23)
    at visitNode (D:\job\sharePoint\locations\node_modules\@microsoft\rush-stack-compiler-3.3\node_modules\typescript\lib\typescript.js:16215:24)
    at Object.forEachChild (D:\job\sharePoint\locations\node_modules\@microsoft\rush-stack-compiler-3.3\node_modules\typescript\lib\typescript.js:16345:21)
    at cb (D:\job\sharePoint\locations\node_modules\@microsoft\rush-stack-compiler-3.3\node_modules\tslint\lib\rules\noSwitchCaseFallThroughRule.js:61:23)
    at visitNodes (D:\job\sharePoint\locations\node_modules\@microsoft\rush-stack-compiler-3.3\node_modules\typescript\lib\typescript.js:16224:30)
    at Object.forEachChild (D:\job\sharePoint\locations\node_modules\@microsoft\rush-stack-compiler-3.3\node_modules\typescript\lib\typescript.js:16404:21)
```

## Steps to reproduce

package.json

```
{
  "name": "locations",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test",
    "type-lint": "tsc --noEmit -p tsconfig.json",
    "package": "gulp bundle --ship && gulp package-solution --ship",
    "lint": "tslint --fix -c ./tslint.json 'src/**/*{.ts,.tsx}'",
    "prettier": "prettier --config .prettierrc.yaml --write src/**/*.ts src/**/*.tsx",
    "commit": "git-cz"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run prettier",
      "pre-push": "npm run type-lint && npm run lint"
    }
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-lodash-subset": "1.10.0",
    "@microsoft/sp-office-ui-fabric-core": "1.10.0",
    "@microsoft/sp-property-pane": "1.10.0",
    "@microsoft/sp-webpart-base": "1.10.0",
    "@pnp/common": "^2.0.2",
    "@pnp/logging": "^2.0.2",
    "@pnp/odata": "^2.0.2",
    "@pnp/sp": "^2.0.2",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/webpack-env": "1.13.1",
    "office-ui-fabric-react": "6.189.2",
    "react": "16.8.5",
    "react-dom": "16.8.5"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/sp-build-web": "1.10.0",
    "@microsoft/sp-module-interfaces": "1.10.0",
    "@microsoft/sp-tslint-rules": "1.10.0",
    "@microsoft/sp-webpart-workbench": "1.10.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "commitizen": "^4.0.3",
    "cz-conventional-changelog": "^3.0.2",
    "gulp": "~3.9.1",
    "husky": "^4.2.0",
    "prettier": "^1.19.1",
    "tslint": "^6.0.0",
    "typescript": "^3.7.5"
  },
  "resolutions": {
    "@types/react": "16.8.8"
  },
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  }
}
```
tsconfig.json

```
{
  "extends": "./node_modules/@microsoft/rush-stack-compiler-3.3/includes/tsconfig-web.json",
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "outDir": "lib",
    "inlineSources": false,
    "strictNullChecks": false,
    "noUnusedLocals": false,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@microsoft"
    ],
    "types": [
      "es6-promise",
      "webpack-env"
    ],
    "lib": [
      "es5",
      "dom",
      "es2015.collection"
    ]
  },
  "include": [
    "src/**/*.ts", "src/**/*.tsx"
  ],
  "exclude": [
    "node_modules",
    "lib"
  ]
}
```
tslint.json

```
{
  "extends": "@microsoft/sp-tslint-rules/base-tslint.json",
  "rules": {
    "class-name": false,
    "export-name": false,
    "forin": false,
    "label-position": false,
    "member-access": true,
    "no-arg": false,
    "no-console": false,
    "no-construct": false,
    "no-duplicate-variable": true,
    "no-eval": false,
    "no-function-expression": true,
    "no-internal-module": true,
    "no-shadowed-variable": false,
    "no-switch-case-fall-through": true,
    "no-unnecessary-semicolons": true,
    "no-with-statement": true,
    "semicolon": true,
    "trailing-comma": false,
    "typedef": false,
    "typedef-whitespace": false,
    "use-named-parameter": true,
    "variable-name": false,
    "whitespace": false
  }
}
```

Component

```
import * as React from 'react';
import { Web } from "@pnp/sp/presets/all";

export const BreadcrumbComponent = () => {
  const web = Web('https://test/');
  web.lists.getByTitle('testList').items.get().then(result => { });
};
```
## Expected behavior

Terminal without error

## Developer environment

- OS: Windows 10
- Framework: [Node.js v10.13.0
- Browser(s): Chrome v79
- Tooling: VS Code, SPFx v1.10.0

**Comment by andrewconnell** [comment]
This isn't a general SharePoint dev issue. A default react project works fine with no error. I also added the PnP libraries and the same component and have no issue. 

The tslint rule implies you have a switch statement somewhere that's allowing fallthrough on cases. By default, that's not allowed as listed in the **tslint.json** file. If you want it, change the value of that rule in **tslint.json**.

Ref: https://palantir.github.io/tslint/rules/no-switch-case-fall-through
