### ISSUE TITLE
Site Creation using pnp provisioning engine takes a long time without proper errors.

### ISSUE THREAD

**Issue by arunkumarperumal** [SharePoint/sp-dev-docs#5510]
## Category

- [x] Bug

## Describe the bug

SharePoint Online Site Creation add apply template using PnP Provisioning engine takes a long time to execute and also there are no proper errors. For example an Modern team site is has taken more than 30 minutes and is still going on.

Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

## Steps to reproduce

Create a site collection using powershell or using the .net PnP Provisioning engine.

## Expected behavior

Sites are created and template applied without errors.

### Additional context

Below are some of the logs. 
Type = Microsoft.SharePoint.Client.ServerException
Message = Cannot complete this action.

Please try again.
Source = Microsoft.SharePoint.Client.Runtime
ServerStackTrace = 
ServerErrorCode = -2147467259
ServerErrorTypeName = Microsoft.SharePoint.SPException
ServerErrorTraceCorrelationId = e1ae429f-5072-b000-fae9-15ee81114b1f
TargetSite = Void ProcessResponseStream(System.IO.Stream)
StackTrace =    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()

Type = Microsoft.SharePoint.Client.ServerException
Message = Cannot find the endpoint specified by the configuration file.
Source = Microsoft.SharePoint.Client.Runtime
ServerStackTrace = 
ServerErrorCode = -1
ServerErrorTypeName = Microsoft.Online.SharePoint.Common.SpoException
ServerErrorTraceCorrelationId = d7ae429f-1088-b000-1347-e8c4f0efd29d
TargetSite = Void ProcessResponseStream(System.IO.Stream)
StackTrace =    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at Factory.SharePointSitesFactory.Create() in E:\Collaboration-SPO\Collaboration-SPO\Factory\Factory\SharePointSitesFactory.cs:line 121
   at Factory.Program.Main(String[] args) in E:\Collaboration-SPO\Collaboration-SPO\Factory\Program.cs:line 123
HResult = -2146233088

*Thanks for your contribution! Sharing is caring.*

**Comment by JarbasHorst** [comment]
Hello @arunkumarperumal 

although your question is related to SharePoint development, it would be more appropriate to post this issue to the PnP-Sites-Core support forum, since this forum is focused on provisioning related topics: https://github.com/pnp/PnP-Sites-Core/issues

Thank you!

Regards,
Jarbas

Regards

**Comment by andrewconnell** [comment]
@JarbasHorst is correct, this should be posted to the PnP Sites Core / PnP Provisioning repo as it's specific to those topics. We can't transfer the issue as those repos are in a different org.
