### ISSUE TITLE
Workflow Service Manager is not responding for the PNP workflows

### ISSUE THREAD

**Issue by Prasanna27081987** [SharePoint/sp-dev-docs#5685]
## Category

- [ ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Workflow Service Manager is not responding for the PNP workflows

## Question

We are trying to get the workflow details and initiate workflow with PNP commands but it is not working in our Production tenant and it giving below error. But the same function working in our another tenant (Dev).

Get-PnPList -Connection $conn | % { Get-PnPWorkflowSubscription -Connection $conn -List $_ }
 
 
writeErrorStream      : True
PSMessageDetails      :
Exception             : Microsoft.SharePoint.Client.ServerException: Cannot invoke method or retrieve property from null object. Object returned by the following call stack
                         is null. "GetWorkflowSubscriptionService
                        new Microsoft.SharePoint.WorkflowServices.WorkflowServicesManager()
                        "
                           at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                           at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                           at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, Strin
                        g userAgent)
                           at SharePointPnP.PowerShell.Commands.Workflows.GetWorkflowSubscription.ExecuteCmdlet()
                           at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
TargetObject          :
CategoryInfo          : WriteError: (:) [Get-PnPWorkflowSubscription], ServerException
FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Workflows.GetWorkflowSubscription
ErrorDetails          : Cannot invoke method or retrieve property from null object. Object returned by the following call stack is null. "GetWorkflowSubscriptionService
                        new Microsoft.SharePoint.WorkflowServices.WorkflowServicesManager()
                        "
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

## Environment details (if applicable)

- **OS**: [SharePoint Online]
- **Target Environment**: [SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.5]
- **Browser(s)**: [e.g. Chrome v81]
- **Tooling**: [NA]
- **Additional details**: *Please let us know why the we are getting this error in our production O365 tenant. Please reach me prasanna.asokan.ext@siemensgamesa.com for more details. We opened a MS ticket [Case #:19570697] and they advised be report an issue here. Please do the needful at the earliest*

**Comment by andrewconnell** [comment]
This issue is more about the PnP cmdlets... please open your issue in it's repo... https://github.com/pnp/PnP-PowerShell
