### ISSUE TITLE
gulp-trust-dev error throwing 

### ISSUE THREAD

**Issue by sohailrazarizvi** [SharePoint/sp-dev-docs#5693]
## Category

- [x] Bug

## Describe the bug

After installing all latest client-side toolchain, today I have started SPFx development and created firstspfx-webpart project and as part when I run 

gulp trust-dev-cert

I see this

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\Projects\SPFx Kindle\firstspfx-webpart\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Projects\SPFx Kindle\firstspfx-webpart\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Projects\SPFx Kindle\firstspfx-webpart\node_modules\gulp\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Projects\SPFx Kindle\firstspfx-webpart\node_modules\gulp\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)

## Steps to reproduce

Opened Command Windows (As Admin)
Installed/update all client-side toolchain (nodejs, npm, etc.)
Created a new folder for firstspfx-web
run yo @microsoft/generator command to create the SPFx project
Once firstspfx-webpart project is created; 
Run the command
gulp trust-dev-cert
Then I saw the above error.

Please advise; how I can fix it
1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide clear & concise description of what you expected to happen.

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide any other context about the problem.

*Thanks for your contribution! Sharing is caring.*

**Comment by derhallim** [comment]
Hi @sohailrazarizvi can you please verify which node version are you using? From your command line type `node -v` 

Make sure it's either v8.. or v10..

**Comment by PrasadKasireddy** [comment]
it seems to be issue with NodeJs v12, please refer the fixes as below
https://github.com/SharePoint/sp-dev-docs/issues/5089
https://github.com/SharePoint/sp-dev-docs/issues/4422

**Comment by andrewconnell** [comment]
No context provided. Please feel free to resubmit and complete the issue template sections as requested. Otherwise, there's zero context to investigate or help with your scenario.
