### ISSUE TITLE
Sharepoint workbench browser error

### ISSUE THREAD

**Issue by charan86** [SharePoint/sp-dev-docs#5744]
## Category

- [x] Bug

## Describe the bug

when i run **gulp serve** command i get errors on "tsc" als 
**[12:09:29] [tsc] error TS1149: File name '/home/sharepointuser/sharepoint/src/webparts/sharepoint/SharepointWebPart.module.scss.ts' differs from already included file name '/home/sharepointuser/sharepoint/src/webparts/sharePoint/SharePointWebPart.module.scss.ts' only in casing.**
Also i get the error in browser -> https://<ipaddress>:5432/temp/workbench.html

Error: ENOENT: no such file or directory, stat '/home/sharepointuser/sharepoint/dist/public/temp/workbench.html'
    at Object.statSync (fs.js:855:3)
    at getPublic (/home/sharepointuser/sharepoint/node_modules/@microsoft/sp-webpart-workbench/lib/api/getPublic.js:32:21)
    at Layer.handle [as handle_request] (/home/sharepointuser/sharepoint/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/sharepointuser/sharepoint/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/sharepointuser/sharepoint/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/sharepointuser/sharepoint/node_modules/express/lib/router/layer.js:95:5)
    at /home/sharepointuser/sharepoint/node_modules/express/lib/router/index.js:281:22
    at param (/home/sharepointuser/sharepoint/node_modules/express/lib/router/index.js:354:14)
    at param (/home/sharepointuser/sharepoint/node_modules/express/lib/router/index.js:365:14)
    at param (/home/sharepointuser/sharepoint/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/sharepointuser/sharepoint/node_modules/express/lib/router/index.js:410:3)
    at next (/home/sharepointuser/sharepoint/node_modules/express/lib/router/index.js:275:10)
    at _setJSONResponseContentTypeMiddleware (/home/sharepointuser/sharepoint/node_modules/@microsoft/gulp-core-build-serve/lib/ServeTask.js:119:9)
    at Layer.handle [as handle_request] (/home/sharepointuser/sharepoint/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/sharepointuser/sharepoint/node_modules/express/lib/router/index.js:317:13)
    at /home/sharepointuser/sharepoint/node_modules/express/lib/router/index.js:284:7

Below are the version details installed in my setup

/home/sharepointuser/.nvm/versions/node/v10.20.1/lib
├── @microsoft/generator-sharepoint@1.10.0
├── gulp@4.0.2
├── npm@6.14.5
└── yo@3.1.1

 ## Steps to reproduce
while executing gulp serve in my environment

## Environment details (*development & target environment*)
Facing this issue in ubuntu latest version

![spfx_workbench](https://user-images.githubusercontent.com/65380495/82005718-b2a10280-9683-11ea-9ed7-98df28e99757.PNG)

**Comment by andrewconnell** [comment]
Did you rename the file... appears so from the error? Have you tried deleting all built files (**gulp clean**) and rebuilding the project with just **gulp build** first?

**Comment by charan86** [comment]
Yeah i tried **gulp clean** and then **gulp build** but get the below error which is similar when i run gulp serve
![gulp_build-error](https://user-images.githubusercontent.com/65380495/82052474-523cb000-96d9-11ea-8992-e874fd0b7602.PNG)

**Comment by andrewconnell** [comment]
The task **gulp serve** runs **gulp build**... the error is coming from the **build** task. I can't repro this... 

Ss I said in my last reply, it looks like it's a filename casing error that you've changed... you didn't reply to that. So...?

If you can somehow share a repro (upload your project to a public GH repo), I can try to repro it, but at this point, can't repro so it's hard to help.

**Comment by charan86** [comment]
If i rename the file will it work?

**Comment by charan86** [comment]
@andrewconnell there was two folder in the name **sharepoint** && **sharePoint** in /src/webparts directory . I have moved the old sharepoint directory to different location and now the casing error is not appearing. 

But still the ENOENT error appears also there is not dist directory exist. Not sure what causing this issue. 
![ENOENT](https://user-images.githubusercontent.com/65380495/82070805-e2d3ba00-96f2-11ea-95e5-48c7855697ae.PNG)

**Comment by andrewconnell** [comment]
Sorry, but same response. 

@andrewconnell said: 
> If you can somehow share a repro (upload your project to a public GH repo), I can try to repro it, but at this point, can't repro so it's hard to help.

**Comment by charan86** [comment]
@andrewconnell What i observed i when i run gulp serve the temp directory which will have workbench.html is not creating

**Comment by andrewconnell** [comment]
Respectfully @charan86, I'm going to keep saying the same thing until you share it. I can't reproduce this and have suggested you please provide a reproduction to help. Otherwise, it's impossible to move forward.

**Comment by charan86** [comment]
@andrewconnell I have pushed the files into repo and the link is https://github.com/charan86/spfx-projectFolder.git.

**Comment by andrewconnell** [comment]
I cloned this project, & ran NPM INSTALL. Right away it failed trying to install the dependencies. 

How did you create this? The **package.json** doesn't look normal... some of your dependencies aren't present in a normal SPFx v1.10 project like **@microsoft/gulp-core-buld-serve** & **@microsoft/sp-module-loader**.

How did you create this project? When you follow the [tutorial on this page](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part), what's your experience?

**Comment by charan86** [comment]
@andrewconnell yeah i followed the same steps as you mentioned in this link [tutorial on this page](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
