### ISSUE TITLE
Gulp Serve Error: Error: EISDIR: illegal operation on a directory, symlink : SPFx

### ISSUE THREAD

**Issue by Kanchan15** [SharePoint/sp-dev-docs#6001]
## Category

- [ ] Question

## Question

> The soultion is running perfectly fine from C drive however when I copied the same solution in H drive(network drive) 
and run gulp server, https://localhost:5432/workbench is launched in the browser and I get the following error

Error: EISDIR: illegal operation on a directory, symlink 'H:\New folder\Test\node_modules\@microsoft\sp-webpart-workbench' -> 'H:\New folder\Test\temp\workbench-packages\@microsoft_sp-webpart-workbench'
    at Object.symlinkSync (fs.js:909:3)
    at WorkbenchPage._getUrlForPackagePath (H:\New folder\Test\node_modules\@microsoft\sp-webpart-workbench\lib\api\WorkbenchPage.js:166:17)
    at WorkbenchPage._generateWorkbenchPageContent (H:\New folder\Test\node_modules\@microsoft\sp-webpart-workbench\lib\api\WorkbenchPage.js:33:39)
    at WorkbenchPage.handleWorkbenchRequest (H:\New folder\Test\node_modules\@microsoft\sp-webpart-workbench\lib\api\WorkbenchPage.js:25:51)
    at Layer.handle [as handle_request] (H:\New folder\Test\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\New folder\Test\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\New folder\Test\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (H:\New folder\Test\node_modules\express\lib\router\layer.js:95:5)
    at H:\New folder\Test\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (H:\New folder\Test\node_modules\express\lib\router\index.js:335:12)
    at next (H:\New folder\Test\node_modules\express\lib\router\index.js:275:10)
    at _setJSONResponseContentTypeMiddleware (H:\New folder\Test\node_modules\@microsoft\gulp-core-build-serve\lib\ServeTask.js:119:9)
    at Layer.handle [as handle_request] (H:\New folder\Test\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (H:\New folder\Test\node_modules\express\lib\router\index.js:317:13)
    at H:\New folder\Test\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (H:\New folder\Test\node_modules\express\lib\router\index.js:335:12)
	
	Please let me know if we can run the SPFx solution from network drive

## Environment details (*development & target environment*)

>

- **Your Developer Environment**: [e.g. Windows 7
-**Target Environment**: SharePoint Online
- **Framework**: Node.js v 10.18.0
- **Browser(s)**: [e.g. Chrome v79 , IE v11 ,  Edge
- **Tooling**: VS Code

**Comment by andrewconnell** [comment]
This isn't an SPFx issue, rather it's a common topic that comes up with Node/NPM. Could be permissions, A/V, and any number of other things.

As a result, it isn't recommended to run projects from network drives.
