### ISSUE TITLE
Additional properties not allowed: developer

### ISSUE THREAD

**Issue by q-le** [SharePoint/sp-dev-docs#6096]
## Describe the bug
I am trying to deploy a Sharepoint Webpart to the Microsoft AppSource aiming at Sharepoint via the Partner Center.  It is saying SPFx Solutions are not acceptable.  But the solution is version 1.11 and everywhere I am seeing "Must be v1.11 or newer."  Thus, I am looking through this https://docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-checklist to see if I am missing anything.  Got an error when I run "gulp bundle --ship" after adding the "developer" section to the /config/package-solution.json

Error: #/solution
       Additional properties not allowed: developer
    at validateObjectWithCallback (C:\Users\x\x\widget\A\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178:19)
    at JsonSchema.validateObjectWithCallback (C:\Users\x\x\widget\A\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:193:13)
    at JsonSchema.validateObject (C:\Users\x\x\widget\A\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:175:14)
    at PackageSolutionTask._readConfigFile (C:\Users\x\x\widget\A\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:312:28)
    at PackageSolutionTask.onRegister (C:\Users\x\x\widget\A\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:88:32)
    at Object.initialize (C:\Users\x\x\widget\A\node_modules\@microsoft\gulp-core-build\lib\index.js:299:24)
    at SPWebBuildRig.initialize (C:\Users\x\x\widget\A\node_modules\@microsoft\sp-build-common\lib\BuildRig.js:61:19)
    at SPWebBuildRig.initialize (C:\Users\x\x\widget\A\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:23:15)
    at SPWebBuildRig.initialize (C:\Users\x\x\widget\A\node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js:15:15)
    at Object.exports.initialize (C:\Users\x\x\widget\A\node_modules\@microsoft\sp-build-web\lib\index.js:23:17)
    at Object.<anonymous> (C:\Users\x\x\widget\A\gulpfile.js:7:7)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

## Steps to reproduce

1. Update @microsoft/generator-sharepoint to version 1.11
2. Create new Sharepoint solution "yo @microsoft/sharepoint"
3. Add developer section to package-solution.json following this document https://docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-checklist 
4. run gulp bundle --ship
5. get error of above

## Expected behavior
Successfully bundle the solution with ship flag as if I didnt add any "developer" section to package-solution.json

## Environment details (*development & target environment*)

- **Your Developer Environment**:   Windows 10 
- **Target Environment**: SharePoint Server 2019/SharePoint Online
- **Framework**: Node.js v10
- **Tooling**:  VS Code | SPFx v1.11.0 | 
- **Additional details**:  gulp v3.9.1 , @microsoft/generator-sharepoint@1.11.0

**Comment by andrewconnell** [comment]
Please share your **package-solution.json** file... I assume you aren't pointing to the correct schema file...

**Comment by q-le** [comment]
Hi andrew, it is pointing to the correct schema; our IDE wasn't screaming and also it has autocomplete on it.  We found the issue though, the package.json produced by generator wasn't updated although it is version 1.11.  We updated all of the @microsoft/* packages to version 1.11. Then it required us to add a dependency "@microsoft/rush-stack-compiler-3.2".  After that things are working.
