### ISSUE TITLE
fs.js:114  throw err

### ISSUE THREAD

**Issue by jtlivio** [SharePoint/sp-dev-docs#6166]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Hope this is the right place to put this.

WebParts was working, today I get this, any help?
Thanks

fs.js:114
    throw err;
    ^

Error: UNKNOWN: unknown error, lstat 'C:\Users\PTL14646\SPFX\CTHMAD\WP\node_modules\@microsoft\sp-build-core-tasks\lib\configJson'
    at toRealPath (internal/modules/cjs/loader.js:241:13)
    at tryFile (internal/modules/cjs/loader.js:237:22)
    at tryExtensions (internal/modules/cjs/loader.js:249:22)
    at Function.Module._findPath (internal/modules/cjs/loader.js:331:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:633:25)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\PTL14646\SPFX\CTHMAD\WP\node_modules\@microsoft\sp-build-core-tasks\lib\index.js:14:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10]
- **Tooling**: [VS Code | SPFx v1.10.0]

**Comment by jtlivio** [comment]
I Could clone from GitHub the latest commit, is working, no clue for this kind of behavior

**Comment by andrewconnell** [comment]
Unfortunately, there's not enough information to do anything with this post. If you can submit a repro, that would help.
