### ISSUE TITLE
Getting Invalid hook call Hooks can only be called inside of the body of a function component in React app right in the HelloWorld Template

### ISSUE THREAD

**Issue by TheInvoker** [SharePoint/sp-dev-docs#6230]
## Category

- [x] Bug

I get this

	sp-webpart-workbench-assembly_default.js:26401 [1599066762186][OtherGlobalError.window.onerro] Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
	1. You might have mismatching versions of React and the renderer (such as React DOM)
	2. You might be breaking the Rules of Hooks
	3. You might have more than one copy of React in the same app
	See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
	H9JW.TraceLogger._writeToConsole @ sp-webpart-workbench-assembly_default.js:26401
	sp-webpart-workbench-assembly_default.js:75345 Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
	1. You might have mismatching versions of React and the renderer (such as React DOM)
	2. You might be breaking the Rules of Hooks
	3. You might have more than one copy of React in the same app
	See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
		at invariant (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:75338:15)
		at Object.throwInvalidHookError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:88115:3)
		at Object.useState (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:73014:21)
		at HelloWorld.9SGU.HelloWorld.render (https://localhost:4321/dist/hello-world-web-part.js:151:64)
		at finishClassComponent (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:89989:31)
		at updateClassComponent (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:89944:24)
		at beginWork (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:90892:16)
		at performUnitOfWork (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:94560:12)
		at workLoop (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:94600:24)
		at HTMLUnknownElement.callCallback (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:75432:14)
	sp-webpart-workbench-assembly_default.js:92365 The above error occurred in the <HelloWorld> component:
		in HelloWorld

	Consider adding an error boundary to your tree to customize error handling behavior.
	Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
	logCapturedError @ sp-webpart-workbench-assembly_default.js:92365
	sp-webpart-workbench-assembly_default.js:75338 Uncaught (in promise) Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
	1. You might have mismatching versions of React and the renderer (such as React DOM)
	2. You might be breaking the Rules of Hooks
	3. You might have more than one copy of React in the same app
	See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
		at invariant (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:75338:15)
		at Object.throwInvalidHookError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:88115:3)
		at Object.useState (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:73014:21)
		at HelloWorld.9SGU.HelloWorld.render (https://localhost:4321/dist/hello-world-web-part.js:151:64)
		at finishClassComponent (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:89989:31)
		at updateClassComponent (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:89944:24)
		at beginWork (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:90892:16)
		at performUnitOfWork (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:94560:12)
		at workLoop (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:94600:24)
		at renderRoot (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:94683:7)

## Steps to reproduce

md helloworld-webpart2
cd helloworld-webpart2
yo @microsoft/sharepoint
(select SP Online latest, React)
(modify code like below, add the 1 line of code to add the hook) (helloworld-webpart2\src\webparts\helloWorld\components\HelloWorld.tsx)
gulp serve

## Expected behavior

No error should occur

## Environment details (*development & target environment*)

Windows 10
SharePoint Online
Node v10
Chrome v79
VS Code | SPFx v1.10.0 

### Additional context

Code 

	import * as React from 'react';
	import styles from './HelloWorld.module.scss';
	import { IHelloWorldProps } from './IHelloWorldProps';
	import { escape } from '@microsoft/sp-lodash-subset';

	export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {
	  public render(): React.ReactElement<IHelloWorldProps> {
		const [count, setCount] = React.useState(0); // THIS LINE CAUSES HOOK ISSUE <-----------------
		return (
		  <div className={ styles.helloWorld }>
			<div className={ styles.container }>
			  <div className={ styles.row }>
				<div className={ styles.column }>
				  <span className={ styles.title }>Welcome to SharePoint!</span>
				  <p className={ styles.subTitle }>Customize SharePoint experiences using Web Parts.</p>
				  <p className={ styles.description }>{escape(this.props.description)}</p>
				  <a href="https://aka.ms/spfx" className={ styles.button }>
					<span className={ styles.label }>Learn more</span>
				  </a>
				</div>
			  </div>
			</div>
		  </div>
		);
	  }
	}

Checking the version of react and react dom I get

https://imgur.com/MLbcAWi

**Comment by TheInvoker** [comment]
I was able to fix this. This can be closed.
