### ISSUE TITLE
error tried to run "gulp serve"

### ISSUE THREAD

**Issue by wliang117** [SharePoint/sp-dev-docs#6429]
C:\Users\admin\Desktop\SharePoint\uiFabricApp\documentcardexample-webpart>gulp serve
**ReferenceError: primordials is not defined**
    at fs.js:36:5
    at req_ (C:\Users\admin\Desktop\SharePoint\uiFabricApp\documentcardexample-webpart\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\admin\Desktop\SharePoint\uiFabricApp\documentcardexample-webpart\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\admin\Desktop\SharePoint\uiFabricApp\documentcardexample-webpart\node_modules\gulp\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\admin\Desktop\SharePoint\uiFabricApp\documentcardexample-webpart\node_modules\gulp\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f89fed-848e-50b9-6be4-657824ad262e
* Version Independent ID: 3d3c5227-7281-ef49-a2d1-686c0a049497
* Content: [Use Office UI Fabric React components in your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components)
* Content Source: [docs/spfx/web-parts/get-started/use-fabric-react-components.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/use-fabric-react-components.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Please update or re-create your issue using the issue template provided when submitted a ticket. 

Subsequently, it looks like you are using the wrong version of Node.

**Comment by wliang117** [comment]
Thanks. I downgrade node to v10, the error went away.
