### ISSUE TITLE
react-rssreader sample 

### ISSUE THREAD

**Issue by Truez** [SharePoint/sp-dev-docs#6472]
## Category

- [ X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Complete novice around SPFX so I am expecting this to be simple so sorry in advanced! 

I downloaded a copy of the SP-DEV-FX web parts with the vision to get the react-rssreader working. After some time managed to get it loading in the localhost workbench no problems. Made some custom edits (New properties and reworking of the links so they point when clicked they navigate to my companies website and the corresponding update). All working locally and I have managed to get it deployed to a dev tenant.

The problem is when I deploy I have followed the microsoft documentation around creating the app catalog and opening the public CDN on both dev and prod tenant. 

I user the two following commands
gulp bundle ship followed by gulp package-solution --ship

[13:28:43] Project react-rssreader version:1.0.0
[13:28:43] Build tools version:3.8.33
[13:28:43] Node version:v8.17.0
[13:28:43] Total duration:24 s

[13:28:54] Project react-rssreader version:1.0.0
[13:28:54] Build tools version:3.8.33
[13:28:54] Node version:v8.17.0
[13:28:54] Total duration:4.28 s

When I upload the sppkg file to the app catalog I am receiving 

This client side solution will get content from the following domains:

HTTPS://SPCLIENTSIDEASSETLIBRARY/ ; https://cdnjs.cloudflare.com

I was expecting SharePoint Online after following Waldeks video on youtube but no success. 

Windows 10 Machine 

Hoping someone can point me in the right direction.

I've been following the [Build your first SPFX web part series ](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part) to help guide me in deploying this solution.

What am I doing wrong!!!!!!

Cheers

**Comment by Truez** [comment]
I've just followed the hellow world web part (inclduing setting up your environment) and when I deploy it shows sharepoint online.

Now I have tried again with react-rss reader but I am getting the following error 
Error: Your dev environment is running NodeJS version v10.23.0 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0
    at SPWebBuildRig.initialize (C:\Users\gbtly\Documents\GitHub\PNP\sp-dev-fx-webparts\samples\react-rss-reader\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:25:19)
    at SPWebBuildRig.initialize (C:\Users\gbtly\Documents\GitHub\PNP\sp-dev-fx-webparts\samples\react-rss-reader\node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js:15:15)
    at Object.exports.initialize (C:\Users\gbtly\Documents\GitHub\PNP\sp-dev-fx-webparts\samples\react-rss-reader\node_modules\@microsoft\sp-build-web\lib\index.js:23:17)
    at Object.<anonymous> (C:\Users\gbtly\Documents\GitHub\PNP\sp-dev-fx-webparts\samples\react-rss-reader\gulpfile.js:50:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

Do I need to update the project somehow?

**Comment by nanddeepn** [comment]
Hi @Truez 
The [React-RSS-Reader](https://github.com/pnp/sp-dev-fx-webparts/blob/master/samples/react-rss-reader/package.json) web part is implemented with SPFx v1.7.0.
Please use the Node version 8.x

Also, any issues related to SPFx PnP web parts, can be reported [here](https://github.com/pnp/sp-dev-fx-webparts/issues).

**Comment by Truez** [comment]
Moved to [SPFX web parts ](https://github.com/pnp/sp-dev-fx-webparts/issues/1604)
