### ISSUE TITLE
IE 11 - error while setting focal point on banner images

### ISSUE THREAD

**Issue by gautamdsheth** [SharePoint/sp-dev-docs#6618]
## Category

- [x] Bug

## Describe the bug

The modern SharePoint pages which have a banner image with focal point set throw SPFx error in IE 11. It works correctly in other browsers.

## Steps to reproduce

1. Create a modern page in a communication or team site. If you already have one, use that .
2. Select a banner image.
3. Set a focal point in that image.
4. Save and publish the page. 
5. Refresh the page.
6. If you are not in IE 11, open that page in IE 11 browser.
7. It throws error as below:

![image](https://user-images.githubusercontent.com/8832018/104847273-119ad380-5905-11eb-8dfc-98dd86eec1b0.png)

Error stack:
```
Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
Technical Details
ERROR:
Object doesn't support property or method 'trunc'

CALL STACK:
TypeError: Object doesn't support property or method 'trunc'
   at e.convertFocalPointToCropMode (https://spoprod-a.akamaihd.net/files/sp-client/sp-title-region-webpart_en-us_39f05ee8d592b52e88a0.js:1:38026)
   at e.prototype._generateThumbnailUrl (https://spoprod-a.akamaihd.net/files/sp-client/sp-title-region-webpart_en-us_39f05ee8d592b52e88a0.js:1:39402)
   at r.value (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_bb60822c281191ab42d0007199d807ab.js:1:1769644)
   at e.prototype._getSharePointImageURL (https://spoprod-a.akamaihd.net/files/sp-client/sp-title-region-webpart_en-us_39f05ee8d592b52e88a0.js:1:38809)
   at r.value (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_bb60822c281191ab42d0007199d807ab.js:1:1769644)
   at e.prototype.getImageURL (https://spoprod-a.akamaihd.net/files/sp-client/sp-title-region-webpart_en-us_39f05ee8d592b52e88a0.js:1:38334)
   at r.value (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_bb60822c281191ab42d0007199d807ab.js:1:1769644)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-title-region-webpart_en-us_39f05ee8d592b52e88a0.js:1:74462)
   at Kl (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_bb60822c281191ab42d0007199d807ab.js:1:1492055)
   at aa (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_bb60822c281191ab42d0007199d807ab.js:1:1507684)
```

This happens to older pages as well , not just newly created pages.

## Expected behavior

It should show image with focal point set in IE 11. It already works correctly in other browsers.

## Environment details (*development & target environment*)

Any SharePoint Online environment. The tenant that I am using is first release tenant, but it could be there in others as well.

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Browser(s)**: IE v11

**Comment by IrisChau-KBQ** [comment]
I find the same issue too.

**Comment by koskila** [comment]
I could reproduce this as well. The picture doesn't load in IE11 but instead you get the error shown in the console excerpts above.

**Comment by ChemaMateos** [comment]
Same error here

**Comment by NetZTE** [comment]
Same here. Hopefully it can be resolved soon.....
