### ISSUE TITLE
Azure Devops Use NodeJS 10.x (uses an old version)

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-docs#6719]
I followed the build definitio steps mentioned here:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops

However I have the following issue on my NPM task step:

Only pasted the lines with some errors:

```

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js:7
const envPaths = require('env-paths')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:433:25)
    at Object.Module._extensions..js (module.js:468:10)
    at Module.load (module.js:350:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:491:10)
    at startup (node.js:119:16)
    at node.js:792:3
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE

npm ERR! errno 8
npm ERR! deasync@0.1.21 install: `node ./build.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the deasync@0.1.21 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2021-02-17T07_44_20_244Z-debug.log
> deasync@0.1.21 install D:\a\1\s\node_modules\deasync
> node ./build.js


stdout=
err=Error: Command failed: 
D:\a\1\s\node_modules\bindings\bindings.js:135
  throw err;
        ^
Error: Could not locate the bindings file. Tried:
 → d:\a\1\s\node_modules\deasync\build\deasync.node
 → d:\a\1\s\node_modules\deasync\build\Debug\deasync.node
 → d:\a\1\s\node_modules\deasync\build\Release\deasync.node
 → d:\a\1\s\node_modules\deasync\out\Debug\deasync.node
 → d:\a\1\s\node_modules\deasync\Debug\deasync.node
 → d:\a\1\s\node_modules\deasync\out\Release\deasync.node
 → d:\a\1\s\node_modules\deasync\Release\deasync.node
 → d:\a\1\s\node_modules\deasync\build\default\deasync.node
 → d:\a\1\s\node_modules\deasync\compiled\0.11.6\win32\ia32\deasync.node
 → d:\a\1\s\node_modules\deasync\addon-build\release\install-root\deasync.node
 → d:\a\1\s\node_modules\deasync\addon-build\debug\install-root\deasync.node
 → d:\a\1\s\node_modules\deasync\addon-build\default\install-root\deasync.node
 → d:\a\1\s\node_modules\deasync\lib\binding\node-v0x000C-win32-ia32\deasync.node
    at bindings (D:\a\1\s\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (D:\a\1\s\node_modules\deasync\index.js:30:31)
    at Module._compile (module.js:450:26)
    at Object.Module._extensions..js (module.js:468:10)
    at Module.load (module.js:350:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:358:17)
    at require (module.js:374:17)
    at Object.<anonymous> (D:\a\1\s\node_modules\deasync\quick-test.js:3:13)
    at Module._compile (module.js:450:26)

```

As explained in the docs, I used Node 10.x on the previous step: However I did notice the following:
```

Starting: Use Node 10,x
==============================================================================
Task         : Node.js tool installer
Description  : Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
Version      : 0.179.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/node-js
==============================================================================
Downloading: https://nodejs.org/dist/v0.11.6/node-v0.11.6-win-x64.7z
Downloading: https://nodejs.org/dist/v0.11.6/win-x64/node.exe
Downloading: https://nodejs.org/dist/v0.11.6/node.exe
Downloading: https://nodejs.org/dist/v0.11.6/node.lib
Caching tool: node 0.11.6 x64
Prepending PATH environment variable with directory: C:\hostedtoolcache\windows\node\0.11.6\x64
Finishing: Use Node 10,x

```

the YAML step is like this:
```
steps:
- task: NodeTool@0
  displayName: 'Use Node 10,x'
  inputs:
    versionSpec: '10,x'
    checkLatest: true

```

Azure devops isnt supposed to install 10.x instead of 0.11.6? Something weird

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db891d3-c14d-9bae-80fc-cedaf2eb5982
* Version Independent ID: aae8a107-ee2a-7b9c-9022-9946b7f65909
* Content: [Implement Continuous Integration and Continuous deployment using Azure DevOps](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops)
* Content Source: [docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by levalencia** [comment]
the error was on my end and ashamed (due to my keyboard).
on the Use Node step, I was using comma instead of dot but couldnt see the difference in my screen  (10,x   -> 10.x)
