### ISSUE TITLE
Custom property pane is throwing error message all the sudden

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#674]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

The property panel with custom field is throwing an error message all the sudden and cannot be opened. This has been working for ages until today it doesn't work. Has there been any changes on how to implement custom property panel? How do I specify the "Custom field key" ?

`sp-classic-page-assembly_en-us_7096014….js:355 Error: ***The value for "Custom field key" must not be undefined
    at Function.e.isNotNullOrUndefined (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-16.013/sp-classic-page-assembly_en-us_70960144ad4f9879b104e4312ea59a4e.js:206:1058)
    at Function.e.isNonemptyString (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-16.013/sp-classic-page-assembly_en-us_70960144ad4f9879b104e4312ea59a4e.js:206:1163)
    at t._renderGroupField (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-16.013/0.sp-webpart-base-propertypane_70f54fa0e637aa95b553.js:1:28447)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-16.013/0.sp-webpart-base-propertypane_70f54fa0e637aa95b553.js:1:28259
    at Array.map (native)
    at t._renderGroupContent (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-16.013/0.sp-webpart-base-propertypane_70f54fa0e637aa95b553.js:1:28234)
    at t.render (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-16.013/0.sp-webpart-base-propertypane_70f54fa0e637aa95b553.js:1:26942)
    at p._renderValidatedComponentWithoutOwnerOrContext (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-16.013/sp-classic-page-assembly_en-us_70960144ad4f9879b104e4312ea59a4e.js:371:50265)
    at p._renderValidatedComponent (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-16.013/sp-classic-page-assembly_en-us_70960144ad4f9879b104e4312ea59a4e.js:371:50392)
    at performInitialMount (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-16.013/sp-classic-page-assembly_en-us_70960144ad4f9879b104e4312ea59a4e.js:371:46233)`

![image](https://user-images.githubusercontent.com/6864547/27590040-44024612-5b45-11e7-9377-70e740b5f1f7.png)

**Comment by patmill** [comment]
The assumption was that you would pass in a key in the underlying call.  If undefined was passed in, it could cause errors and odd behaviour.  We now make sure that a key is passed in.  Can you update your code to ensure the key isn't undefined?

**Comment by srideshpande** [comment]
@jonathanhotono,

Thanks for raising the concern.

The reason you are seeing this is when you create a custom field you have to provide a unique `key` to it. This property is there for some time now and it was always a `required` field. The recent change we made in this regard is that we are now validating it to have a non-empty value. The reason we had to validate is that it introduces an issue while rendering the custom fields on the property pane. If you are passing an `undefined` or `null` or `empty` value for the `key` prop then you will see this error.

> /**
>   A UNIQUE key indicates the identity of this control.
>   The PropertyPane uses ReactJS to render its components. ReactJS uses keys to identify a component and if it should be re-rendered or not. This is a performance feature in ReactJS. Please read the following link to understand how to pick the value of the key.
>
> @see https://facebook.github.io/react/docs/lists-and-keys.html#keys
*/
> key: string;

So, the resolution for this would be that you have to pass in a **non-empty** value for that prop.

Please let me know if you need any more guidance in this regard.


Thanks for understanding,
Srikanth

**Comment by jonathanhotono** [comment]
@srideshpande @patmill thanks, the custom property panel now works on workbench after I added the key property, however when I bundled and packaged the solution then deployed it to the tenant there is an issue where it doesn't save the property (disabled the reactive mode) any longer however it still saves in workbench.
