### ISSUE TITLE
SharePoint spfx webparts seem to be taking up all sessionStorage in the browser

### ISSUE THREAD

**Issue by TazzyMan** [SharePoint/sp-dev-docs#6807]
## Category

- [x] Bug

## Describe the bug

Ever since a few weeks we get reports of our customers that our software is failing at random places. We investigated the issue and this seems to be happening at places where we use localStorage or sessionStorage in the browser to cache some things.
The error we see in our logs is: 'Failed to execute 'setItem' on 'Storage': Setting the value of '…' exceeded the quota’.
We added some logging to find what was filling the local or sessionStorage, so we created a hook on Storage.prototype in which we put a try...catch around the operation. When failing, we clean up some space, retry and create a report of that storage (entries, size etc) and we send that both to the console and to Application Insights, so that we can monitor these errors on all our customers tenants.
Everyday we get over a 1000 of these messages from all tenants, so we don't think it's an incident.
The items that are (will post below) in the sessionStorage, and even the items failing to be added seem to be related to mssearch* or spfx-ndsi* of over 3MB per item and storage seems to be limited to 10MB
Also reported this as a premier ticket, but they don't seem to know what to do with this.

## Steps to reproduce

Not really steps to reproduce, but this the report we made. In the header you see what item is being added (that failed) 
Below the line you see all items in that particular storage (session or local) ordered from biggest to small. Below the second line is the call stack when the error occured: Below a report of a single tenant.

sessionStorage => Failed to execute 'setItem' on 'Storage': Setting the value of 'mssearchux-cache-site-activities-rawsprefetch' exceeded the quota.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
timestamp:       Tue Mar 09 2021 10:04:02 GMT+0100 (Midden-Europese standaardtijd)
key:             mssearchux-cache-site-activities-rawsprefetch
value length:    .............7084274 (6.76 MB)
value:           {"cacheCreationTime":1615272817044,"cacheVersion":"0","puid":"10037ffea70ce4b5","cacheItems":{"scope:ffdb1c8e-29ce-4c71-8772-077a097174ca,ffdb1c8e-29ce-...
capacity (est.): ............10485760 (10 MB)
used:            .............7426392 (7.08 MB)
available:       .............3059368 (2.92 MB)
required bytes:  .............3542227 (3.38 MB)
removed bytes:   .............5787980 (5.52 MB)
fixed:           true
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
mssearchux-cache-site-activities-rawsprefetch, 3444116, 3.28 MB
spfx-ndsi-1615274963238-665, 980272, 957.3 KB
mssearchux-cache-spsites-activitiesprefetch, 925446, 903.76 KB
spfx-ndsi-1615274967710-913, 476056, 464.9 KB
spfx-ndsi-1615274965373-419, 456080, 445.39 KB
spfx-ndsi-1615274967380-353, 451848, 441.26 KB
spfx-ndsi-1615274965495-447, 424620, 414.67 KB
ms-oil-datasource-search-news-suggestions, 112494, 109.86 KB
AI_buffer, 40188, 39.25 KB
mssearchux-cache-searchConfiguration, 26140, 25.53 KB
mssearchux-cache-searchConfigurationFromEcs, 24424, 23.85 KB
mssearchux-cache-psst, 15420, 15.06 KB
{"authority":"https://login.microsoftonline.com/9e3ee5fe-3a99-45db-ac6e-691e86febef3/","clientId":"08e18876-6177-487e-b8b5-cf950c1e598c","scopes":"https://###.sharepoint.com/Files.ReadWrite.All https://###.sharepoint.com/Sites.FullControl.All https://###.sharepoint.com/Sites.ReadWrite.All https://###.sharepoint.com/TermStore.ReadWrite.All https://###.sharepoint.com/.default","homeAccountIdentifier":"YzlhMDI0ZjEtNTdiNy00MGVmLWFlODMtYmNhZjkzOThkYTcx.OWUzZWU1ZmUtM2E5OS00NWRiLWFjNmUtNjkxZTg2ZmViZWYz"}, 7298, 7.13 KB
{"authority":"https://login.microsoftonline.com/9e3ee5fe-3a99-45db-ac6e-691e86febef3/","clientId":"92b8143b-8f52-4ba9-8ca6-229b310a89c9","scopes":"17cdfa36-b203-4a05-ae40-1725a00ed1d1/user_impersonation 17cdfa36-b203-4a05-ae40-1725a00ed1d1/.default","homeAccountIdentifier":"YzlhMDI0ZjEtNTdiNy00MGVmLWFlODMtYmNhZjkzOThkYTcx.OWUzZWU1ZmUtM2E5OS00NWRiLWFjNmUtNjkxZTg2ZmViZWYz"}, 6236, 6.09 KB
ms-oil-datasource-SpHomeApiDataSource, 4462, 4.36 KB
LokiAuthToken, 3550, 3.47 KB
mssearchux-cache-pspd, 3056, 2.98 KB
msal.08e18876-6177-487e-b8b5-cf950c1e598c.idtoken, 2702, 2.64 KB
msal.idtoken, 2702, 2.64 KB
msal.92b8143b-8f52-4ba9-8ca6-229b310a89c9.idtoken, 2632, 2.57 KB
sp-application-base:NavigationDataStore, 1636, 1.6 KB
mssearchux-cache-personalaccountname, 1450, 1.42 KB
mssearchux-cache-warmupMsb, 1432, 1.4 KB
mssearchux-cache-warmupSubstrateSearch, 488, 488 Bytes
mssearchux-cache-searchcenterurl, 454, 454 Bytes
msal.08e18876-6177-487e-b8b5-cf950c1e598c.error.description, 318, 318 Bytes
msal.error.description, 318, 318 Bytes
msal.08e18876-6177-487e-b8b5-cf950c1e598c.client.info, 248, 248 Bytes
msal.92b8143b-8f52-4ba9-8ca6-229b310a89c9.client.info, 248, 248 Bytes
msal.client.info, 248, 248 Bytes
odsp-ds-WebDataSource({76f1a325-fd6b-4cc4-86a9-9a9b07db96f9}), 158, 158 Bytes
odsp-ds-GraphUserInfo, 112, 112 Bytes
odsp-ds-ViewNavDataSource-version, 78, 78 Bytes
odsp-ds-FavoriteFeed-version, 78, 78 Bytes
odsp-ds-SiteDataSource({ffdb1c8e-29ce-4c71-8772-077a097174ca})-version, 78, 78 Bytes
odsp-ds-GroupsDataSource-version, 76, 76 Bytes
ms-oil-datasource-FavoriteFeed-version, 76, 76 Bytes
ms-oil-datasource-PersonalActiveFeed-version, 76, 76 Bytes
ms-oil-datasource-Suggested-version, 76, 76 Bytes
ms-oil-datasource-SpHomeApiDataSource-version, 76, 76 Bytes
ms-oil-datasource-BookmarkFeed-version, 76, 76 Bytes
ms-oil-datasource-SettingsFeed-version, 76, 76 Bytes
ms-oil-datasource-SitePermission-version, 76, 76 Bytes
odsp-ds-SiteDataSource({d393d054-c787-4c58-92be-c77a07d53db6})-version, 76, 76 Bytes
ms-oil-datasource-ActiveNewsFeed-version, 76, 76 Bytes
odsp-ds-UserInfo-version, 76, 76 Bytes
ms-oil-datasource-PersonalActivity-version, 76, 76 Bytes
ms-oil-datasource-CompanyPromotedFeed-version, 76, 76 Bytes
ms-oil-datasource-RecentSites-version, 76, 76 Bytes
ms-oil-datasource-NewsViewCount-version, 76, 76 Bytes
ms-oil-datasource-SuggestedActiveFeed-version, 76, 76 Bytes
odsp-ds-WebDataSource({76f1a325-fd6b-4cc4-86a9-9a9b07db96f9})-version, 76, 76 Bytes
odsp-ds-GraphUserInfo-version, 76, 76 Bytes
sp-application-base:NavigationDataStore:buildId, 74, 74 Bytes
msameid, 72, 72 Bytes
lastCortexDisableFlagLogged, 66, 66 Bytes
experimentLogCacheTime, 56, 56 Bytes
msal.08e18876-6177-487e-b8b5-cf950c1e598c.error, 38, 38 Bytes
msal.error, 38, 38 Bytes
EXPLokiAuthToken, 26, 26 Bytes
ms-oil-datasource-search-news-suggestions-version, 24, 24 Bytes
experimentLogCache, 18, 18 Bytes
serviceworkerstate, 18, 18 Bytes
sp-home-application:CreateNewsButton, 8, 8 Bytes
SPPPLATSuiteNavcachedthissession, 8, 8 Bytes
ms-oil-datasource-FavoriteFeed, 4, 4 Bytes
odsp-ds-FavoriteFeed, 4, 4 Bytes
odsp-ds-SiteDataSource({d393d054-c787-4c58-92be-c77a07d53db6}), 4, 4 Bytes
ms-oil-datasource-ActiveNewsFeed, 4, 4 Bytes
ms-oil-datasource-PersonalActivity, 4, 4 Bytes
odsp-ds-ViewNavDataSource, 4, 4 Bytes
AI_sentBuffer, 4, 4 Bytes
ms-oil-datasource-Suggested, 4, 4 Bytes
ms-oil-datasource-BookmarkFeed, 4, 4 Bytes
odsp-ds-UserInfo, 4, 4 Bytes
ms-oil-datasource-SuggestedActiveFeed, 4, 4 Bytes
odsp-ds-SiteDataSource({ffdb1c8e-29ce-4c71-8772-077a097174ca}), 4, 4 Bytes
ms-oil-datasource-NewsViewCount, 4, 4 Bytes
ms-oil-datasource-CompanyPromotedFeed, 4, 4 Bytes
ms-oil-datasource-SettingsFeed, 4, 4 Bytes
ms-oil-datasource-RecentSites, 4, 4 Bytes
ms-oil-datasource-SitePermission, 4, 4 Bytes
ms-oil-datasource-PersonalActiveFeed, 4, 4 Bytes
odsp-ds-GroupsDataSource, 4, 4 Bytes
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
stack: Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'mssearchux-cache-site-activities-rawsprefetch' exceeded the quota.
    at Storage.window._setItem.Storage.setItem (https://###.sharepoint.com/sites/apps/ClientSideAssets/32cca86b-d67d-45c2-a26a-a7f1d2acafce/debble-application-customizers_86ae8461e5734d9e9d1ecf5119e2aa56.js:1:2436621)
    at Object.setItem (https://shell.cdn.office.net/shellux/o365/versionless/suiteux.shell.searchbox.44c26ca46b45bf98f644.js:1:7136)
    at https://shell.cdn.office.net/shellux/o365/versionless/suiteux.shell.searchbox.44c26ca46b45bf98f644.js:1:8523
    at https://shell.cdn.office.net/shellux/o365/versionless/suiteux.shell.searchbox.44c26ca46b45bf98f644.js:1:8692

## Expected behavior

at least a few MB's of sessionStorage to cache our stuff.

## Environment details (*development & target environment*)

This happens on all tenant and the usually use Chome or the  Edge browser

### Additional context
This is a simplified representation the code we use to log these issues, but you get the idea:

window["_setItem"] = Storage.prototype.setItem;
Storage.prototype.setItem = function(key, value){
try {
	window["_setItem"].apply(this, arguments);
} catch (e) {
	var report = createReport(this);
	console.log(report);
	sendToApplicationInsights(report);
	cleanup(this, value.length * 2);
	retry();
}

**Comment by MarkyDeParky** [comment]
I would like to confirm that we see this with our customers as well.

We have a web part solution that relies on caching data in localStorage to prevent unnecessary calls to various endpoints on each page load. The exception reported by the OP is the same exception we see every now and then in our Application Insights logs.  
In our logs it usualy comes in one of these two shapes:

`Failed to execute 'setItem' on 'Storage': Setting the value of 'msal.********-****-****-848e-db0c65044361.error.description' exceeded the quota.`

or 

`Error: could not resolve endpoints. Please check network and try again. Details: QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'msal.********-****-****-8dc5-424b4e7ed146.acquireTokenAccount|***[REMOVED DETAILS]***|dad9ce9b-e9c2-4597-b841-4a856540d6da' exceeded the quota.`

I haven't done any further research since we usually just skip the cache logic if this happens, preventing the solution to fail, but it would be very nice if we can safely depend on caching to be possible without these exceptions.

**Comment by TazzyMan** [comment]
Any progress? Or is this just happening on our tenants?. Any feedback would be appreciated. If not possible to resolve we will stop using session storage alltogether and find a different solution that doesn't break our packages.

**Comment by MarksPoint** [comment]
Just to confirm: we still see these issues frequently in our logs.

**Comment by AJIXuMuK** [comment]
@MarksPoint - it hasn't been deployed yet. We're working on it.

**Comment by AJIXuMuK** [comment]
@TazzyMan @MarksPoint - we made some changes that should be rolled out in the next couple of weeks.
We removed sessionStorage-based caching on navigation items that should decrease the amount of storage used by the product itself.

**Comment by AJIXuMuK** [comment]
This should be rolled out WW by now.
