### ISSUE TITLE
Gulp errors after upgrading SPFx version

### ISSUE THREAD

**Issue by kabdul-rightpoint** [SharePoint/sp-dev-docs#6953]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - Chrome
- SPFx version - 1.10.0
- Node.js version - 10.13.0
- etc

### Issue description

Hello everyone,

 

I'm upgrading my SPFx version in my project from 1.6.0 to 1.10.0 using CLI. I went through all steps that the upgrade task suggested but running into gulp errors. I upgraded my gulp version from 3.9.1 to 4.0.2 but still having issues. The error I get is shown below. Any ideas?

 

Error: More tasks executed then were scheduled.

 

at D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1266:9
at process.removeListener (eval at createNamedFn (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1207:17), <anonymous>:3:41)
at process.on (domain.js:151:13)
at process.emit (events.js:187:15)
at process.EventEmitter.emit (domain.js:442:20)
at _addListener (events.js:211:14)
at process.prependListener [as __zone_symbol__prependListener] (events.js:266:14)
at Object.invokeAddFunc (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1065:48) at ZoneTask.scheduleEventListener [as scheduleFn] (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1092:21)
at ZoneDelegate.scheduleTask (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:255:26)
at Zone.scheduleEventTask (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:171:39)
at zoneAwareAddListener (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1137:14) at D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1266:9
at process.prependListener (eval at createNamedFn (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1207:17), <anonymous>:3:42)
at process.on (domain.js:152:13)
at process.emit (events.js:187:15)
at process.EventEmitter.emit (domain.js:442:20)
at _addListener (events.js:211:14)
at process.prependListener [as __zone_symbol__prependListener] (events.js:266:14)
at Object.invokeAddFunc (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1065:48) at ZoneTask.scheduleEventListener [as scheduleFn] (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1092:21)
at ZoneDelegate.scheduleTask (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:255:26)
at Zone.scheduleEventTask (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:171:39)
at zoneAwareAddListener (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1137:14) at D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1266:9
at process.prependListener (eval at createNamedFn (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1207:17), <anonymous>:3:42)
at process.on (domain.js:152:13)
at process.emit (events.js:187:15)
at process.EventEmitter.emit (domain.js:442:20)
at _addListener (events.js:211:14)
at process.prependListener [as __zone_symbol__prependListener] (events.js:266:14)
at Object.invokeAddFunc (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1065:48) at ZoneTask.scheduleEventListener [as scheduleFn] (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:1092:21)
at ZoneDelegate.scheduleTask (D:\Rightpoint\ACH\ACH-Upgraded-Project\ACH-%20Intranet%20Migration\spark-meganav\node_modules\zone.js\dist\zone-node.js:255:26)
About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1

**Comment by StfBauer** [comment]
Downgrade your gulp version to 3.9.1 - Gulp 4 is not supported in 1.10 as far as I know. Even 1.11 still used 3.9.1 and only partially some were upgraded to 4.0.2.

![image](https://user-images.githubusercontent.com/5503835/115996297-02e84a80-a5df-11eb-84bc-35ac7e7fd2cc.png)

**Comment by andrewconnell** [comment]
> Gulp 4 is not supported in 1.10 as far as I know. Even 1.11 still used 3.9.1 and only partially some were upgraded to 4.0.2.

Just to clarify one thing @StfBauer said... Gulp 4 is supported on Node.js v12+, while Gulp 3 is supported up to Node.js v10. Because SPFx v1.11 is only supported up to Node.js v10, you should only use Gulp 3.9.1 with SPFx v1.11 and below. Future versions of SPFx (v1.12.1+) will require Gulp v4.

You can learn more from the release preview notes here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.1#gulp-versions--nodejs-v12
