### ISSUE TITLE
Uploading file does not work (random) since few weeks

### ISSUE THREAD

**Issue by Dr-Oli** [SharePoint/sp-dev-docs#7002]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint CSOM

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

This is happening in Windows desktop application

### Describe the bug / error

When trying to add file - code is:

Dim fci As Microsoft.SharePoint.Client.FileCreationInformation = New Microsoft.SharePoint.Client.FileCreationInformation
fci.ContentStream = ms
fci.Url = FileRef 'FileRef is location of file
fci.Overwrite = True

dim myWeb As Microsoft.SharePoint.Client.Web = tempContext.Site.OpenWeb(file.weburl)  'file.weburl is site location
Dim docs As Microsoft.SharePoint.Client.List = myWeb.Lists.GetByTitle(file.listtitle) 'file.listtitle is document library name
Dim uploadFile As Microsoft.SharePoint.Client.File = docs.RootFolder.Files.Add(fci)

tempContext.Load(myWeb)
tempContext.Load(docs)
tempContext.Load(uploadFile)
tempContext.ExecuteQuery()

'tempContext is GetWebLoginClientContext

Error message is:
Message: System.NullReferenceException: 'Object reference not set to an instance of an object.'
Source: Microsoft.SharePoint.Client.Runtime
Stack:
   at Microsoft.SharePoint.Client.ClientRequest.BuildQuery()
   at Microsoft.SharePoint.Client.ClientRequest.SetupQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at 

Interestingly this is happening randomly and usually first time when I am trying to process documents. If I, after issue, retry in most cases it will work ok.

Btw. this started to happen recently and only with GetWebLoginClientContext
Beside this error I see, also randomly, 403 error, Stream closed... and they are after retrying working so does not look like a our coding.

### Steps to reproduce

1. Trying with above code to upload document processed locally
2. Retry usually works.

### Expected behavior

This problem is happening 95% only first time when trying to process documents. After retrying it usually works ok.

**Comment by Dr-Oli** [comment]
Quick one - was there any update? Issue is closed but I cannot find any comment on it (except me opening it).
Thx
