### ISSUE TITLE
SPFx Web part does not load in Teams - CORS policy errors

### ISSUE THREAD

**Issue by canturan** [SharePoint/sp-dev-docs#7337]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

Starting from last Friday, the SPFx web part does not load in Teams tab. The same app was working in Teams for a long time, since Friday (no change has been made in the manifest or in the code since two months). 

I am getting two error messages in Teams Tab. First error, when I disabled the cache over DEVTools. Second one without "disableCache" with DEVTools. Most probably Teams cannot find the expected scripts in the cache. 

1. [SPLoaderError.loadComponentError]: Failed to load URL 'https://publiccdn.sharepointonline.com/packsysglobal.sharepoint.com/sites/apps... There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
    at t [as constructor] (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_1d9dd697a4bc2da941600736495c0ac1.js:67:19823)
    at new t (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_1d9dd697a4bc2da941600736495c0ac1.js:68:9374)
    at Function.e.buildErrorWithVerboseLog (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_1d9dd697a4bc2da941600736495c0ac1.js:68:46574)
    at Function.e.buildLoadComponentError (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_1d9dd697a4bc2da941600736495c0ac1.js:68:42619)
    at https://modernb.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_e75d6a10aa75d58591f1.js:1:66020

2. SPLoaderError.loadComponentError]:
Failed to load component "fe7d2b3a-90d6-4946-a131-1082e4606760" (MeetingAppWebPart). Original error: loadComponent() returned an empty object for component
CALLSTACK:
Error
    at t [as constructor] (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_1d9dd697a4bc2da941600736495c0ac1.js:67:19823)
    at new t (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_1d9dd697a4bc2da941600736495c0ac1.js:68:9374)
    at Function.e.buildErrorWithVerboseLog (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_1d9dd697a4bc2da941600736495c0ac1.js:68:46574)
    at Function.e.buildLoadComponentError (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_1d9dd697a4bc2da941600736495c0ac1.js:68:42619)
    at https://modernb.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_e75d6a10aa75d58591f1.js:1:66020

In both cases I am seeing a lot of CORS errors in the console. 
Access to fetch at 'https://publiccdn.sharepointonline.com/xxxxxx.sharepoint.com/sites/apps/ClientSideAssets/webpart.js' from origin 'https://xxxxxx.sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Teams cannot load the SPFx web parts because of the wrong CORS header. All the SPFx web part scripts are blocked. 
![image](https://user-images.githubusercontent.com/13345587/134183277-309fef9d-9c5d-4ce3-8c26-ced60a49ed01.png)

I am seeing this behavior on four different tenants. Hopefully, we can stop this before it spreads to the other tenants. 

The same web part works in SharePoint without any problem. 

### Steps to reproduce

1. Add the SPFx web part as a teams tab. 

### Expected behavior

Expected behavior is  that the web parts loads and the SPFx scripts are not blocked because of wrong CORS policies.

**Comment by canturan** [comment]
After a long debugging, I found the main problem. The main problem was completely different! 

There is a new change in Teams, how Teams loads the theme for the SPFx web parts. The SPFx themeProvider now loads the Teams theme and not the SharePoint theme, where the hostedApp page is. If you were using the __themeState from the window object as a fallback scenario, the __themeState is now undefined and the web part cannot be load, if it is not handled well. 

That brings us to the point that the SPModuleLoader can't load the web part. If the web part is loaded from cache then it is naturally an empty object and the SPModuleLoader throws the error: loadComponent() returned an empty object for component. If the web part does not come from cache then the SPModuleLoader tries to load the web part multiple times and during that the CORS errors appear and the moduleLoader throws the error: There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate. 

That explains the two error messages that I mentioned in my initial post. 

But finally, it is pretty cool that the SPFx themeProvider loads the right themes for Teams (default, dark etc.)! 

The issue does not need any more investigation. By reason of that I am closing the issue.
