### ISSUE TITLE
spfx-controls-react version: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by rafakil** [SharePoint/sp-dev-docs#7367]
Hello,
I get this error when I try to use the controls:
[SPLoaderError.loadComponentError]:
***Failed to load component "6ac657b4-924c-4182-9eba-7f6dacc68b22" .
Original error: ***Failed to load entry point from component "6ac657b4-924c-4182-9eba-7f6dacc68b22".
Original error: Error loading https://component-id.invalid/6ac657b4-924c-4182-9eba-7f6dacc68b22_1.0.0
Cannot read properties of undefined (reading 'call')

***INNERERROR:
***Failed to load entry point from component "6ac657b4-924c-4182-9eba-7f6dacc68b22".
Original error: Error loading https://component-id.invalid/6ac657b4-924c-4182-9eba-7f6dacc68b22_1.0.0
Cannot read properties of undefined (reading 'call')
***CALLSTACK:
Error
at SPLoaderError.SPError [as constructor] (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:10183:24)
at new SPLoaderError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:4211:28)
at Function.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3821:21)
at Function.ErrorBuilder.buildLoadComponentError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3743:21)
at https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:7952:3

Versions:
office-ui-fabric-react versions : 5.131.0
spfx-controls-react version: 1.21.1
SPFx: 1.4
SharePoint 2019 onPrem.

Any idea please?

**Comment by patmill** [comment]
Can you start with posting this to the pnp issues list?  Nothing in the call stack indicated a product specific error at this point.  If the investigations point out a product issue, then please open a bug here with information to diagnose (for example, what the undefined object is that is expected to have a call method, etc.)

**Comment by AJIXuMuK** [comment]
@rafakil - try `gulp trust-dev-cert`
