### ISSUE TITLE
Server-side error adding content type to document library

### ISSUE THREAD

**Issue by keith-knight** [SharePoint/sp-dev-docs#7819]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Assembly: PnP.Framework, Version=1.8.0.0
- Chrome: Version 99.0.4844.74 (Official Build) (64-bit)

### Describe the bug / error

We have been seeing random server-side errors when trying to assign a content type to a document library. At first we noticed this when running c# provisioning code using the PnP provisioning framework but further testing has revealed that the same issue happens when we try to add a content type to a list using the out-of-the-box SharePoint UI.

We get the following error when we try to assign a content type to a library using the list settings page in SharePoint Online.

```
Sorry, something went wrong
An unexpected error has occurred.
Correlation ID: 532b2ca0-e0c6-1000-18eb-f68d045122c8
Date and Time: 3/22/2022 12:30:03 AM
```

We get the following exception when we try to run PnP Provisioning Framework code to assign the same content type to the same library:

```
Exception: Microsoft.SharePoint.Client.ServerException: Value does not fall within the expected range.
[2022-03-22T06:44:26.452Z]    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
[2022-03-22T06:44:26.454Z]    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
[2022-03-22T06:44:26.457Z]    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
[2022-03-22T06:44:26.460Z]    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
[2022-03-22T06:44:26.464Z]    at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
[2022-03-22T06:44:26.467Z]    at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
[2022-03-22T06:44:26.469Z]    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
[2022-03-22T06:44:26.472Z]    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
[2022-03-22T06:44:26.476Z]    at PnP.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ConfigureContentTypes(Web web, List list, ListInstance templateList, Boolean isNewList, PnPMonitoredScope scope, TokenParser parser)
[2022-03-22T06:44:26.481Z]    at PnP.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance templateList, TokenParser parser, PnPMonitoredScope scope, Boolean isNoScriptSite)
[2022-03-22T06:44:26.484Z]    at PnP.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
[2022-03-22T06:44:26.487Z]    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)
[2022-03-22T06:44:26.491Z]    at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
```

It appears to only happen when the content type contains taxonomy fields. If we remove taxonomy fields from the content type then the crash no longer occurs.

This looks like the same issue as these two earlier issues which were closed due to inactivity https://github.com/SharePoint/sp-dev-docs/issues/4438 and also https://github.com/pnp/PnP-Sites-Core/issues/2352

### Steps to reproduce

1. Provision site columns and a content type where the content type contains a taxonomy field.
2. Create a new document library.
3. Attempt to add the content type to the document library using the out-of-the-box list settings page (or using the PnP provisioning framework).

### Expected behavior

The content type should be associated with the list.

**Comment by keith-knight** [comment]
I can also confirm that the issue also happens with the REST API - e.g.

`https://our-tenancy.sharepoint.com/sites/test-site/_api/web/lists('9D1A673B-D936-47CE-8208-E6F4F558BF2D')/contenttypes/addAvailableContentType('0x010100DE581657DB3B459E99E2BE295CFD64FB')`

The following error is returned:

`{"odata.error":{"code":"-2147024809, System.ArgumentException","message":{"lang":"en-US","value":"Value does not fall within the expected range."}}}
`

When we send the same request with a different content type ID (e.g. one of the out-of-the-box ones like '0x0101009D1CB255DA76424F860D91F20E6C4118002A50BFCFB7614729B56886FADA02339B') the request succeeds and the content type is added to the library.

**Comment by keith-knight** [comment]
An update on this one - it appears to be a bug in the PnP Provisioning framework.

Occasionally when our provisioning script is run, the token substitution is not performed for the list id of the taxonomy hidden list. The result is a site column deployed with the following value in its schema (instead of having the list id as expected):

`List="{{listid:TaxonomyHiddenList}}"`

I am assuming that it could be that because we are running our script in a new site (which is also created programmatically) - and that the taxonomy hidden list itself may not have been provisioned yet by SharePoint at the time we run our script.

We can hopefully work around it by adding some code to check for the existence of the hidden list before we run our script.
