### ISSUE TITLE
[SPFx 1.15.0-beta.1] package-solution fails when elements.xml file is referenced from external folder and sharepoint/assets doesn't exist

### ISSUE THREAD

**Issue by nse7ens** [SharePoint/sp-dev-docs#7826]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.15.0-beta.1

### Describe the bug / error

While working in a monorepo, we reference our `elements.xml` feature files to be included in the .sppkg package from another project in the monorepo.

When running `gulp package-solution` this task fails when there is no `sharepoint/assets` folder in the project the command is run.

PS: follow-up on fixes in #7689

#### Project structure
```
<root>
├───apps
│   └───demoapp
│       ├───config
│       │   ├───package-solution.json
│       │   └───...
│       ├───gulpfile.js
│       └───...
├───node_modules
│   └───@mycompany
│       └───appcustomizer
│           └───...
├───packages
│   └───appcustomizer
│       ├───config
│       ├───sharepoint
│       │   └───assets
│       │       └───elements.xml
│       └───src
└───package.json
```

#### apps/demoapp/config/package-solution.json
```
{
	"$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
	"solution": {
		"name": "connect-demo",
		"id": "054bb688-3365-4121-ad60-e870f10518cb",
		"version": "1.1.0.0",
		"includeClientSideAssets": true,
		"skipFeatureDeployment": true,
		...
		"features": [
			{
				"title": "App Components",
				"description": "...",
				"id": "...",
				"version": "1.1.0.0",
				"assets": {
					"elementManifests": ["@mycompany/appcustomizer/sharepoint/assets/elements.xml"]
				}
			}
		]
	},
	"paths": {
		"zippedPackage": "solution/demoapp.sppkg"
	}
}
```

#### Behaviour
Running this:
```bash
cd apps/demoapp
gulp package-solution
```

... returns with this error message:

```
[12:10:26] [package-solution] Normalizing solution information...
[12:10:26] [package-solution] Attempting creating component definitions for {9} manifests
[12:10:26] [package-solution] Created component definitions for {9} manifests
[12:10:26] [package-solution] feature.componentIds not set! Adding all [9] components to feature { App Components }.
[12:10:26] Error - [package-solution]
[12:10:26] Error - [package-solution] Error: File does not exist: C:\<root>\apps\demoapp\sharepoint
ENOENT: no such file or directory, lstat 'C:\<root>\apps\demoapp\sharepoint'
    at Object.realpathSync (fs.js:1646:7)
    at C:\<root>\node_modules\@rushstack\node-core-library\lib\FileSystem.js:903:24
    at Function._wrapException (C:\<root>\node_modules\@rushstack\node-core-library\lib\FileSystem.js:1034:20)
    at Function.getRealPath (C:\<root>\node_modules\@rushstack\node-core-library\lib\FileSystem.js:902:27)
    at Function.resolveModule (C:\<root>\node_modules\@rushstack\node-core-library\lib\Import.js:146:60)
    at resolveFeatureFile (C:\<root>\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\packageSolutionPlugin\packageSolution\utils\normalizeSolutionDefinition.js:234:43)
    at C:\<root>\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\packageSolutionPlugin\packageSolution\utils\normalizeSolutionDefinition.js:226:40
    at Array.map (<anonymous>)
    at resolveFeatureFiles (C:\<root>\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\packageSolutionPlugin\packageSolution\utils\normalizeSolutionDefinition.js:226:22)
    at normalizeSolutionDefinition (C:\<root>\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\packageSolutionPlugin\packageSolution\utils\normalizeSolutionDefinition.js:210:47)
[12:10:26] Error - 'package-solution' sub task errored after 178 ms
 File does not exist: C:\<root>\apps\demoapp\sharepoint
ENOENT: no such file or directory, lstat 'C:\<root>\apps\demoapp\sharepoint'
```

**Comment by AJIXuMuK** [comment]
@NickSevens thanks for the follow up!
So, just to confirm, if you add empty folder - it starts working, correct?

Could you please provide some basic sample so I could work on it?

Thanks!

**Comment by NickSevens** [comment]
@AJIXuMuK I've created a demo repo at https://github.com/NickSevens/issue-sp-dev-docs-7826

#### Steps to reproduce

1. Create a new SPFx project
2. Add an `elements.xml` file **not** in the `sharepoint/assets` directory (e.g. in the root of the project, or basically anywhere else)
3. Reference the `elements.xml` file in `package-solution.json`
4. (make sure no `sharepoint/assets` folder exists)
5. Run `gulp bundle` and `gulp package-solution`

**Comment by AJIXuMuK** [comment]
@NickSevens - thanks for the sample.
The fix is done. Unfortunately, we will not include it in the next beta (should be released next week). But we will include it in the beta after next :)

Your configuration will work after the change.
Additionally, you will be able to provide `sharepointAssetDir` property in the `package-solution.json` (relative to `packageDir`).

**Comment by AJIXuMuK** [comment]
@NickSevens - this should be a part of released rc.0.
