### ISSUE TITLE
Intercepting Query String Change breaks SharePoint navigation

### ISSUE THREAD

**Issue by DevYak** [SharePoint/sp-dev-docs#7958]
### Scenario
Implementing a simple React SPFx app to intercept query strings and maintain back/forward history.

### Issue
I have implemented the code from this document and it works well as long as you stay within the page where the web part is located. The moment you click any other link within the current SharePoint site, the navigation is broken. You can see the URL update but the page content doesn't load or update. If you try to click any other link it throws an error, and of course, no content loads.

**Error message**
It throws this error:

> Uncaught TypeError: Cannot read properties of undefined (reading 'domElement')
>     at t.get (sp-pages-assembly_en-us_0f75c67cd29bce02cfc7272e579bc1fb.js:71:286967)
>     at t.render (web-part_6fd793b42f656085c9f3.js:2:520896)
>     at t._onUrlChange (web-part_6fd793b42f656085c9f3.js:2:520761)
>     at History.a.pushState (web-part_6fd793b42f656085c9f3.js:2:520284)
>     at sp-pages-assembly_en-us_0f75c67cd29bce02cfc7272e579bc1fb.js:71:981210
>     at Object.confirmTransitionTo (sp-pages-assembly_en-us_0f75c67cd29bce02cfc7272e579bc1fb.js:71:924487)
>     at Object.G [as push] (sp-pages-assembly_en-us_0f75c67cd29bce02cfc7272e579bc1fb.js:71:981127)
>     at sp-pages-assembly_en-us_0f75c67cd29bce02cfc7272e579bc1fb.js:71:986492

In the documentation, I logged the path in the _onUrlChange method:
```
  private _onUrlChange(newpath = window.location.search): void {
    // any logic you might want to trigger when the query string updates
    // e.g. fetching data
    console.log(newpath)
    this.render();
  }
```

The render method is a little different than the documentation but standard React SPFx boilerplate:
```
  public render(): void {
    const element: React.ReactElement<WebPartProps> = React.createElement(
      WebPart,
      {
        description: this.properties.description
      }
    );
    ReactDom.render(element, this.domElement);
  }
```

I notice that when I click to navigate elsewhere in the current SharePoint site, my custom SPFx web part will log the new path. For instance, if my web part is located on "/sites/SiteName/SitePages/Page.aspx" and I click to go home, it will log the path "/sites/SiteName" in the console.

I assume it will then try to run `this.render()`, but of course, we are no longer on a page with that web part so it throws that error 

> Cannot read properties of undefined (reading 'domElement').

I also notice that if I continue to navigate throughout the site, even on standard SP pages (no custom SPFx), it will continue to throw the same error as well as log the path (so `this._onUrlChange()` keeps getting triggered even as I navigate on standard pages)

The issue resolves itself if I hard refresh.

### Possible solution?
Perhaps add a condition to not run the `this._onUrlChange` on Dispose? It's not disposing properly or something in the code is preventing default behaviour? I'm not sure how to solve this issue and guidance would be appreciated.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9907ffa7-f129-9b96-d59f-29a060433769
* Version Independent ID: c0c5d82a-a8a6-a44c-81c8-daa47e457ebc
* Content: [Intercepting Query String Changes in Web Parts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/intercepting-query-changes-in-webparts)
* Content Source: [docs/spfx/web-parts/guidance/intercepting-query-changes-in-webparts.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/intercepting-query-changes-in-webparts.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **bekaise**

**Comment by AJIXuMuK** [comment]
@DevYak - thanks for reporting that.
Your proposal is correct - we need to add `onDispose` example in the docs to revert `pushState` changes back.

**Comment by vinaykumarkn** [comment]
@DPCamino  same error we are facing how u resolve above error ?

**Comment by DPCamino** [comment]
> @DPCamino same error we are facing how u resolve above error ?

Sorry I can't be of any assistance. This was some time ago and have since implemented a router package instead to handle routing.
