### ISSUE TITLE
1.15 asset files not found in subdirectories

### ISSUE THREAD

**Issue by trueleader** [SharePoint/sp-dev-docs#8268]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx 1.15.0
- Node.js 14.19.0 / 16.15.1
- rush-stack-compiler-4.5 0.2.2
- typescript 4.5.5

### Describe the bug / error

My solution contains many assets in subdirectories.
After upgrading:
- SPFx from v1.14.0 to 1.15.0
- Typescript from 4.2.4 to 4.5.5
- rush-stack-compiler-4.2 to 4.5

the assets inside the subdirectory are not found any more.
Updating Node from 14.19.0 to 16.15.1 doesn´t change the behavior.

```
...
[13:33:09] Finished subtask 'configure-webpack' after 540 ms
[13:33:09] Starting subtask 'webpack'...
[13:33:45] Finished subtask 'webpack' after 36 s
[13:33:45] Finished 'bundle' after 49 s
[13:33:46] ==================[ Finished ]==================
[13:33:46] Project gremlin-app version:1.4.2
[13:33:46] Build tools version:3.17.19
[13:33:46] Node version:v16.15.1
[13:33:46] Total duration:53 s
Build target: SHIP
[13:33:50] Using gulpfile C:\Projects\DLH-Gremlin\frontend\gulpfile.js
[13:33:50] Starting 'package-solution'...
[13:33:50] Starting gulp
[13:33:50] Starting subtask 'package-solution'...
[13:33:50] [package-solution] Found manifest: d0ec8b24-aaed-4887-98bd-ca211f0d2df7.manifest.json
[13:33:50] [package-solution] Found client-side build resource: AttachmentsStrings_de-de_41b37811bcc79ecf4a77a747941bab64.js
[13:33:50] [package-solution] Found client-side build resource: AttachmentsStrings_en-us_7578bcfc2aa5089904319a9d3e401f92.js
[13:33:50] [package-solution] Found client-side build resource: ControlStrings_bg-bg_563ca021db63b04d5f0a11a1057f4651.js
...
[13:33:50] [package-solution] Found teams icons: d0ec8b24-aaed-4887-98bd-ca211f0d2df7_outline.png
[13:33:50] [package-solution] Verifying configuration...
[13:33:50] [package-solution] Done!
[13:33:50] [package-solution]
[13:33:50] [package-solution] Normalizing solution information...
[13:33:50] [package-solution] Attempting creating component definitions for {1} manifests
[13:33:50] [package-solution] Created component definitions for {1} manifests
[13:33:50] [package-solution] feature.componentIds not set! Adding all [1] components to feature { Gremlin Structure }.
[13:33:50] Error - [package-solution]
[13:33:50] Error - [package-solution] Error: Cannot find module "initial\Lists\AgendaItemAdditionsSchema.xml" from "C:\Projects\DLH-Gremlin\frontend/sharepoint/assets".
    at Function.resolveModule (C:\Projects\DLH-Gremlin\frontend\node_modules\@microsoft\spfx-heft-plugins\node_modules\@rushstack\node-core-library\lib\Import.js:176:19)
    at resolveFeatureFile (C:\Projects\DLH-Gremlin\frontend\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\packageSolutionPlugin\packageSolution\utils\normalizeSolutionDefinition.js:247:43)
    at C:\Projects\DLH-Gremlin\frontend\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\packageSolutionPlugin\packageSolution\utils\normalizeSolutionDefinition.js:231:40
    at Array.map (<anonymous>)
    at resolveFeatureFiles (C:\Projects\DLH-Gremlin\frontend\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\packageSolutionPlugin\packageSolution\utils\normalizeSolutionDefinition.js:231:22)
    at normalizeSolutionDefinition (C:\Projects\DLH-Gremlin\frontend\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\packageSolutionPlugin\packageSolution\utils\normalizeSolutionDefinition.js:214:43)
    at createPackage (C:\Projects\DLH-Gremlin\frontend\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\packageSolutionPlugin\packageSolution\createPackage.js:36:51)
    at SolutionPackager.packageSolutionAsync (C:\Projects\DLH-Gremlin\frontend\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\packageSolutionPlugin\SolutionPackager.js:190:43)
    at async PackageSolutionTask.executeTask (C:\Projects\DLH-Gremlin\frontend\node_modules\@microsoft\sp-build-core-tasks\lib\packageSolution\PackageSolutionTask.js:20:9)
[13:33:50] Error - 'package-solution' sub task errored after 138 ms
 Cannot find module "initial\Lists\AgendaItemAdditionsSchema.xml" from "C:\Projects\DLH-Gremlin\frontend/sharepoint/assets".
[13:33:50] 'package-solution' errored after 181 ms
[13:33:50]
About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1
```

### Steps to reproduce

1. Sharepoint assets inside folders: 
![image](https://user-images.githubusercontent.com/7026107/177160365-f967a982-a77e-4fff-b2d3-475ae7a26e40.png)

2. config/package-solution.json:
```
{
    "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
    "solution": {
        ...
        "features": [
            {
                "title": "Gremlin Structure",
                "description": "Fields, ContentTypes and Lists of Gremlin",
                "id": "e4eb077e-2d96-4b5a-bebe-1f978017bb97",
                "version": "1.4.0.5",
                "assets": {
                    "elementManifests": [
                        "initial/Fields.xml",
                        "initial/ContentTypes.xml",
                        "initial/Lists/AgendaItemAdditionsInstance.xml",
                        ...
                    ],
                    "elementFiles": [
                        "initial/Lists/AgendaItemAdditionsSchema.xml",
                        "initial/Lists/AgendaItemsSchema.xml",
                        ...
                    ],
                    "upgradeActions": [
                        "v1.1.0/Migration_v1.1.0.xml",
                        ...
                    ]
                }
            }
        ]
    },
    "paths": {
        "zippedPackage": "solution/gremlin-app.sppkg"
    }
}
```

3. npm run dist

### Expected behavior

Getting a .sppkg file after npm run dist

**Comment by AJIXuMuK** [comment]
Thank you @trueleader for reporting this one!
The fix has been made and will be included in the next released version of the SPFx.

**Comment by AJIXuMuK** [comment]
1.15.2 is out - this should be fixed

**Comment by trueleader** [comment]
Update is working, thx :)
