### ISSUE TITLE
CDN errors for SPFX components

### ISSUE THREAD

**Issue by marcusroberts** [SharePoint/sp-dev-docs#8270]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

Our SPFX components on one tenant have started to fail to load from the CDN.   Instead we see a whole load of 406 errors.

Publishing new versions of the SPFX with a new version number doesn't help.

Once we disable the Public CDN it all works again

`[SPLoaderError.loadComponentError]:
Failed to load component "e2bcf8c2-43a1-4928-8700-5106dd2ec654" (AtveroWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/xxx.sharepoint.com/sites/appcatalog/ClientSideAssets/3c8e3737-7e30-4f24-9e0b-2cac46cbe339/atvero-web-part_bdbd165032baf2238e58.js' for resource 'atvero-web-part' in component 'e2bcf8c2-43a1-4928-8700-5106dd2ec654' (AtveroWebPart). There was an error requesting the file.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/xxx.sharepoint.com/sites/appcatalog/ClientSideAssets/3c8e3737-7e30-4f24-9e0b-2cac46cbe339/atvero-web-part_bdbd165032baf2238e58.js' for resource 'atvero-web-part' in component 'e2bcf8c2-43a1-4928-8700-5106dd2ec654' (AtveroWebPart). There was an error requesting the file.
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6b3ba9b92f0aab063b870bb4542f59a7.js:70:214899)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6b3ba9b92f0aab063b870bb4542f59a7.js:71:7680)
    at e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6b3ba9b92f0aab063b870bb4542f59a7.js:71:44944)
    at e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6b3ba9b92f0aab063b870bb4542f59a7.js:71:41035)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_dc58eaaa7aaff14eda18.js:1:6012`

### Steps to reproduce

Enable Public CDN on the tenant.

### Expected behavior

On other tenants and this tenant until Friday, the SPFX components were loading as expected from the CDN.

**Comment by marcusroberts** [comment]
I think this is a duplicate of #8261  sorry.
