### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)

### ISSUE THREAD

**Issue by pmeripe** [SharePoint/sp-dev-docs#8800]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

![image](https://user-images.githubusercontent.com/38794321/222005522-ea224e77-60a2-47fb-a1b0-031bf80280c1.png)

### Describe the bug / error

Error:

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\SPFx\LAMetroPCC\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\SPFx\LAMetroPCC\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\SPFx\LAMetroPCC\node_modules\@microsoft\gulp-core-build-sass\lib\SassTask.js:12:18)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)

### Steps to reproduce

1. Installed Node.js version 16.17.1
2.
3.

### Expected behavior

Thought I could use latest version of node js

**Comment by StfBauer** [comment]
What does the package.json from your project look like? It seems like you have SPFx 1.12.1 installed.

**Comment by pmeripe** [comment]
> 

"dependencies": {
    "@fluentui/react": "^8.22.2",
    "@microsoft/sp-core-library": "1.12.1",
    "@microsoft/sp-lodash-subset": "1.12.1",
    "@microsoft/sp-office-ui-fabric-core": "1.12.1",
    "@microsoft/sp-property-pane": "1.12.1",
    "@microsoft/sp-webpart-base": "1.12.1",
    "@pnp/graph": "^2.15.0",
    "@pnp/sp": "^2.15.0",
    "office-ui-fabric-react": "7.156.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-excel-renderer": "^1.1.0",
    "sass": "^1.58.3",
    "semantic-ui-react": "^1.3.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.7": "0.2.3",
    "@microsoft/sp-build-web": "1.12.1",
    "@microsoft/sp-module-interfaces": "1.12.1",
    "@types/react": "16.9.36",
    "@types/react-dom": "16.9.8",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "gulp": "~4.0.2"
  }

**Comment by AJIXuMuK** [comment]
@pmeripe SPFx 1.12.1 doesn't support node v16.
Please, take a look at the [compatibility table](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/compatibility).
You should use node v10, v12, or v14.

**Comment by pmeripe** [comment]
Hi Alex,

Thanks for your reply. So If I want to upgrade all to latest, what are the steps?

**Comment by AJIXuMuK** [comment]
I would recommend using [CLI for Microsoft 365](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-upgrade/) to upgrade the project correctly to the latest version.

**Comment by pmeripe** [comment]
Thanks Alex. I downgraded Node.js to 14.21.3 and tried to fix other errors. But still I get webpart error.
Please help!

![image](https://user-images.githubusercontent.com/38794321/222256654-b91271f4-232d-4865-a46e-e78d2b8ae61a.png)
