### ISSUE TITLE
SPFX 1.16.1 - React import issue (node v16.17.0)

### ISSUE THREAD

**Issue by varunssis** [SharePoint/sp-dev-docs#8823]
In the process of developing a List View Command set using scaffolding provided by  yo @microsoft/sharepoint

just by adding this line to the default .ts file at the top near other import statements:

`import * as React from 'react';`

causes the following error when debugging using Edge developer tools on a SharePoint document library page:
```
listview-host-assembly_en-us_4aca07e33375188b33b9dac5c05ea8d7.js:68 
        
       Could not load setret-command-set in require. Trying in system.js. TypeError: Cannot read properties of undefined (reading 'id')
    at listview-host-assembly_en-us_4aca07e33375188b33b9dac5c05ea8d7.js:68:328939
    at new Promise (<anonymous>)
    at e.loadComponent (listview-host-assembly_en-us_4aca07e33375188b33b9dac5c05ea8d7.js:68:328907)
    at listview-host-assembly_en-us_4aca07e33375188b33b9dac5c05ea8d7.js:68:330668
    at async Promise.all (/sites/CWC-R-ICT/Shared%20Documents/Forms/index 0)
(anonymous) @ listview-host-assembly_en-us_4aca07e33375188b33b9dac5c05ea8d7.js:68
AllItems.aspx:1 
        
       Uncaught (in promise) Error
    at t [as constructor] (listview-host-assembly_en-us_4aca07e33375188b33b9dac5c05ea8d7.js:3:209583)
    at new t (listview-host-assembly_en-us_4aca07e33375188b33b9dac5c05ea8d7.js:68:271957)
    at e.buildErrorWithVerboseLog (listview-host-assembly_en-us_4aca07e33375188b33b9dac5c05ea8d7.js:68:309241)
    at e.buildLoadComponentError (listview-host-assembly_en-us_4aca07e33375188b33b9dac5c05ea8d7.js:68:305332)
    at chunk.systemjs-component-loader_en-us_a8c57c27bfe2e3f49312.js:1:6036
```

and removing the import statement loads the command buttons fine.

My package.json looks like this:
```
{
  "name": "rs",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=16.13.0 <17.0.0"
  },
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "tslib": "2.3.1",
    "@microsoft/sp-core-library": "1.16.1",
    "@microsoft/decorators": "1.16.1",
    "@microsoft/sp-listview-extensibility": "1.16.1",
    "@microsoft/sp-dialog": "1.16.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-4.5": "0.2.2",
    "@rushstack/eslint-config": "2.5.1",
    "@microsoft/eslint-plugin-spfx": "1.16.1",
    "@microsoft/eslint-config-spfx": "1.16.1",
    "@microsoft/sp-build-web": "1.16.1",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "gulp": "4.0.2",
    "typescript": "4.5.5",
    "@microsoft/sp-module-interfaces": "1.16.1"
  }
}
```
My intention is to use the React import to load a panel:
```
//   const _showPanel = (props: IStatefulPanelProps): void => {
  //     **ReactDOM.render(**
  //       React.createElement(StatefulPanel, props),
  //       this.panelPlaceHolder
  //     );
  //   };
```
The code is based on a sample here: https://github.com/kkazala/spfx-Panel/blob/main/src/extensions/panel/PanelCommandSet.ts 

_Is importing react no longer supported, if not is this a known issue and is there a fix available for this please or am I missing something?_

**Comment by AJIXuMuK** [comment]
@varunssis please add dependencies to react and react-dom version 17.0.1 and appropriate typings.
It will solve the issue.
