### ISSUE TITLE
SPFX 1.17 PopupFlow

### ISSUE THREAD

**Issue by danielcostalvt** [SharePoint/sp-dev-docs#8881]
Hi all,

Cannot make this popup flow work in anyway, here is the code I'm using:
const tokenProvider = await this.context.aadTokenProviderFactory.getTokenProvider();

    const spEventObserver:ISPEventObserver = { componentId: this.componentId, instanceId:this.instanceId, isDisposed:false, dispose:null};

    tokenProvider.onBeforeRedirectEvent.add(spEventObserver, (eventArgs: IBeforeRedirectEventArgs) =>{

      eventArgs.cancel();

    })

   
      tokenProvider.popupEvent.add(spEventObserver, (eventArgs: IPopupEventArgs) =>

      { eventArgs.requestPopup(); eventArgs.showPopup(); })

      return await tokenProvider.getToken(reachResourceUrl);  

What am I doing wrong?

**Comment by SharePickle** [comment]
Bumping, I've followed [instructions](https://github.com/andrewconnell/sp-dev-docs/blob/content-new/aadtokenprovider-popup/docs/spfx/use-aadtokenprovider.md) but its still redirecting.
Debugging `AADHttpClient` I can see `popupEvent` is registered correctly, but it's never called, `onBeforeRedirect` event is called instead.
Running `Get-SPOTenant` shows that `IsEnableAppAuthPopupEnabled` is set to `true`.

**Comment by AJIXuMuK** [comment]
@danielcostalvt @SharePickle - we identified an issue and working on the fix.
If no unpredicted things happen it should be rolled out WW in about 2-3 weeks.

**Comment by glyn-clough-wm-reply** [comment]
Any update on this @AJIXuMuK ?

**Comment by AJIXuMuK** [comment]
@glyn-clough-wm-reply - sorry for the silence.
The fix should be rolled out globally.

Could you please check if you're still experiencing the issue?

**Comment by glyn-clough-wm-reply** [comment]
Many thanks - we'll try and test this out over the next few days and provide an update.

Can I just check - is this the Microsoft recommended approach to access AD secured API's, when there is ITP blocking the usual authentication methods? (As that's the challenge we're trying to solve)

**Comment by AJIXuMuK** [comment]
@glyn-clough-wm-reply - yes, we recommend this approach for SPFx solutions.

**Comment by danielcostalvt** [comment]
@AJIXuMuK : will try it out and provide some feedback.
My question though, if we have multiple web parts consuming different APIs, we will have a never ending appearance of popups, correct?

Can we get some insight if there is any plan on removing the cookie dependency of authentication alltogether in the future?

**Comment by SharePickle** [comment]
The popup shows up, but nothing happens (error says `cannot read measage of undefined` in console). Also if you try get token again it says is `Token request previously failed.`

**Comment by AJIXuMuK** [comment]
@SharePickle could you please share the console errors and also correlation id from requests (request-id header value) for failing requests?

**Comment by SharePickle** [comment]
Here's my setup:

```ts

  // configure popup
  onInit() {
    return this.context.aadTokenProviderFactory.getTokenProvider()
      .then(configurableTokenProvider => {
        configurableTokenProvider.popupEvent.add(this, this.handlePopup);
        this._tokenProvider = configurableTokenProvider;
      })
      .catch(e => console.error(e));
  }

  handlePopup = (eventArgs: PopupEventArgs) => {
    eventArgs.cancel();     // REQUIRED: to cancel the default popup that is called to open
    eventArgs.showPopup();  // initiate the popup flow
  }

  getToken = async () => {
    const token = await this._tokenProvider.getToken('https://graph.microsoft.com')
  }
```
The web part is just a simple button which calls `getToken` method.

When I click the first time - popup shows up, but nothing happens.

When I was debugging `cannot read measage of undefined` I found it caused by this method (argument `e` is `undefined`):

![image](https://github.com/SharePoint/sp-dev-docs/assets/32567749/72d8e715-d517-406b-bfe2-1678f0a07598)

When I click the button second time nothing happens at all, but if I debug again the error message is caught internally and it says `Token request previously failed.`.

```js
Error: Token request previously failed
    at new t (chunk.aadTokenProvider_en-us_fee8ad587b68c8265bea.js:1:1754)
    at e._getTokenInternal (chunk.aadTokenProvider_en-us_fee8ad587b68c8265bea.js:1:3807)
    at e.getToken (chunk.aadTokenProvider_en-us_fee8ad587b68c8265bea.js:1:2612)
    at sp-pages-assembly_en-us_c362cb7e1934defdf3d1046262075d28.js:78:169616
```

![image](https://github.com/SharePoint/sp-dev-docs/assets/32567749/117e624b-92e7-4020-9a9a-6a3d7e78901e)

If I refresh the page and click button again - token loads successfully.

**Comment by glyn-clough-wm-reply** [comment]
Hi @AJIXuMuK  - any update on this? Do you need anything else from @SharePickle ?

**Comment by danielcostalvt** [comment]
hi @AJIXuMuK / @VesaJuvonen can we get an answer on:
My question though, if we have multiple web parts consuming different APIs, we will have a never ending appearance of popups, correct?

Can we get some insight if there is any plan on removing the cookie dependency of authentication alltogether in the future?

**Comment by SharePickle** [comment]
@AJIXuMuK hey sorry to ping you so often, but is there anything you guys found out?
Now I'm getting other error:
```
Uncaught (in promise) ClientAuthError: User cancelled the flow.
    at t [as constructor] (chunk.vendors~msalImplicit~msalImplicitLegacy_none_98fce48cd7ca5bbe0433.js:1:8320)
    at new t (chunk.vendors~msalImplicit~msalImplicitLegacy_none_98fce48cd7ca5bbe0433.js:1:8879)
    at t.createUserCancelledError (chunk.vendors~msalImplicit~msalImplicitLegacy_none_98fce48cd7ca5bbe0433.js:1:10209)
    at chunk.vendors~msalImplicit~msalImplicitLegacy_none_98fce48cd7ca5bbe0433.js:1:41370
```

**Comment by Dalf10** [comment]
Is there any update on this?
I also need to be able to handle AAD authentication when silentsso gets blocked by the browser
