### ISSUE TITLE
SPFx 1.17.1 - pdf.js

### ISSUE THREAD

**Issue by necik11** [SharePoint/sp-dev-docs#8896]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
  - Chrome 112.0.5615.86
- SPFx version
  - 1.17.1  
- Node.js version
  - v16.14.1

### Issue description

Following on from expanding the [custom dialog box](https://github.com/SharePoint/sp-dev-docs/issues/8895), I would like to display the pdf using pdf-js:

1.  For repair dialog:
- `npm i react@17.0.1 react-dom@17.0.1 @types/react@17.0.45 @types/react-dom@17.0.17 --save-exact`
2.  Install pdf-js:
- `npm install pdfjs-dist --save-dev`
4. Create compo
-
```
import { useEffect, useRef, useState, useCallback } from "react";
import * as React from "react";
// import pdfjsWorker from "pdfjs-dist/build/pdf.worker.entry";
// import * as pdfjsLib from "pdfjs-dist";
import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.js";
export default function CustomPdfReader() {
    const url = "https://cors-anywhere.herokuapp.com/http://www.pdf995.com/samples/pdf.pdf";
    const canvasRef = useRef();
    const [pdfRef, setPdfRef] = useState("");
    const currentPage = 1;
    const zoomScale = 1;
    const rotateAngle = 0;
    useEffect(() => { pdfjsLib.GlobalWorkerOptions.workerSrc = "https://unpkg.com/pdfjs-dist@3.5.141/build/pdf.worker.min.js"; });
    const renderPage = useCallback(
        (pageNum, pdf = pdfRef) => {
            pdf &&
                pdf.getPage(pageNum).then(function (page: any) {
                    const viewport = page.getViewport({ scale: zoomScale, rotation: rotateAngle });
                    const outputScale = window.devicePixelRatio || 1;
                    const canvas = document.getElementById("pdf-doc") as HTMLCanvasElement;
                    const context = canvas.getContext("2d");
                    canvas.width = Math.floor(viewport.width * outputScale);
                    canvas.height = Math.floor(viewport.height * outputScale);
                    canvas.style.width = Math.floor(viewport.width) + "px";
                    canvas.style.height = Math.floor(viewport.height) + "px";
                    const transform = outputScale !== 1
                        ? [outputScale, 0, 0, outputScale, 0, 0]
                        : null;
                    const renderContext = {
                        canvasContext: context,
                        transform: transform,
                        viewport: viewport,
                        textContent: pdfRef
                    };
                    page.render(renderContext);
                });
        },
        [pdfRef, url]
    );
    useEffect(() => {
        if (url.slice(-4).toLowerCase() === ".pdf") {
            renderPage(currentPage, pdfRef);
        } else {
            setPdfRef("");
        }
    }, [pdfRef, renderPage, url]);
    useEffect(() => {
        const loadingTask = pdfjsLib.getDocument(url);
        loadingTask.promise.then(
            (loadedPdf: any) => {
                setPdfRef(loadedPdf);
            },
            function (reason: any) {
                console.error(reason);
            }
        );
    }, [url]);
    return (
        <div>
            <canvas id="pdf-doc" ref={canvasRef} />
        </div>
    );
}
```
5. Add pdf reader to customDialog.tsx:
6.  But then i got error:

```
[11:17:50] Error - [webpack] 'dist':
./node_modules/pdfjs-dist/legacy/build/pdf.js 4380:33
Module parse failed: Unexpected token (4380:33)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const httpHeaders = src.httpHeaders || null;
|   const withCredentials = src.withCredentials === true;
`>`   const password = src.password ?? null;
|   const rangeTransport = src.range instanceof PDFDataRangeTransport ? src.range : null;
|   const rangeChunkSize = Number.isInteger(src.rangeChunkSize) && src.rangeChunkSize > 0 ? src.rangeChunkSize : DEFAULT_RANGE_CHUNK_SIZE;
 @ ./lib/components/CustomPdfReader.js 5:0-59 13:28-56 47:26-46
 @ ./lib/components/CustomDialog.js
 @ ./lib/extensions/helloWorld/HelloWorldCommandSet.js
```

7. So i found this:
- [Issue1](https://github.com/mozilla/pdf.js/issues/13200)
- [Issue2](https://github.com/wojtekmaj/react-pdf/issues/1043)
Everywhere is result: Update to webpack 5 it should solve this issue. or workaround change webpack:
8. So i go spfx :
- [Extending Webpack in the SharePoint Framework toolchain](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/extending-webpack-in-build-pipeline)
gulpfile.js
```

build.configureWebpack.mergeConfig({
  additionalConfiguration: (generatedConfiguration) => {
    generatedConfiguration.module.rules.push(
      {
        test: /\.js$/,
        exclude: /node_modules(?!(\/|\\)pdfjs-dist)/,
        loader: 'babel-loader',
        options: {
          'presets': ['@babel/preset-env'],
          'plugins': ['@babel/plugin-proposal-optional-chaining']
        }
      }
    );
    return generatedConfiguration;
  }
});
```
not help so i got next error:
```
[11:50:14] Error - [webpack] 'dist':
./lib/extensions/helloWorld/HelloWorldCommandSet.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: this.getOptions is not a function
    at Object.loader (C:\github\spfx-pdfjs\spfx-pdfjs\node_modules\babel-loader\lib\index.js:46:28)
    at Object.<anonymous> (C:\github\spfx-pdfjs\spfx-pdfjs\node_modules\babel-loader\lib\index.js:41:12)
```
and i am again back:
[next issue](https://github.com/webpack-contrib/style-loader/issues/517)
**You need webpack v5 to use the latest version of style-loader, please read changelog**
```
spfx-pdfjs@0.0.1 C:\github\spfx-pdfjs\spfx-pdfjs
├─┬ @microsoft/sp-build-web@1.17.1
│ ├─┬ @microsoft/gulp-core-build-webpack@5.2.30
│ │ └─┬ webpack@4.44.2
│ │   └─┬ terser-webpack-plugin@1.4.5
│ │     └── webpack@4.44.2 deduped
│ ├─┬ @microsoft/sp-build-core-tasks@1.17.1
│ │ ├─┬ @microsoft/spfx-heft-plugins@1.17.1
│ │ │ ├─┬ @microsoft/sp-css-loader@1.17.1
│ │ │ │ └─┬ webpack@4.44.2
│ │ │ │   └─┬ terser-webpack-plugin@1.4.5
│ │ │ │     └── webpack@4.44.2 deduped
│ │ │ ├─┬ @rushstack/set-webpack-public-path-plugin@3.3.91
│ │ │ │ ├─┬ @rushstack/webpack-plugin-utilities@0.1.56
│ │ │ │ │ └── webpack@5.79.0 deduped
│ │ │ │ └── webpack@5.79.0 deduped
│ │ │ ├─┬ @rushstack/webpack4-localization-plugin@0.17.2
│ │ │ │ └── webpack@4.44.2 deduped
│ │ │ ├─┬ @rushstack/webpack4-module-minifier-plugin@0.9.40
│ │ │ │ └── webpack@4.44.2 deduped
│ │ │ ├─┬ copy-webpack-plugin@6.0.4
│ │ │ │ └── webpack@5.79.0 deduped
│ │ │ ├─┬ css-loader@3.4.2
│ │ │ │ └── webpack@5.79.0 deduped
│ │ │ ├─┬ file-loader@6.1.0
│ │ │ │ └── webpack@5.79.0 deduped
│ │ │ ├─┬ postcss-loader@4.3.0
│ │ │ │ └── webpack@5.79.0 deduped
│ │ │ ├─┬ source-map-loader@1.1.3
│ │ │ │ └── webpack@5.79.0 deduped
│ │ │ ├─┬ webpack-dev-server@4.9.3
│ │ │ │ ├─┬ webpack-dev-middleware@5.3.3
│ │ │ │ │ └── webpack@5.79.0 deduped
│ │ │ │ └── webpack@5.79.0 deduped
│ │ │ └─┬ webpack@4.44.2
│ │ │   └─┬ terser-webpack-plugin@1.4.5
│ │ │     └── webpack@4.44.2 deduped
│ │ └─┬ webpack@4.44.2
│ │   └─┬ terser-webpack-plugin@1.4.5
│ │     └── webpack@4.44.2 deduped
│ └─┬ webpack@4.44.2
│   └─┬ terser-webpack-plugin@1.4.5
│     └── webpack@4.44.2 deduped
└─┬ babel-loader@9.1.2
  └─┬ webpack@5.79.0
    └─┬ terser-webpack-plugin@5.3.7
      └── webpack@5.79.0 deduped
```
Code on branch: https://github.com/necik11/spfx-pdfjs/tree/pdfjs

I already try almost every possible solutions:
![image](https://user-images.githubusercontent.com/25322303/232047858-c08a78f0-f647-486d-aae3-f2cdc51ed357.png)

Again, any tips would be very appreciated... webpack is giving me a headache... wouldn't it be easier to upgrade it to version 5? 😍

**Comment by AJIXuMuK** [comment]
@necik11 - seems like the problem is with nullish coalescing operator (`??`).
There are two options I can think of:
1. try to load the library as external: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library
2. use custom webpack rule with `babel-loader` for this specific module/path. Something like `include: /node_modules\/path-to-pdfjs\/blah.js/`

**Comment by necik11** [comment]
I finally figured it out...:
There was no problem in loading the library, because I tried different library imports..evenetuall try add some async function, change loading url or even adding module to types.d.ts -> nothing helped.. still same error.

From **issue 1** + instructions in spfx, I tried adding a rule to webpack also didn't help, it started giving me the error from issue2
...
But **YES** the error was probably in **WEBPACK** (problem in loading modules from those libraries):
├─┬ @microsoft/sp-build-web@1.17.1
│ ├─┬ @microsoft/gulp-core-build-webpack@5.2.30
│ │ └─┬ webpack@4.44.2

Webpack 4... and as it is written, you need to have v5 and more everywhere..
So the procedure for right working is as follows:
1. Add Custom rule to Webpack - what I have already stated here
2.  install babel libraries:
```
npm and @babel/preset-env --save-dev
npm and @babel/plugin-proposal-optional-chaining --save-dev
```
**and the most important babel-loader - but version 8.3.0 the latest version no longer supports webpack smaller than 5.**
```
npm and @babel-loader@8.3.0 --save-dev
```
thanks again for the tips and reply.
