### ISSUE TITLE
Error - [lint] Unexpected STDERR output from ESLint:  Oops! Something went wrong! :( ESLint: 8.7.0 TypeError: Cannot read properties of undefined (reading 'getFirstToken')

### ISSUE THREAD

**Issue by srkcode10** [SharePoint/sp-dev-docs#9006]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

PS C:\WINDOWS\system32> npm list -g --depth 0
C:\Users\user1\AppData\Roaming\npm
+-- @angular/cli@15.2.4
+-- @microsoft/generator-sharepoint@1.16.1
+-- @pnp/cli-microsoft365@3.11.0
+-- @types/jquery@2.0.48
+-- bower@1.8.8
+-- create-react-app@3.4.1
+-- gulp-cli@2.3.0
+-- nodemon@1.19.1
+-- npm-install-peers@1.2.2
+-- npm@9.7.1
+-- react@16.8.6
+-- typescript@4.1.5
+-- windows-build-tools@5.2.2
`-- yo@4.3.1

### Describe the bug / error

The error occurs while running the gulp build or gulp serve command from the terminal. 

Error - [lint] Unexpected STDERR output from ESLint: 
Oops! Something went wrong! :(
ESLint: 8.7.0
TypeError: Cannot read properties of undefined (reading 'getFirstToken')
Occurred while linting C:/SPODev/LBOApp/src/webparts/lboCalc/components/LboCalc.tsx:6
Rule: "@typescript-eslint/no-extra-semi"
    at ClassBody (C:/SPODev/LBOApp/node_modules/eslint/lib/rules/no-extra-semi.js:112:52)
    at ruleErrorHandler (C:/SPODev/LBOApp/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/linter.js:1079:28)
    at C:/SPODev/LBOApp/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:/SPODev/LBOApp/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:/SPODev/LBOApp/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (C:/SPODev/LBOApp/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (C:/SPODev/LBOApp/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (C:/SPODev/LBOApp/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at C:/SPODev/LBOApp/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/linter.js:1110:32

Error - [lint] 

### Steps to reproduce

PS C:\SPODev> yo @microsoft/sharepoint

     _-----_     ╭──────────────────────────╮
    |       |    │      Welcome to the      │
    |--(o)--|    │  SharePoint Online SPFx  │
   `---------´   │  Yeoman Generator@1.16.1 │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

See https://aka.ms/spfx-yeoman-info for more information on how to use this generator.
Let's create a new SharePoint solution.
? What is your solution name? Test1
? Which type of client-side component to create? WebPart
Add new Web part to solution test-1.
? What is your Web part name? TestApp
? Which template would you like to use? React

Hit enter and NPM Install will start.

### Expected behavior

The app should open in the workbench or the gulp build command should complete successfully.

**Comment by timdhahn** [comment]
I'm also having the this same issue with spfx 1.16.1. 

Updating to 1.17.3 resolves this eslint error. However, I don't recall seeing this error when I first scaffolded to test webparts in 1.16.1. Could something have introduced this issued in a transitive dependency?

**Comment by AJIXuMuK** [comment]
@timdhahn - yep, that is exactly what happened.
