### ISSUE TITLE
Unable to add a second web part to an existing on-prem solution

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#921]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Be able to add a second web part to an existing on-prem solution.

#### Observed Behavior
The following error occurs when trying to add another web part to an existing SPFx project:

```
Found config file: config.json
Cannot create two Web part (on-prem) with the same name.
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'forEach' of undefined
    at ConfigJsonManager.addV1Entry (/Users/waldek/tmp/123/node_modules/@microsoft/generator-sharepoint/lib/common/ConfigJsonManager.js:64:27)
    at WebpartGenerator.configuring (/Users/waldek/tmp/123/node_modules/@microsoft/generator-sharepoint/lib/generators/onPremWebpart/index.js:51:29)
    at Object.<anonymous> (/Users/waldek/tmp/123/node_modules/yeoman-generator/lib/index.js:408:23)
    at /Users/waldek/tmp/123/node_modules/run-async/index.js:25:25
    at /Users/waldek/tmp/123/node_modules/run-async/index.js:24:19
    at /Users/waldek/tmp/123/node_modules/yeoman-generator/lib/index.js:409:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

Generator: v1.3.2
Node: v6.11.2
npm: v4.6.1

#### Steps to Reproduce
- `yo @microsoft/sharepoint` (optionally you can include `--skip-install` to speed up the repro)
- baseline: onprem
- location: current folder
- name: _webpart1_
- framework: React
- `yo @microsoft/sharepoint` (again, possible with `--skip-install`)
- name: _webpart2_
- framework: React
- 💥  error

**Comment by VesaJuvonen** [comment]
Issue acknowledged and we are working on getting this solved. Just to add based on quick additional testing: name of the web aprt or selected framework does not have an impact on the outcome.

**Comment by waldekmastykarz** [comment]
This seems to be working fine with generator v1.3.4.
