### ISSUE TITLE
Set-PnPSite throws error: "The type of data at position nnnn is different than the one expected"

### ISSUE THREAD

**Issue by fjaeger1986** [SharePoint/sp-dev-docs#9470]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Windows PowerShell locally -> PnP 2.2.0/2.3.0
Azure Function -> PPnP 2.2.0/2.3.0

### Describe the bug / error

For a few days running Set-PnP(Tenant)Site with the DisableSharingForNonOwners switch results in an error "The type of data at position 3331 is different than the one expected". (The position number varies.) Multiple tenancies are affected.

```
Disable-PnPSharingForNonOwnersOfSite -Identity https://tenant.sharepoint.com/sites/oursite is also failing

Set-PnPSite -Identity https://xxx.sharepoint.com/sites/xxx -DisableSharingForNonOwners
```

### Steps to reproduce

Disable-PnPSharingForNonOwnersOfSite -Identity https://tenant.sharepoint.com/sites/oursite
Set-PnPSite -Identity https://xxx.sharepoint.com/sites/xxx -DisableSharingForNonOwners
#
From https://github.com/pnp/powershell/issues/3697#issuecomment-1900564475

Office365Tenant office365Tenant = new Office365Tenant(context);
context.Load(office365Tenant);
office365Tenant.DisableSharingForNonOwnersOfSite(siteUrl);
context.ExecuteQueryRetry();

### Expected behavior

Should Disable Sharing For Non Owners ;)

**Comment by Sean-LM** [comment]
This is also occurring for our team. It was functional before.

**Comment by ved-leachim** [comment]
I am working on an implementation for an automated extended spo property sync: [https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online](bulk-user-profile-update-api-for-sharepoint-online)

I am using a timer triggered durable function (Isolated .Net 8), the action is happening in an activity function:

```C#
        Office365Tenant tenant = new Office365Tenant(_ctx);
        _ctx.Load(tenant);
        _ctx.ExecuteQuery();
```
Following exception gets thrown on ...ExecuteQuery() line:

System.InvalidOperationException: The type of data at position 3331 is different than the one expected.

**Comment by cluber22** [comment]
Also having the exact same error which is effecting us uploading up to date details to SharePoint profiles.

**Comment by JohanKroese** [comment]
Same here. When I use Fiddler I can see that the POST to /_vti_bin/client.svc/ProcessQuery that returns the Office365Tenant object does return with a HTTP 200. It contains all the right properties for the object in json:

```
[
{
"SchemaVersion":"15.0.0.0","LibraryVersion":"16.0.24517.12007","ErrorInfo":null,"TraceCorrelationId":"3c1607a1-4018-8000-14fd-1c20f49c47f6"
},2,{
"IsNull":false
},3,{
"_ObjectType_":"Microsoft.Online.SharePoint.TenantManagement.Office365Tenant","
```
It is the Microsoft.SharePoint.Client object that fails while interpreting the returned json:
```

   at Microsoft.SharePoint.Client.JsonReader.ReadString()
   at Microsoft.SharePoint.Client.JsonReader.Read[T]()
   at Microsoft.SharePoint.Client.JsonReader.ReadList[T]()
   at Microsoft.Online.SharePoint.TenantManagement.Office365Tenant.InitOnePropertyFromJson(String peekedName, JsonReader reader)
   at Microsoft.SharePoint.Client.ClientObject.FromJson(JsonReader reader)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__57.MoveNext()
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__23.MoveNext()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\source\ConsoleApp2\ConsoleApp2\Program.cs:line 14
```

Interestingly enough the property that's around the 3300-3400 position is probably relatively new since it concerns the Esigntature stuff that was announced at Ignite:

"ESignatureSiteList":[

],"ESignatureSiteListFileName":"","ESignatureThirdPartyProviderInfoList":[
{
"_ObjectType_":"Microsoft.Online.SharePoint.TenantAdministration.EsignatureThirdPartyProvidersInfo","IsEnabled":false,"ProviderName":"DocuSign"
},{
"_ObjectType_":"Microsoft.Online.SharePoint.TenantAdministration.EsignatureThirdPartyProvidersInfo","IsEnabled":false,"ProviderName":"AdobeSign"
}

although that of course might be coincidental. 

Currently it seems that usage of the Office365Tenant is blocked until the Microsoft.SharePoint.Client library is fixed, or so it seems to me.

**Comment by cluber22** [comment]
So support have come back and said they ar closing my ticket.

**Comment by fjaeger1986** [comment]
Can confirm that it’s working fine again on PnP PowerShell 2.3.44-nightly.

**Comment by Sean-LM** [comment]
Our system (spanning both GCCH and Commercial) has started to function once again without any code changes. This appears to be fixed on the m365 side.

**Comment by cluber22** [comment]
Same - started working again 4 days ago. Bit concerning that this isn't covered by standard support.
