### ISSUE TITLE
InteractionRequiredAuthError for guest user with AadHttpClientFactory

### ISSUE THREAD

**Issue by annebraamburg** [SharePoint/sp-dev-docs#9496]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx version – 1.18.2
Node.js version – v18.19.0

### Describe the bug / error

Getting token for logged in guest user with AadHttpClientFactory results in a InteractionRequiredAuthError:

The user is a guest user with a office 365 account in another tenant. For regular users everything works fine.
Deleting and reinviting the user does not fix the problem.

### Steps to reproduce

1.	Log in with guest user

2.	Navigate to page with a webpart that will try to get a token with AadHttpClientFactory
a.	Webpart will try to get a token in this part

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;let client = await this.context.aadHttpClientFactory.getClient(resourceEndpoint);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;let response: HttpClientResponse = await client.post(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"https://...",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AadHttpClient.configurations.v1,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;options
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.context is WebPartContext

3.	Error while be thrown

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;InteractionRequiredAuthError: AADSTS50058: A silent sign-in request was sent but no user is signed in. Trace ID: 0401497f-5572-4437-83ee-32d3f835a000 Correlation ID: f0cb84e4-d076-4621-97e3-3373e2935589 Timestamp: 2024-01-24 15:18:27Z
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at t [as constructor] (chunk.vendors\~msalImplicit\~msalImplicitLegacy_none_d4284dbbb379893a62ca.js:1:8320)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at t [as constructor] (chunk.vendors\~msalImplicit\~msalImplicitLegacy_none_d4284dbbb379893a62ca.js:1:46382)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at new t (chunk.vendors\~msalImplicit\~msalImplicitLegacy_none_d4284dbbb379893a62ca.js:1:46801)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at e.saveTokenFromHash (chunk.vendors\~msalImplicit\~msalImplicitLegacy_none_d4284dbbb379893a62ca.js:1:90180)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at e.processCallBack (chunk.vendors\~msalImplicit\~msalImplicitLegacy_none_d4284dbbb379893a62ca.js:1:78427)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at e.handleAuthenticationResponse (chunk.vendors\~msalImplicit\~msalImplicitLegacy_none_d4284dbbb379893a62ca.js:1:79742)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at e.<anonymous> (chunk.vendors\~msalImplicit\~msalImplicitLegacy_none_d4284dbbb379893a62ca.js:1:74044)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sp-pages-assembly_nl-nl_6a2422a7f3ad9be86d7bc2ddfdb5fdc5.js:2:4729
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at Object.next (sp-pages-assembly_nl-nl_6a2422a7f3ad9be86d7bc2ddfdb5fdc5.js:2:4834)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at o (sp-pages-assembly_nl-nl_6a2422a7f3ad9be86d7bc2ddfdb5fdc5.js:2:3576)

4.	SharePoint will redirect the user to office 365 login page. After user logins again it works.
This happens for every webpart on the page, so for 4 webparts user must login 4 additional times.

### Expected behavior

Expect the spfx/webpart to silent sign in the user.

**Comment by annebraamburg** [comment]
@VesaJuvonen We are still experiencing the same issue, do you have any update?
