### ISSUE TITLE
have weird issues with SPFX webparts running inside teams

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#9512]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

i am getting some unkown error in new teams for SPFX webparts. everything works fine in classic, and classic web and new teams for web as well.
Issue is on new teams desktop app.

script error for: 1b64e0ca-dc77-4fad-ac1f-3ea79ceb05be_0.0.1/AppWebPartStrings
http://requirejs.org/docs/errors.html#scripterror

CALL STACK:
Error: Script error for: 1b64e0ca-dc77-4fad-ac1f-3ea79ceb05be_0.0.1/AppWebPartStrings
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_c7aa917482ec9ea53588c98d5ef9816a.js:121:12036), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_c7aa917482ec9ea53588c98d5ef9816a.js:121:12036), <anonymous>:30:244)

### Steps to reproduce

Sync SPFx webpart from App catalogue to Teams.
Open the app in teams

### Expected behavior

the app should work in teams

**Comment by harshdamaniahd** [comment]
i am still having this issue

**Comment by harshdamaniahd** [comment]
> @harshdamaniahd Unfortunately, I do not have any ideas. We've been running into a lot of issues with the new Teams as well :(

thanks for the reply 👍 . is there any appropriate place to raise this issue ?
