### ISSUE TITLE
Error: Cannot find module 'node:path'

### ISSUE THREAD

**Issue by MarioZagreb** [SharePoint/sp-dev-docs#9544]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- npm version 6.14.13
- SPFx version 1.18.2
- Node.js version 14.17.0

### Describe the bug / error

I am getting an error "Cannot find module 'node:path' when trying to create new spfx project (web part).
I am not able to create anything.
I have created multiple web parts and all old web parts are working fine.
I tried to install new version of Node (v20), no luck.

I get same error as here:
https://sharepoint.stackexchange.com/questions/311279/while-setting-up-a-spfx-solution-getting-nodepath-error

PS D:\tttt> gulp serve
Error: Cannot find module 'node:path'
Require stack:
- D:\tttt\node_modules\@microsoft\rush-lib\dist\rush-lib.js
- D:\tttt\node_modules\@microsoft\rush-lib\lib\index.js
- D:\tttt\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\devDeployPlugin\SpDevDeploy.js
- D:\tttt\node_modules\@microsoft\spfx-heft-plugins\lib\index.js
- D:\tttt\node_modules\@microsoft\sp-build-core-tasks\lib\webpack\ConfigureWebpackTask.js
- D:\tttt\node_modules\@microsoft\sp-build-core-tasks\lib\index.js
- D:\tttt\node_modules\@microsoft\sp-build-web\lib\index.js
- D:\tttt\gulpfile.js
- C:\Users\mm\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js
- C:\Users\mm\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- C:\Users\mm\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\index.js
- C:\Users\mm\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.149411 (D:\tttt\node_modules\@microsoft\rush-lib\dist\rush-lib.js:461:18)
    at __webpack_require__ (D:\tttt\node_modules\@microsoft\rush-lib\dist\rush-lib.js:562:41)
    at Object.74151 (D:\tttt\node_modules\@microsoft\rush-lib\dist\commons.js:18203:67)
    at __webpack_require__ (D:\tttt\node_modules\@microsoft\rush-lib\dist\rush-lib.js:562:41)
    at Object.62165 (D:\tttt\node_modules\@microsoft\rush-lib\dist\commons.js:10485:93)
    at __webpack_require__ (D:\tttt\node_modules\@microsoft\rush-lib\dist\rush-lib.js:562:41) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\tttt\\node_modules\\@microsoft\\rush-lib\\dist\\rush-lib.js',
    'D:\\tttt\\node_modules\\@microsoft\\rush-lib\\lib\\index.js',
    'D:\\tttt\\node_modules\\@microsoft\\spfx-heft-plugins\\lib\\plugins\\devDeployPlugin\\SpDevDeploy.js',
    'D:\\tttt\\node_modules\\@microsoft\\spfx-heft-plugins\\lib\\index.js',
    'D:\\tttt\\node_modules\\@microsoft\\sp-build-core-tasks\\lib\\webpack\\ConfigureWebpackTask.js',
    'D:\\tttt\\node_modules\\@microsoft\\sp-build-core-tasks\\lib\\index.js',
    'D:\\tttt\\node_modules\\@microsoft\\sp-build-web\\lib\\index.js',
    'D:\\tttt\\gulpfile.js',
    'C:\\Users\\mm\\AppData\\Roaming\\npm\\node_modules\\gulp\\node_modules\\gulp-cli\\lib\\shared\\require-or-import.js',
    'C:\\Users\\mm\\AppData\\Roaming\\npm\\node_modules\\gulp\\node_modules\\gulp-cli\\lib\\versioned\\^4.0.0\\index.js',
    'C:\\Users\\mm\\AppData\\Roaming\\npm\\node_modules\\gulp\\node_modules\\gulp-cli\\index.js',
    'C:\\Users\\mm\\AppData\\Roaming\\npm\\node_modules\\gulp\\bin\\gulp.js'
  ]
}

### Steps to reproduce

1. Create new folder (md tttt)
2. position in that new folder (cd tttt)
3. yo @microsoft/sharepoint
4. gulp serve 
5. ERROR

### Expected behavior

I expect for Hello World project to work, i am not able to create any spfx project.

**Comment by MarioZagreb** [comment]
Ok, the solution was found in package.json file, in row:
"engines": {
    "node": ">=16.13.0 <17.0.0 || >=18.17.1 <19.0.0"
  },

So, new node.js (v20) isn't good enough. So, I tried with downloading and installing 18.19 and it worked.
Of course, now my old projects aren't building, but I can use old node.js version for them or upgrade then to new...
