### ISSUE TITLE
Public CDN for SPFx Solution is not working for every Solution

### ISSUE THREAD

**Issue by EA12** [SharePoint/sp-dev-docs#9656]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version Edge 124.0.2478.51 (Offizielles Build) (64-Bit)
- SPFx version 1.18.2
- Node.js version 18.18.0

### Describe the bug / error

We have a public CDN configured and most of our SPFx Solutions are working fine.

![image](https://github.com/SharePoint/sp-dev-docs/assets/22025808/d688df84-7dae-4290-a17e-0e9d1ce1fdd9)

![image](https://github.com/SharePoint/sp-dev-docs/assets/22025808/2cc42c47-a3b8-40dd-be2f-b398bb512985)

Some SPFx Solution are not loading the resources from publiccdn.sharepointonline.com and that results in errors:

Refused to execute script from 'https://ourtenant.sharepoint.com/_layouts/15/AccessDenied.aspx?p=16&type=accessremoved&correlation=447a22a1-0018-8000-a4eb-b6d4e7b9b0f5' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Could not load req-form-customizer in require**. Error: Script error for: 735c5639-8053-4557-8177-54db66f2d5cd_0.0.1/ControlStrings
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (sp-list-form-application-assembly_de-de_8180d4d2c1b44deddcb265fd6d5bbcea.js:189:10397), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at e (sp-list-form-application-assembly_de-de_8180d4d2c1b44deddcb265fd6d5bbcea.js:189:10397)

I already cleaned those Solutions, rebuild and redeployed them with no avail.
From viewing related issues, I see that you had provided bug fixes to the public CDN. May be you have an error again there.

### Steps to reproduce

1. Enable a public CDN in your tenant
2. Use a new communication site to host the resource files from the SPFx Solution
3. Enable a specific folder in a specific library as public origin by power shell
4. Configure the cdnBasePath in write-manifests.json to the origin
5. Deploy a SPFx Solution to a Site Collection App-Catalog
6. Deploy the files from release/assets folder of the SPFx Project to the origin
7. Add and test the app

### Expected behavior

The app should be shown, no matter if it is a webpart or a forms customizer and should be loaded from the public CDN

**Comment by EA12** [comment]
My bad. Sorry, i must answer my own question.
In those failed solutions I had a wrong cdnbasepath. It must be like this:
![image](https://github.com/SharePoint/sp-dev-docs/assets/22025808/70aad483-d97c-4a92-b969-804a5dc71b62)

but I had onle the full qualified url to my folder but not the prefix https://publiccdn.sharepointonline.com/
