### ISSUE TITLE
SPFX version 1.19.0 - @microsoft/sp-build-web": "1.20.1 not open pdf.js

### ISSUE THREAD

**Issue by necik11** [SharePoint/sp-dev-docs#9727]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - latest
- SPFx version - 1.19.0
- Node.js version - v18.19.0

### Describe the bug / error

I wanted upgrade my spfx project to version 1.19.0 cause i am using library PDF.js, which need webpack 5 and higher or additional loader (until now I have used babel-loader). 

Few months ago when was beta version of 1.19.0 release I tried it and everything worked as it should. 
But I was waiting for the official version.

Unfortunately, I tried to upgrade it today after upgrading this dependency:
 "@microsoft/sp-build-web": "1.18.1", this "@microsoft/sp-build-web": "1.20.1"
my pdf.js library stops working with the error:

```
Unexpected token 'catch' (at pdf.mjs:19862:1)
 at ./node_modules/pdfjs-dist/build/pdf.mjs (bundle.js:1035:1)
 at __nested_webpack_require_2262005_
..
/* harmony import */ var pdfjs_dist__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! pdfjs-dist */ "./node_modules/pdfjs-dist/build/pdf.mjs");
..
catch(e) { __webpack_async_result__(e); } }, 1);
```
![image](https://github.com/SharePoint/sp-dev-docs/assets/25322303/c10b103e-3cc4-4120-af67-843f8e238070)

when I upgrade project and only this library downgrade everything works, but i am not sure if its best practices..
![image](https://github.com/SharePoint/sp-dev-docs/assets/25322303/a4a66fa4-1dff-42c0-94d0-5b3cc9ac6d74)

I still don't see why the dependencies are in version 1.19.0
and devDependencies 1.20.1

### Steps to reproduce

1. Create SPFX webpart
2. Create Project with pdf.js Lib and by webpack bundle  or maybe just install pdf-dist
3. Run

### Expected behavior

Open the pdf document:
![image](https://github.com/SharePoint/sp-dev-docs/assets/25322303/a337bd0d-b158-430b-9210-22ec0e387f3f)

**Comment by necik11** [comment]
Here is a [sample application](https://github.com/necik11/pdfJsPlayGround/tree/main/sample-pdf-js) of how pdf.js and webpack could be used. After npm run build i will get dev.js and prod.js.

After import i have got problem [Object Object].

But I found this in the second issue: [Extremely hack-y way to debug this problem](https://github.com/SharePoint/sp-dev-docs/issues/9675#issuecomment-2150221474)

After I finally got some mean error message:

```
Module not found: Error: Can't resolve 'http' - BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.  ...
Module not found: Error: Can't resolve 'canvas' ...
Module not found: Error: Can't resolve 'fs' ...
Module not found: Error: Can't resolve 'path2d'...
Module not found: Error: Can't resolve 'https' ...
Module not found: Error: Can't resolve 'url' ...
```

Is there a way to setup gulpfile.js? Or is it an error when exporting bundle.js using webpack?

**Comment by StfBauer** [comment]
Or simply debug it in a proper way without manipulation of the build chain with:
https://github.com/SharePoint/sp-dev-docs/issues/9675#issuecomment-2151825299
and
https://github.com/SharePoint/sp-dev-docs/issues/9675#issuecomment-2151867681

**Comment by necik11** [comment]
> Or simply debug it in a proper way without manipulation of the build chain with: [#9675 (comment)](https://github.com/SharePoint/sp-dev-docs/issues/9675#issuecomment-2151825299) and [#9675 (comment)](https://github.com/SharePoint/sp-dev-docs/issues/9675#issuecomment-2151867681)

I probably don't understand..

`gulp bundle`  doesn't work - only returned error [Object Object]

that's why I used the overwritten line in :
node_modules/@microsoft/gulp-core-build-webpack/lib/WebpackTask.js

and then I found the errors listed above.

Mainly problem is:
webpack < 5 used to include polyfills for node.js core modules by default.\nThis is no longer the case.
Verify if you need this module and configure a polyfill for it.\n\nIf you want to include a polyfill,

so I am asking how deal with it?

I found that I should put something like this in webpack.js:

```
module.exports = {
...
 plugins: [
 new NodePolyfillPlugin(),
 ],
 resolve: {
 fallback: {
 "http": require.resolve("stream-http"),
 "https": require.resolve("https-browserify"),
 "url": require.resolve("url/"),
 "fs": false,
 "path2d": false,
 "canvas": require.resolve("canvas"),
 }
 }
};

```

Do I really need to install all the packages manually?

**Comment by StfBauer** [comment]
`gulp bundle`still works and because in a dev build it do not really matter or rely on webpack. It prepares in additional file to have to embed the webpart on a page.

Rename the SPPKG file to a .zip and extract on a working project and you won't find any javascript at all in there.
Hence you can still deploy and install the web part and server everything from localhost.

In fact the webpack is only used to load your solution and do nothing during the code compilation.

So deploy a dev build without the --ship - gulp serve from localhost and embedd the web part on the page.

Magically you will see all the npm packages in the browser that are missing for you solution.

More on that on: https://n8d.at/debug-and-fix-webpack-object-object-error-in-sharepoint-web-parts

**Comment by necik11** [comment]
Even if I use your instructions, as I already announced it's not showing an error.
I did the same as written, the component was loaded, only this will be written at the beginning:

[13:40:37] Error - [webpack] 'dist':
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]

No problem is displayed, neither in the terminal nor in the web part - here the component is loaded as it should!

The problem is that when I
```
gulp clean
gulp bundle --ship
```
I get an error here
```
Error - [webpack] 'dist':
[object Object]
```

and I'll conclude
`gulp package-solution --ship`

so I get an error:
Error - [package-solution] No manifests were found in

but if I grant:
```
gulp bundle
gulp package-solution --ship
```

so everything seems to have passed, but of course the package was only for the local version

I keep thinking that if I change the line
` this.logError(`'${outputDir}':` + os_1.EOL + statsResult.errors.map(x => JSON.stringify(x, null, 2)).join(os_1.EOL) + os_1.EOL);
`
 and call:
`gulp bundle > output.txt`

I get the whole debug + error:

"message": "Module not found: Error: Can't resolve 'https' in 'C:...\\node_modules\dist'\n\nBREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.\nThis is no longer the case. Verify if you need this module and configure a polyfill for it.\n\nIf you want to include a polyfill, you need to:\n\t- add a fallback 'resolve. fallback: { \"https\": require.resolve(\"https-browserify\") }'\n\t- install 'https-browserify'\nIf you don't want to include a polyfill, you can use an empty module like this:\n\tresolve.fallback: { \"https\": false }", [39m

+5 more errors show above.

**Comment by StfBauer** [comment]
Done't use `--ship` on package-solution this will give you a production build. You can deploy any web part to any site and load the webpart from localhost when you don't use the `--ship` options.

This option is exclusively for production build, not when you develope a web part.

So the only thing to do is:

```sh
gulp bundle
gulp package-solution
```

Deploy the web part regularly and you will find the issue in your browser like I wrote in my blog post.

In your case to fix your issue:

```sh
npm install --save-dev https-browserify
```

**Comment by necik11** [comment]
As I wrote, there were more problems and I asked if there was anything better than installing everything manually.

Anyway, what helped me (install all missing packages manually):
`npm install --save-dev node-polyfill-webpack-plugin https-browserify stream-http url canvas path2d-polyfill`

edit **gulpfile.js**:
```
const build = require('@microsoft/sp-build-web');
const webpackConfig = require('./webpack.extend.js');
```

**webpack.extend.js**:
```

const NodePolyfillPlugin = require('node-polyfill-webpack-plugin');
const path = require('path'); // Add this line

module.exports = (config) => {
 config.plugins.push(new NodePolyfillPlugin());

 config.resolve = {
 ...config.resolve,
 fallback: {
 ...config.resolve.fallback,
 "http": require.resolve("stream-http"),
 "https": require.resolve("https-browserify"),
 "url": require.resolve("url/"),
 "fs": false,
 "path2d": path.resolve(__dirname, 'node_modules/path2d-polyfill/dist/path2d-polyfill.js'),
 "canvas": require.resolve("canvas")
 }
 };

 return configuration;
};
```

Actually the production version works beautifully, the only problem/warning
Warning - [webpack] 'dist':
2:63115-63137: Critical dependency: the request of a dependency is an expression
The problem is somewhere in require :smile: ...

But I still don't know if I'm doing everything right.
Here is the my code for SPFx webpart : [spfx-webpack5](https://github.com/necik11/pdfJsPlayGround/tree/main/spfx-webpack5)

Otherwise, I will be glad for any advice/ideas and questions.

**Comment by Amey-MSFT** [comment]
Hello @necik11,
Thank you for bringing this issue to our attention. Could you please confirm if the issue still persists for you?

**Comment by Amey-MSFT** [comment]
We are closing this issue for now. If the problem persists, feel free to reopen it or open a new one.
