### ISSUE TITLE
Webparts not loading in device emulation

### ISSUE THREAD

**Issue by sliziky** [SharePoint/sp-dev-docs#9750]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version 
- SPFx version 1.18.0
- Node.js version 16.14.0
- etc

### Describe the bug / error

I have built an SPFx package containing 1 form webpart and deployed it into Sharepoint A (site collection app catalog) and Sharepoint B (global app catalog):

- Sharepoint A - web part is fully working (desktop/mobile emulation/mobile)
- Sharepoint B - when browsing on desktop it works fine, but as soon as I switch to mobile emulation/mobile I get this on-screen error:

```
ERROR:
Script error for: f3a9abfa-9d4a-457a-88dc-07b89b53bf8a_0.0.1/ControlStrings
http://requirejs.org/docs/errors.html#scripterror

CALL STACK:
Error: Script error for: f3a9abfa-9d4a-457a-88dc-07b89b53bf8a_0.0.1/ControlStrings
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_cs-cz_c113e52d950edbc28a80ec2e906317e2.js:198:10340), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_cs-cz_c113e52d950edbc28a80ec2e906317e2.js:198:10340), <anonymous>:30:244)
```
and also this Console error:
```
Could not load form-web-part in require. Error: Script error for: f3a9abfa-9d4a-457a-88dc-07b89b53bf8a_0.0.1/ControlStrings
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (sp-pages-assembly_cs-cz_c113e52d950edbc28a80ec2e906317e2.js:198:10340), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at e (sp-pages-assembly_cs-cz_c113e52d950edbc28a80ec2e906317e2.js:198:10340), <anonymous>:30:244)
```

as soon as I cancel emulation and do refresh, the error is gone.

I have also tried with SPFx 1.18.2 and 1.12.1 but happens all the time. Could there be any problem with Sharepoint settings? Catalog? 

Thanks

### Steps to reproduce

1. Deployed SPFx package and added it into site
2. Added webpart into sitepage
3. Webpart throws error in mobule emulation

### Expected behavior

I expect Sharepoint to render webpart in mobule emulation

**Comment by Amey-MSFT** [comment]
Hello @sliziky,
Thank you for bringing this issue to our attention. Could you please confirm if the issue still persists for you?

**Comment by Amey-MSFT** [comment]
We are closing this issue for now. If the problem persists, feel free to reopen it or open a new one.
