### ISSUE TITLE
Unable to approve a site page with versioning enabled

### ISSUE THREAD

**Issue by vspinelli** [SharePoint/sp-dev-docs#9777]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

Since few hours, in our customers sites (different tenants), where we have enabled the versioning on the SitePages library when we try to approve a page, after clicked on "Submit for approvals" button, the panel showed loads infinitely, not allowing us to approve the page.

![image](https://github.com/SharePoint/sp-dev-docs/assets/16682138/fd4c8ef3-2346-436a-941b-13b721fd2627)

We get an error message in the browser console:
```
TypeError: Cannot read properties of undefined (reading 'id')
    at e._isFlowBasedOnContentApprovalTemplate (chunk.sp-pages-flow_it-it_c1dbfee833970154d0e7.js:4:580)
    at chunk.sp-pages-flow_it-it_c1dbfee833970154d0e7.js:4:1673
    at Array.filter (<anonymous>)
    at chunk.sp-pages-flow_it-it_c1dbfee833970154d0e7.js:4:1645
```

### Steps to reproduce

1. Enable the versioning on SitePages
![image](https://github.com/SharePoint/sp-dev-docs/assets/16682138/208f125c-9fc5-4d7b-8438-02d87056e868)

2. Create a page and send a request to approve it (save the page and the click on "Submit for approval" button)

### Expected behavior

The approval request is sent to the approvers

**Comment by vspinelli** [comment]
Update: not in all sites (where the approval process is enabled) in the same tenant

**Comment by vspinelli** [comment]
Now the problem should be resolved. It's really frustrating not to receive any communication of blocking problems on the normal use of SharePoint
