### ISSUE TITLE
SharePoint Embedded assign permissions to container to an Azure AD group

### ISSUE THREAD

**Issue by mick-anderson24** [SharePoint/sp-dev-docs#9805]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Microsoft.graph SDK      <PackageVersion Include="Microsoft.Graph" Version="5.56.0" />

### Describe the bug / error

Using the graphServiceClient I am attempting to add permissions to a SharePoint embedded container to an Azure AD group.  The examples and the documentation on the Graph API don't have examples and nothing says it isn't possible to assign a group to the sharepoint embedded container.  Below is the executing code:

`var requestBody = new Permission
{
	Roles = new List<string>
	{
		"writer"
	},
	GrantedToV2 = new SharePointIdentitySet
	{
		Group = new Identity
		{
			Id = "17d4e352-2cff-41e8-902a-96ad2f33f3d0"
		},
	}
};

try
{

	var permission = await _graphServiceClient.Storage.FileStorage.Containers[$"{id}"].Permissions.PostAsync(requestBody);
	var p = permission;
}
catch(Exception ex)
{
	var exception = ex;
}`

The exception I am seeing is: 'userPrincipalName' is required.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<ThrowIfFailedResponse>d__28.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Graph.Storage.FileStorage.Containers.Item.Permissions.PermissionsRequestBuilder.<PostAsync>d__7.MoveNext()
   
   

### Steps to reproduce

1. Ensure you have the graphServiceClient configured and granted permissions with scopes "FileStorageContainer.Selected"
2. Execute the following code: `var requestBody = new Permission
{
	Roles = new List<string>
	{
		"writer"
	},
	GrantedToV2 = new SharePointIdentitySet
	{
		Group = new Identity
		{
			Id = "17d4e352-2cff-41e8-902a-96ad2f33f3d0"
		},
	}
};

try
{

	var permission = await _graphServiceClient.Storage.FileStorage.Containers[$"{id}"].Permissions.PostAsync(requestBody);
	var p = permission;
}
catch(Exception ex)
{
	var exception = ex;
}`
3. See exception

### Expected behavior

I would expect to be able to assign permissions to an Azure AD group to a Sharepoint embedded container.  This is to allow all the members of the group permissions to the files in that container.

**Comment by Ashlesha-MSFT** [comment]
Hello @mick-anderson24,
We will investigate and if we require further information we will reach out to you. Please use[(https://aka.ms/DevCommunityEscalationForm)](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR4mTPG34N0xHuJATbbeqmGlUNlAwSlpSNlpPTkszVkRPMFgzNVdaS0dTUy4u) to escalate if you don't get replies in two working days.

Best regards, Teams

**Comment by Ashlesha-MSFT** [comment]
@mick-anderson24,
Have you verified below sample [Samples/spe-ocr-sample](https://github.com/microsoft/SharePoint-Embedded-Samples/tree/a5693a68786dab8ac2b0ebd2ca263411d8c4140e/Samples/spe-ocr-sample)
Also refer to this related GitHub issue: https://github.com/SharePoint/sp-dev-docs/issues/9425

**Comment by Ashlesha-MSFT** [comment]
We are closing this issue for now. If the problem persists, feel free to reopen it or open a new one.
