### ISSUE TITLE
Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_2.2.1. Store had [3.0.2].

### ISSUE THREAD

**Issue by da-maxl** [SharePoint/sp-dev-docs#9836]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.16.1
- Node.js version: 16.18.

 "dependencies": {
    "@microsoft/decorators": "1.16.1",
    "@microsoft/mgt-react": "2.6.1",
    "@microsoft/mgt-sharepoint-provider": "2.6.1",
    "@microsoft/sp-adaptive-card-extension-base": "1.16.1",
    "@microsoft/sp-application-base": "1.16.1",
    "@microsoft/sp-core-library": "1.16.1",
    "@microsoft/sp-dialog": "1.16.1",
    "@microsoft/sp-lodash-subset": "1.16.1",
    "@microsoft/sp-office-ui-fabric-core": "1.16.1",
    "@microsoft/sp-property-pane": "1.16.1",
    "@microsoft/sp-webpart-base": "1.16.1",
    "@pnp/graph": "2.14.0",
    "@pnp/sp": "2.14.0",
    "@pnp/spfx-controls-react": "3.12.0",
    "@pnp/spfx-property-controls": "3.11.0",
    "@uifabric/file-type-icons": "7.10.10",
    "moment": "2.29.4",
    "office-ui-fabric-react": "7.199.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-router-dom": "5.3.4",
    "tslib": "2.3.1"
  },

### Describe the bug / error

One of our custom SharePoint Webparts which was running fine for over a year now suddenly stopped working a few days ago, stating the following error:
Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_2.2.1. Store had [3.0.2]. Service worker version: odsp-web-prod_2024-07-19.009; App version: odsp-web-prod_2024-07-19.012; Next app version: odsp-web-prod_2024-07-19.012

CALL STACK:
Error: Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_2.2.1. Store had [3.0.2]. Service worker version: odsp-web-prod_2024-07-19.009; App version: odsp-web-prod_2024-07-19.012; Next app version: odsp-web-prod_2024-07-19.012
    at e.getManifest (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:207:5083)
    at e.requestManifest (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:207:7401)
    at e._configureComponentResource (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:199:9476)
    at e.configLoadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:199:7324)
    at e._loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:199:12715)
    at e.loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:209:346)
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:199:11071
    at new Promise (<anonymous>)
    at e.loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:199:10957)
    at e.loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:199:2270)

As far as we analyzed it for now, it seems that SharePoint somehow isn't providing v.2.2.1 of microsoft-graph-client any more.
We suspect there was an breaking update to SharePoint lately. 

### Steps to reproduce

No changes were made to the already working Webpart, so basically setting up a new webpart with the given dependecies and SPFx version should lead to the error.

### Expected behavior

Webpart works again with the expected microsoft-graph-client 2.2.1.

**Comment by da-maxl** [comment]
We noticed that the problem does not appear on some of our customers tenants. 
One finding is, that the following script seems to get loaded correctly on the other tenants but is missing somehow on our productive tenant.:
![image](https://github.com/user-attachments/assets/a1d6dd86-a0e4-4f09-a955-1cd68967f3e7)
vs.
![image](https://github.com/user-attachments/assets/7c2bae57-ba1b-47dc-a029-d68bc15acf60)

**Comment by Ashlesha-MSFT** [comment]
Hello @da-maxl,
Thank you for bringing this issue to our attention. We will look into it and get back to you shortly.

**Comment by Ashlesha-MSFT** [comment]
@da-maxl,
It should be resolved by changing component id with new guid.
https://stackoverflow.com/questions/69560569/mgt-spfx-web-part-error-manifest-not-found-for-component-id-and-version-2-3-0#:~:text=This%20error%20occurs%20if%20you%20don%27t%20have%20the,the%20product%20id%20present%20in%20the%20app%20catalog.

Can you please confirm.

**Comment by Ashlesha-MSFT** [comment]
We are closing this issue for now. If the problem persists, feel free to reopen it or open a new one.
